### ISSUE TITLE
Edit example

### ISSUE THREAD

**Issue by MitaiGit** [grpc/grpc-web#1016]
Edit your code under api v3 api v2 support will be discontinued soon [https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/helloworld/envoy.yaml](url)
[https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v2_support](url)

**Comment by MitaiGit** [comment]
`[2020-12-26 22:37:46.003][3714][warning][misc] [bazel-out/k8-opt/bin/external/envoy/source/extensions/common/_virtual_includes/utility_lib/extensions/common/utility.h:65] Using deprecated extension name 'envoy.http_connection_manager' for 'envoy.filters.network.http_connection_manager'. This name will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details.
`

**Comment by stanley-cheung** [comment]
Fixed
