### ISSUE TITLE
Envoy yaml file is deprecated

### ISSUE THREAD

**Issue by steeling** [grpc/grpc-web#1024]
The envoy yaml file is for v2 grpc-web/net/grpc/gateway/examples/echo/envoy.yaml
which is now deprecated, and won't run with newer versions of envoy directly. https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition

**Comment by stanley-cheung** [comment]
#1021?

**Comment by stanley-cheung** [comment]
Fixed.
