### ISSUE TITLE
about file .proto complie to .js/.ts, the field be changed 

### ISSUE THREAD

**Issue by jetsoman** [grpc/grpc-web#1032]
my english is not good, but i hope i can describe Understandable

when i code a proto file, and complie it to .js/.ts as grpc-web client, but them field be changed by the funtion toObject()!
for example:
      "coreClass" in the proto but "coreclass" in the js/ts, and key word "repeat" changed to "XXXList"/"map" changed to "XXXMap"
that resulting in field Inconsistent front and back， Not what i hope

i search the change code in file grpc_generator.cc about line 448

my question:
1、why change the field?
2、Is it possible config this change function

please!

**Comment by stanley-cheung** [comment]
The APIs you mentioned are the protobuf API, not grpc-web. A `repeat` field's API is `getXXXList()` for protobuf JS. This isn't something we just made up here in grpc-web.
