### ISSUE TITLE
All the interop test fail

### ISSUE THREAD

**Issue by MarnixKuijs** [grpc/grpc-web#1040]
I was following the instructions mention in the [README](https://github.com/grpc/grpc-web/blob/master/test/interop/README.md) of the interop test, then when executing the test via npm test or in the browser all the test fail. I did notice the issue #436 and even after changing to what was recommended all the test still fail. It seems that they fail due to time out, so I'm suspecting that somewhere in the configuration something is wrong which prevents the grpc request from executing.

## Meta
Os: Windows 10 version 2004

**Comment by stanley-cheung** [comment]
Sorry we probably won't have resources to make sure this run properly in Windows. All our CI tests run on linux.
