### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by pro-wh** [grpc/grpc-web#1043]
Maintainers, could you make a new release of grpc-web? We'd like to start using the fix from #1025.

**Comment by stanley-cheung** [comment]
Acknowledged. Sorry about the delay.

**Comment by JPeaker** [comment]
@stanley-cheung Any update on a new release coming? There's a specific bug that has been fixed in `main` that I'd really like to make use of!

**Comment by jayars** [comment]
Hi, am also wondering if there's a new release on the roadmap?
Hoping to get the fix from https://github.com/grpc/grpc-web/issues/939.
Thanks

**Comment by sampajano** [comment]
Thanks for the interest and sorry again for the delay!

We're definitely committed to cutting a new release soon.. It's just that there are currently some blocker issues (due to our dependencies) that we're working through.. But hopefully will be resolved soon :)

Thanks for the patience! :)
