### ISSUE TITLE
Helloworld example has problem

### ISSUE THREAD

**Issue by zredb** [grpc/grpc-web#1048]
The readme.md envoy config is not consistent with envoy.yaml file content.

**Comment by stanley-cheung** [comment]
Any specific breaking changes?

**Comment by acebelowzero** [comment]
syntax in the envoy.yaml is for envoy v2 and was deprecated you have to use v3. @stanley-cheung

**Comment by stanley-cheung** [comment]
I believe this is already done? https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml

Our integration test has been using envoy `v1.17.0` with no issue.
