### ISSUE TITLE
Problems with passing metadata to Go backend server

### ISSUE THREAD

**Issue by janiskemper** [grpc/grpc-web#1061]
I have a setup with a Vue.js frontend where I use grpc-web, an Envoy proxy and a Go backend server. 
I use the code
```
headers, ok := metadata.FromIncomingContext(ctx)
```
on to read the metadata on server-side. However, it always gives me ok==false, so that no metadata exists. In the frontend I use the code 
```client.sayHello(data, {testmeta: 'test'})```, but no metadata reaches the backend. I also tried different configurations of the Envoy proxy and added the key to both ```allow_headers``` and ```expose_headers``` (although I am not sure whether this has any effect). 
Do you have any ideas? 

A similar problem is described in https://github.com/grpc/grpc-web/issues/691, but it did not resolve my problem. In this issue the solution was to import the grpc node.js module and use its metadata object, but importing it breaks my Vue.js code with the error ```Uncaught TypeError: n.version is undefined```, so I wasn't even able to try it out. However, in the docs the metadata is just a normal object, anyway. So importing the grpc node.js module seems not like a valid solution to me (https://github.com/grpc/grpc-web#3-write-your-js-client)

**Comment by janiskemper** [comment]
I fixed the problem with the grpc node.js module breaking my app. Now I can confirm that the following solution is also not working for me: 
```
      const metadata = new grpc.Metadata()
      metadata.add('custom-header-1', 'value1')
```

**Comment by stanley-cheung** [comment]
If you use the browser "inspect" window, the "Networks" tab, find the RPCs from your grpc-web app, do you see your custom header being sent as part of the "Request header"?

**Comment by janiskemper** [comment]
Yes I do!

**Comment by stanley-cheung** [comment]
So your custom metadata made it out of the grpc-web browser app and made it to Envoy. Now you need to debug on the Envoy -> grpc backend connection to see why it gets dropped.

**Comment by janiskemper** [comment]
Okay. As I configured all the components as described in the docs, I thought it is a translation problem from a grpc-web client to a grpc server. I'll close it for now and follow your suggestion!
