### ISSUE TITLE
stream never ends if server ends connection

### ISSUE THREAD

**Issue by guyguy333** [grpc/grpc-web#1078]
Hi,

We had an issue with Envoy closing connections too early with a gRPC Web server-stream. However, in that case, grpc Web didn't detect stream close (onEnd or onError is never called (I would expected on Error)). In case server already streamed data, return code is 200. I thought I had an issue with my code but it's really simple so I did try to use improbable grpc-web and I can see this implementation handles server stream close properly with "onError". I guess there is an issue with connection close and stream. Any ideas ?

Using v1.2.1

Thanks

**Comment by girafferiel** [comment]
have u add timeout: 0s and stream_idle_timeout: 0s in ur envoy config? 
https://github.com/grpc/grpc-web/pull/1057
https://github.com/grpc/grpc-web/issues/557
I have the same server streaming problem, https://github.com/grpc/grpc-web/issues/1075 but for me onError is called with
code: 2, details: "Http response at 400 or 500 level
still not able to solve:(

**Comment by guyguy333** [comment]
I didn't set `stream_idle_timeout: 0s` because in my case a cut down during stream is not an issue. I've a solution to retry (and so continue) on each fail. Moreover, in front of Envoy, I've an Nginx with a proxy timeout. So the issue can be from Nginx or Envoy. I would like my web application to be robust. Currently, the implementation of grpc-web doesn't detect a connection close or maybe it does but no callback are triggered and so I never know the stream closed which is a huge issue for us. I believe a callback can be triggered as improbable implementation does.

**Comment by guyguy333** [comment]
Finally, the issue is not this library, it's devtools : https://github.com/SafetyCulture/grpc-web-devtools/issues/62
