### ISSUE TITLE
Does nginx/1.18.0 (Ubuntu) support grpc-web server-side streaming?

### ISSUE THREAD

**Issue by wchbrad** [grpc/grpc-web#1087]
Hello,I know that envoy is the default proxy, but I now want to use grpc-web on the original front-end and back-end separation project that uses nginx. I know whether nginx supports grpc-web server-side streaming.
In addition, I looked at other issues and it seems that nginx does not support grpc-web?

**Comment by psyhonut** [comment]
Yes.

**Comment by sampajano** [comment]
Please refer to https://github.com/grpc/grpc-web/discussions/1322 too.

Closing for now :)
