### ISSUE TITLE
Error in pulling docker.io/grpcweb/prereqs

### ISSUE THREAD

**Issue by dudebing99** [grpc/grpc-web#1090]
According https://grpc.io/docs/platforms/web/quickstart/, try to pull all dependencies and got errors: 

**ERROR: repository docker.io/grpcweb/prereqs not found: does not exist or no pull access**

```bash
[root@localhost grpc-web]# docker-compose pull
Pulling common (grpcweb/common:latest)...
Trying to pull repository docker.io/grpcweb/common ... 
latest: Pulling from docker.io/grpcweb/common
Digest: sha256:15d28c9c0f5fc41c3c9989bd6750806920bf7dc1ec6c0e20cc008c84051e5ffb
Status: Image is up to date for docker.io/grpcweb/common:latest
Pulling prereqs (grpcweb/prereqs:latest)...
Trying to pull repository docker.io/grpcweb/prereqs ... 
ERROR: repository docker.io/grpcweb/prereqs not found: does not exist or no pull access
```

**Comment by dudebing99** [comment]
docker version
```bash
[root@localhost grpc-web]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-205.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Apr 28 13:37:12 2021
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-205.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Apr 28 13:37:12 2021
 OS/Arch:         linux/amd64
 Experimental:    false
```

docker compose version
```bash
[root@localhost grpc-web]# docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

os version
```bash
[root@localhost grpc-web]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

kernel version
```bash
[root@localhost grpc-web]# uname -a
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by emicklei** [comment]
Today I noticed that it is building from source as a fallback. However, that fails for another reason:

**grpc-web status**
commit a56e7212a382545c9692e510c0e780928a5b2d4a (HEAD -> master, origin/master, origin/HEAD)
Author: 06kellyjac <dev@j-k.io>
Date:   Wed Aug 11 11:44:28 2021 +0100

**expected**
Docker image prereqs build success.

**output**
<details>
<pre>
....% docker-compose pull
Pulling common              ... done
Pulling prereqs             ... done
Pulling echo-server         ... done
Pulling node-server         ... done
Pulling node-interop-server ... done
Pulling envoy               ... done
Pulling grpcwebproxy        ... done
Pulling commonjs-client     ... done
Pulling closure-client      ... done
Pulling ts-client           ... done
Pulling binary-client       ... done
Pulling interop-client      ... done
Pulling java-interop-server ... done
Pulling protoc-plugin       ... done
WARNING: Some service image(s) must be built from source by running:
    docker-compose build ts-client binary-client echo-server java-interop-server protoc-plugin grpcwebproxy closure-client node-interop-server interop-client prereqs
..... grpc-web %  docker-compose build ts-client binary-client echo-server java-interop-server protoc-plugin grpcwebproxy closure-client node-interop-server interop-client prereqs
Building prereqs
[+] Building 357.0s (18/21)
 => [internal] load build definition from Dockerfile                                                                                                                                                        0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/grpcweb/common:latest                                                                                                                                            0.0s
 => [ 1/17] FROM docker.io/grpcweb/common                                                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                           0.1s
 => => transferring context: 18.27kB                                                                                                                                                                        0.1s
 => CACHED [ 2/17] RUN echo "\nloglevel=error\n" >> $HOME/.npmrc                                                                                                                                            0.0s
 => CACHED [ 3/17] WORKDIR /github/grpc-web                                                                                                                                                                 0.0s
 => CACHED [ 4/17] COPY ./scripts ./scripts                                                                                                                                                                 0.0s
 => CACHED [ 5/17] RUN ./scripts/init_submodules.sh                                                                                                                                                         0.0s
 => CACHED [ 6/17] COPY ./Makefile ./Makefile                                                                                                                                                               0.0s
 => CACHED [ 7/17] COPY ./WORKSPACE ./WORKSPACE                                                                                                                                                             0.0s
 => CACHED [ 8/17] COPY ./bazel ./bazel                                                                                                                                                                     0.0s
 => CACHED [ 9/17] COPY ./javascript ./javascript                                                                                                                                                           0.0s
 => CACHED [10/17] COPY ./net ./net                                                                                                                                                                         0.0s
 => CACHED [11/17] COPY ./packages ./packages                                                                                                                                                               0.0s
 => CACHED [12/17] COPY ./src ./src                                                                                                                                                                         0.0s
 => CACHED [13/17] COPY ./test ./test                                                                                                                                                                       0.0s
 => ERROR [14/17] RUN cd ./packages/grpc-web &&   npm install &&   npm run build &&   npm link                                                                                                            356.8s
------
 > [14/17] RUN cd ./packages/grpc-web &&   npm install &&   npm run build &&   npm link:
#18 353.9 added 357 packages from 663 contributors and audited 360 packages in 351.9s
#18 354.0
#18 354.0 7 packages are looking for funding
#18 354.0   run `npm fund` for details
#18 354.0
#18 354.0 found 4 vulnerabilities (2 low, 2 moderate)
#18 354.0   run `npm audit fix` to fix them, or `npm audit` for details
#18 354.3
#18 354.3 > grpc-web@1.2.1 build /github/grpc-web/packages/grpc-web
#18 354.3 > node scripts/build.js
#18 354.3
#18 354.4 /github/grpc-web/packages/grpc-web/node_modules/.bin/google-closure-compiler --js=exports.js --js=../../javascript --js=../../third_party/closure-library --entry_point=grpc.web.Exports --externs=externs.js --dependency_mode=PRUNE --compilation_level=ADVANCED_OPTIMIZATIONS --generate_exports --export_local_property_definitions --js_output_file=index.js
#18 354.6 ../../javascript/net/grpc/web/clientreadablestream.js:29: ERROR - [JSC_UNDEFINED_VARIABLE] variable goog is undeclared
#18 354.6 goog.module('grpc.web.ClientReadableStream');
#18 354.6 ^^^^
#18 354.6
#18 354.6 1 error(s), 0 warning(s)
#18 356.7 npm ERR! code ENOENT
#18 356.7 npm ERR! syscall access
#18 356.7 npm ERR! path /github/grpc-web/packages/grpc-web/node_modules/grpc-web.js
#18 356.7 npm ERR! errno -2
#18 356.7 npm ERR! enoent ENOENT: no such file or directory, access '/github/grpc-web/packages/grpc-web/node_modules/grpc-web.js'
#18 356.7 npm ERR! enoent This is related to npm not being able to find a file.
#18 356.7 npm ERR! enoent
#18 356.7
#18 356.7 npm ERR! A complete log of this run can be found in:
#18 356.7 npm ERR!     /root/.npm/_logs/2021-08-24T12_52_56_022Z-debug.log
------
executor failed running [/bin/sh -c cd ./packages/grpc-web &&   npm install &&   npm run build &&   npm link]: exit code: 254
ERROR: Service 'prereqs' failed to build : Build failed
</pre>
</details>

**Comment by sampajano** [comment]
@dudebing99 @emicklei Thanks for the report.. :)

It is true that there's no `grpcweb/prereqs` images uploaded on [dockerhub](https://hub.docker.com/u/grpcweb).. and the `grpcweb/common` image which `prereqs` is [based upon](https://github.com/grpc/grpc-web/blob/a56e7212a382545c9692e510c0e780928a5b2d4a/net/grpc/gateway/docker/prereqs/Dockerfile#L15) was uploaded about [1 year ago](https://hub.docker.com/r/grpcweb/common), hence the build errors..

---

@dudebing99  In my newer version of docker (20.10.7) and docker-compose (1.29.2) on Mac, it seems like docker no longer reports error when the `prereqs` package is not found, but only prints a warning like what @emicklei sees. And `docker-compose up ...` command in the [quickstart](https://grpc.io/docs/platforms/web/quickstart/) seems to run ok...

---

@emicklei As i mentioned above, the build error you see is probably due to building off of a year-old `grpcweb/common` image..

If you do the following it should be able to build `prereqs` ok..

```
docker rmi grpcweb/common grpcweb/prereqs
docker-compose build common prereqs
```

---

In any case, it's definitely suboptimal to be running/building off of year-old images.. We will update the [quickstart guide](https://grpc.io/docs/platforms/web/quickstart/) and/or docker images soon. :)

**Comment by sampajano** [comment]
Update: We've removed the out-dated `grpcweb/common` image on docker hub for now and updated the documentations so this shouldn't happen anymore. (And we'll probably update the images soon when we cut a new release.)

Let us know if you're still having issues here. Thanks again for the reports! :)

**Comment by emicklei** [comment]
thank you @sampajano , I got the demo working now

**Comment by sampajano** [comment]
Fantastic! Yw! 😃

**Comment by rgkrishnas** [comment]
Hello,
I am getting the error "ERROR: Service 'prereqs' failed to build : Build failed", can somebody help me on this?

>docker version
Client:
 Version:      17.03.1-ce-rc1
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3476dbf
 Built:        Wed Mar 15 20:33:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce-rc1
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3476dbf
 Built:        Wed Mar 15 20:28:18 2017
 OS/Arch:      linux/amd64
 Experimental: true

>docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.9.10
OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021

Error
>docker-compose pull prereqs node-server envoy commonjs-client
Pulling prereqs         ... done
Pulling node-server     ... done
Pulling envoy           ... done
Pulling commonjs-client ... done
WARNING: Some service image(s) must be built from source by running:
    docker-compose build commonjs-client prereqs node-server envoy

>docker-compose up -d node-server envoy commonjs-client
Building prereqs
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'prereqs' failed to build : Build failed
