### ISSUE TITLE
Content-length: 0 confuses grpc-web client 

### ISSUE THREAD

**Issue by wlhee** [grpc/grpc-web#1101]
A gRPC server could send back a gRPC response without any body, for example, a gRPC error response. However, some server could choose not to use "trailers-only" to send back the "grpc-status". Instead, it still uses "headers", "empty body", "trailers" HTTP/2 frames, and the grpc-status and grpc-message are set in the trailers.

There could be scenario when "content-length: 0" is added to the response header as the body is empty. For example, if the gRPC server is fronted by an envoy, the envoy could add "C-L: 0". See https://github.com/envoyproxy/envoy/issues/5554. An example response looks like this:
```
envoy_1   | [2021-06-19 02:40:08.061][15][debug][http] [source/common/http/conn_manager_impl.cc:1472] [C6][S17521888214259471014] encoding headers via codec (end_stream=false):
envoy_1   | ':status', '200'
envoy_1   | 'grpc-accept-encoding', 'identity'
envoy_1   | 'grpc-encoding', 'identity'
envoy_1   | 'content-type', 'application/grpc+proto'
envoy_1   | 'date', 'Sat, 19 Jun 2021 02:40:08 GMT'
envoy_1   | 'server', 'envoy'
envoy_1   | 'x-cloud-trace-context', 'a86f4f6eeee8e5baccd463176c163b05/11003727237429165764'
envoy_1   | 'content-length', '0'
envoy_1   | 'x-envoy-upstream-service-time', '170'
envoy_1   |
envoy_1   | [2021-06-19 02:40:08.062][15][debug][client] [source/common/http/codec_client.cc:130] [C7] response complete
envoy_1   | [2021-06-19 02:40:08.062][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:200] [C7] destroying stream: 0 remaining
envoy_1   | [2021-06-19 02:40:08.062][15][debug][http] [source/common/http/conn_manager_impl.cc:1488] [C6][S17521888214259471014] encoding trailers via codec:
envoy_1   | 'grpc-status', '200'
envoy_1   | 'grpc-message', 'invalid%20input'
```

For this case, as grpc-web filter doesn't strip content-length nor update content length after it encodes the trailers and puts it into the response body. The output from the filter could confuses the grpc-web client and makes it reject the response. 

See a reproduction case in https://github.com/ridedott/grpc-web-cloud-run-issue
And confirm removing content-length header makes the grpc-web client happy: https://github.com/ridedott/grpc-web-cloud-run-issue

**Comment by wlhee** [comment]
For correctness, should grpc-web filter remove C-L or update C-L to the actual size of the body?

**Comment by stanley-cheung** [comment]
@Jennnnny Can you please take a first look at this issue? This comes from an internal bug ( will update the bug number if I find it ). This could be something in the Envoy filter that's outside of this repo though.

**Comment by stefannegrea** [comment]
@stanley-cheung , I posted in https://github.com/grpc/grpc-web/issues/1050#issuecomment-888741174 before seeing this issue. I am experiencing the same problem with the javascript library. Tested with two proxies and have identical results. I would appreciate help with debugging/fixing this.

**Comment by LukeLaScala** [comment]
Hey all. What's the current status on this and are there any workarounds in the time being?

**Comment by efossvold** [comment]
[#1050 (comment)](https://github.com/grpc/grpc-web/issues/1050#issuecomment-970304584) solved it for us.

**Comment by sampajano** [comment]
@RmStorm Thanks for the comment!

I'm closing this bug now based on the comment from @RmStorm and @stefannegrea above (thanks both!!). Please feel free to re-open if the issue remains.

Thanks!
