### ISSUE TITLE
Incorrect TS import type of enum

### ISSUE THREAD

**Issue by EchoZhaoH** [grpc/grpc-web#1105]
type_pb.d.ts
![image](https://user-images.githubusercontent.com/23427655/125578999-dcb3fb79-2e29-42a7-8087-28ad481a4652.png)
import type_pb.ts in doc.d.ts
![image](https://user-images.githubusercontent.com/23427655/125579135-d46b6de8-594a-498c-92b0-3b3e46854094.png)

It's should be `dc_message_type_pb.DCMessageDocAction`

**Comment by calvinkarundu** [comment]
Any update on this? Facing a similar challenge, only affecting enums as well.

**Comment by renkei** [comment]
Looks like a duplicate: #1039
It seems to happen when you don't define a package in your proto file. Fortunately it is already fixed, unfortunately there was no new release for a while that contains the fix.

**Comment by EchoZhaoH** [comment]
ok，I will have a try

**Comment by renkei** [comment]
Should be fixed now with the grpc-web 1.3.0 release
