### ISSUE TITLE
Plugin failed with status code 126 when trying to generate stup files

### ISSUE THREAD

**Issue by Ferror** [grpc/grpc-web#1136]
# Description
Hi, I am trying to generate client/stub files but the `protoc-get` file fails. I checked the permissions and the file is executable, also it is in the $PATH. Do you have some ideas why it might not work? I also use `protoc-gen-php-grpc` plugin and it works seamlessly. This might be MacOS specific because it works fine on ubuntu

# Command
```
protoc --js_out=import_style=commonjs:src --grpc-web_out=import_style=commonjs,mode=grpcwebtext:src contract/*.proto
```
# Environment
* MacOS BigSur 11.5.2
* protoc-gen-grpc-web 1.2.1

# Result
```
/usr/local/bin/protoc-gen-grpc-web: /usr/local/bin/protoc-gen-grpc-web: cannot execute binary file
--grpc-web_out: protoc-gen-grpc-web: **Plugin failed with status code 126**.
```

# Proto
```proto
syntax = "proto3";

package package;

message Nothing {}

message Product {
    string identifier = 1;
    string name = 2;
    string price = 3;
}

message ProductCollection {
    repeated Product product = 1;
}

service ProductService {
    rpc create(Nothing) returns (Product);
    rpc getAll(Nothing) returns (ProductCollection);
}
```

**Comment by sampajano** [comment]
Thanks for the report!

Do you mind trying to run the protoc-gen-grpc-web binary directly to see what happens?

e.g.
```
echo test | protoc-gen-grpc-web
```
(This isn't really a proper input but just trying to see what will happen :))

Thanks!
