### ISSUE TITLE
How to get header value from Streaming.

### ISSUE THREAD

**Issue by singerxt** [grpc/grpc-web#1156]
Hello!

I do have a simple endpoint that streams objects from the database. In headers, I'm sending extra header with information about the total amount of items. The header is called _total_count_

<img width="644" alt="Zrzut ekranu 2021-10-26 o 00 37 59" src="https://user-images.githubusercontent.com/5427444/138780519-46ece321-a8b4-4e2c-9917-3ca370b6e013.png">

I'm seeing the value in the response header in the network debugger. However, I'm unable to get it using your framework.

```typescript
const headers = new grpc.Metadata();
headers.set('authorization', login?.accessToken || '');
const response = client.listDemoObjects(req, headers);
const items: DemoObject.AsObject[] = [];
let totalItems: number;

response.on('status', (status) => {
  console.log(status.code);
  console.log(status.details);
  console.log(status.metadata); // total_count is not here
});

response.on('end', (status) => {
  console.log(status); // total_count is not here
});

response.on('data', (data) => {
  items.push(data.toObject()); // total_count is not here
});
```

How can I get response headers?

To be 100% clear I'm not using trailers. :-)

**Comment by lukasmoellerch** [comment]
As noted [here](https://github.com/grpc/grpc-web/blob/627e33718d5055e3cfb9c8318e81cf1b4045b189/javascript/net/grpc/web/clientreadablestream.js#L57) you should be able to read the response headers in the `"metadata"` event. The `GrpcWebClientReadableStream` implementation directly reads the response headers from the xhr event and will emit the corresponding event.

**Comment by mconrejas** [comment]
Hi @lukasmoellerch why do you think the `"metadata"` doesn't show the other values that were set on the trailers?

This is from the response headers
![Screenshot from 2022-11-21 15-42-05](https://user-images.githubusercontent.com/16751268/202994007-4c2b5b34-97cc-4490-ace7-436c4189e1cc.png)

While this is from the console when I tried to log the `"metadata"`
![Screenshot from 2022-11-21 15-42-52](https://user-images.githubusercontent.com/16751268/202994155-85063de7-192e-406d-8c05-b323c5b6faba.png)

And this is my code
`stream.on('metadata', (metadata) => {
        console.log('metadata', metadata);
      });`

**Comment by lukasmoellerch** [comment]
I'd assume that status and message have special handling. Does it not appear anywhere in the response? Maybe in the status event?

**Comment by mconrejas** [comment]
Already tried to log the status but the `metadata` there doesn't contain anything
![image (2)](https://user-images.githubusercontent.com/16751268/202996457-cb563eab-bb85-4adf-82b3-43f5d09f7ed7.png)

**Comment by lukasmoellerch** [comment]
How about the error event? I am only on mobile right now, can investigate more this evening.

**Comment by mconrejas** [comment]
Same goes for the `error` event, only shows `code`, `details`, and an empty `metadata`.

Could it be because I'm using it on ReactJS + Typescript? Since from our back-end dev's side it does show all values and he's just using plain javascript.
![Screenshot from 2022-11-21 18-38-09](https://user-images.githubusercontent.com/16751268/203029640-bfe765ff-8a61-4710-92c9-995fb4c44a61.png)

**Comment by singerxt** [comment]
Hello!

You have to add an additional header in the envoy server so that grpc lib will be able to use it.
In my case it was

```
expose_headers: grpc-status,grpc-message,total-count
```
