### ISSUE TITLE
run exampels/helloworld error

### ISSUE THREAD

**Issue by kekexilinan** [grpc/grpc-web#1157]
Uncaught TypeError: Cannot read property 'MethodInfo' of undefined
    at Object.<anonymous> (main.js:10)
    at o (main.js:1)
    at Object.<anonymous> (main.js:1)
    at o (main.js:1)
    at main.js:1
    at main.js:1

**Comment by alanhg** [comment]
error again.

![image](https://user-images.githubusercontent.com/9245110/143875099-df1feea4-cb11-4b34-b8c0-00d1c01dd16d.png)

## version

```shell
$ protoc --version
# libprotoc 3.17.3

```

**Comment by sampajano** [comment]
@alanhg please provide more details on the platform/command that you've used. thanks :)

**Comment by sampajano** [comment]
Also closing the issue as the original error is addressed.
