### ISSUE TITLE
legal text script html

### ISSUE THREAD

**Issue by Svuibes6** [grpc/grpc-web#1163]
https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwiJ68Pvtof0AhXADK0GHQPuC2EYABAAGgJwdg&ae=2&ohost=www.google.com&cid=CAESQeD2XktZHy52SARQfWMcfc6MsZimoS9EVmVdoFUPWCckI-x4dSxDbaLyEBO_l9tA69GMZFV5IbOaZGVgJHk8ehS4&sig=AOD64_2S1pMCFAqnUHEBnZZZzadifwwASA&q&adurl&ved=2ahUKEwiozLnvtof0AhVlHzQIHdRmAvIQ0Qx6BAgDEAE

**Comment by sampajano** [comment]
(Please don't link to unknown sources in bug reports.)
