### ISSUE TITLE
node-client.js is redundant？

### ISSUE THREAD

**Issue by alanhg** [grpc/grpc-web#1177]
https://github.com/grpc/grpc-web/blob/69a16b603359334884a04927572cc96de36f80bf/net/grpc/gateway/examples/helloworld/node-client.js#L26

1. I found no usage about node-client.js.
2. What is the purpose of this file and how to use it?

![image](https://user-images.githubusercontent.com/9245110/147046861-514d04d0-cd0d-4595-a830-a479868b012d.png)

**Comment by sampajano** [comment]
Thanks for noticing :)

You're right it's not referred anywhere in the exmaples.

Although, maybe that was used to showcase how grpc-web can be used from a node runtime?

I'm not sure if it works anymore tho :)

**Comment by jasonclg** [comment]
I had the same question. Please consider adding some notes about node-client.js in README (or remove the file?).
Thanks :)

**Comment by sampajano** [comment]
Checked with team, actually node-client.js is used to test against the node grpc server (without Envoy proxy) just in case things aren't working.. so it doesn't actually speak grpc-web! Will add note to clarify. Thanks for noticing and the suggestions! :)
