### ISSUE TITLE
Max Message Size

### ISSUE THREAD

**Issue by RohinBhargava** [grpc/grpc-web#1182]
Can someone explain the max message size of a single request. It appears to be around 4 MB as per grpc specification. Can this limit be increased? Is there a configuration in either the grpc-web client that can be set or on the proxy (I am using envoy)? Thanks in advance.

**Comment by RohinBhargava** [comment]
Thanks! Appreciate the response. Feel free to close the issue.

**Comment by kyungseopk1m** [comment]
I wrote it like this
`const server = new Server(
  {
    'grpc.max_receive_message_length': 1024 * 1024 * 100,
    'grpc.max_send_message_length': 1024 * 1024 * 100,
  }
);`
Grpc can attach up to 100MB to a single message.
