### ISSUE TITLE
--js_out=import_style=commonjs doesn't export the messages from _pb.js files

### ISSUE THREAD

**Issue by chris-kruining** [grpc/grpc-web#1186]
the _pb.js files generated with the commonjs import style do not define `module.exports`. how can I import my message classes in my code so I can construct a request message for example?

currently I have this "build path":

CI of repo Library.Proto generates the stubs for web and c# and commits these to the respective repo
CI of repo Library.Proto.Typescript builds the received typesctript files and bundles it all into a lib.
npm install that-lib
import the message class into business logic

**Comment by sampajano** [comment]
Thanks for the question!

You're right that the _pb.js file doesn't directly contain `module.exports` statements.. Although, they contain some`goog.exportSymbol(...)` statements which i believe will export the message classes into module space too.

See our common-js [code examples](https://github.com/grpc/grpc-web/blob/3fcc2a2a8a041074884ce452554662dbbe2951fb/net/grpc/gateway/examples/echo/commonjs-example/client.js#L19-L20) on how import statements looks like, and the related [Dockerfile](https://github.com/grpc/grpc-web/blob/3fcc2a2a8a041074884ce452554662dbbe2951fb/net/grpc/gateway/docker/commonjs_client/Dockerfile#L19-L29) on how the code is generated and bundled (using webpack).

Lemme know if you still have issues after seeing the examples! Thanks! :)

**Comment by chris-kruining** [comment]
I fixed the issue with custom plugin that just generates typescript for me. so this is no longer relevant for me. Still, thank you for answering 😊

**Comment by sampajano** [comment]
Of course! Glad it works for you now! Thank you for letting us know! :)
