### ISSUE TITLE
getMethodDescriptor(...).createUnaryResponse is not a function

### ISSUE THREAD

**Issue by eyouyou** [grpc/grpc-web#1215]
Hi there,

I try to construct a  UnaryResponse in Interceptor but failed
### Code:

    class InterceptorTest 
    {

        intercept(request: any, invoker: any) {
            return Promise.resolve( request.getMethodDescriptor().createUnaryResponse(new GeneralReply()));
        }
    
    }

or how to create response 

thanks

### Version:
grpc-web: 1.3.1

**Comment by sampajano** [comment]
Please refer to interceptor documentations on how it can be used:

- Code: https://github.com/grpc/grpc-web/blob/7fe18d1e088c650002209141cfaaad96cc8949b6/javascript/net/grpc/web/interceptor.js#L21-L33

- Blog: https://grpc.io/blog/grpc-web-interceptor/

Thanks :)
