### ISSUE TITLE
web client streaming support

### ISSUE THREAD

**Issue by Lu-Gru** [grpc/grpc-web#1232]
Hello,
Question regarding current streaming status.

From testing it seams to me that streaming is only supported from server side (tested c++ server and did received messages fine in JS client). 

Unfortunately I'm unable to find concrete answer regarding streaming support from client to server and bi-directional streaming. 

Generated stubs for client side (service and channel) seams to be missing streaming part.

So my question is can JS client stream to server (and use bi-directional streaming) ?

**Comment by sampajano** [comment]
Hi! Thanks for the question!

you're right.. unfortunately both client->server streaming and bidi-streaming are NOT supported currently. :)

It might come in the future but no plans so far. 😃

**Comment by Lu-Gru** [comment]
Thank You for the answer.

**Comment by KiyonamiYu** [comment]
I think this issue should be explained in the README.md.
I tried it for a long time 😂

**Comment by sampajano** [comment]
@KiyonamiYu thanks for the suggestion.. it makes sense to me. Added above. Thanks! :)
