### ISSUE TITLE
Essential documentation for javascript is gone/missing

### ISSUE THREAD

**Issue by ben-xD** [grpc/grpc-web#1241]
There was a documentation site containing essential guides on how to use protocol buffers in Javascript. The page was previously available on https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#any=

You can see this guide on Wayback Machine: https://web.archive.org/web/20200928202524/https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#any=

**Now the essential documentation is missing**. I've attached a PDF version of the website on this github issue. 

![missing](https://user-images.githubusercontent.com/24711048/167876201-026c94c6-1ff0-4c97-b7ea-efaf9d0dbff4.png)

[JavaScript Generated Code | Protocol Buffers | Google Developers.pdf](https://github.com/grpc/grpc-web/files/8670804/JavaScript.Generated.Code.Protocol.Buffers.Google.Developers.pdf)

## Help
Could someone investigate why the documentation is missing and fix it? 😢

**Comment by sampajano** [comment]
Thanks!!

I'm guessing maybe it could be related to this? 😃
https://github.com/protocolbuffers/protobuf/pull/9874

@acozzette Hey Adam I'm wondering if you know anything about this? Thanks! :)

**Comment by sampajano** [comment]
Update: There is a plan to re-host the documentation under the new github repo:
https://github.com/protocolbuffers/protobuf-javascript

Thanks for the patience! 😃

CC @lukesandberg

**Comment by sampajano** [comment]
FYI a related issue with `protoc` support is at: https://github.com/grpc/grpc-web/issues/1251 :)

**Comment by sampajano** [comment]
Docs are now re-hosted here:
https://github.com/protocolbuffers/protobuf-javascript/blob/main/docs/index.md

Hope it works for everyone now!

Thanks for the patience! :)
