### ISSUE TITLE
Server-side streaming has buffering behavior

### ISSUE THREAD

**Issue by jasonclg** [grpc/grpc-web#1245]
I'm curious if the buffering behavior of [server](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/helloworld/server.js#L48) is expected?
**doSayRepeatHello** waits and sends back 5 messages at once right after call.end() was executed (buffering).
What I expected was each message being written to stream and sent back immediately at 500ms interval but it's apparently not the case.

BTW, is it possible to send back messages without executing call.end()?

**Comment by sampajano** [comment]
Hi!

Curious if you're using `mode=grpcwebtext` or `mode=grpcweb`? Streaming is only supported for the former so if you use the latter it may seems like that response is buffered.

**Comment by jasonclg** [comment]
I'm using grpcwebtext mode.
Besides helloworld, I tested [Echo](https://github.com/grpc/grpc-web#advanced-demo-browser-echo-app) too.
Response is also buffered.

**Comment by sampajano** [comment]
Ahh. then it's not expected.. streaming response should arrive as they're sent.

**Comment by jasonclg** [comment]
My network tab on testing [Echo](https://github.com/grpc/grpc-web#advanced-demo-browser-echo-app)
Two requests were sent when I typed "4 hello".
![1](https://user-images.githubusercontent.com/2009930/169599376-be5b78ca-d01d-42f2-b161-098d7fc159bb.png)
![2](https://user-images.githubusercontent.com/2009930/169599387-b100330b-47b1-48ca-82aa-f0dd70f6751b.png)

**Comment by sampajano** [comment]
Ah ok that's a bit weird..

I tried locally with the echo example and streaming works and here's what i saw in my chrome tab:

<img width="1731" alt="Screen Shot 2022-05-24 at 3 36 34 PM" src="https://user-images.githubusercontent.com/133680/170143247-348b672d-a4b5-4716-a8d4-198f9af51c8e.png">

The difference is that there's minimal "Waiting" in my case..

Not quite sure what the difference is..

**Comment by jasonclg** [comment]
@sampajano really appreciate your time on this!
Closing this issue as I found the firewall/antivirus were the cause.

**Comment by sampajano** [comment]
Oh i see! Thanks so much for letting us know that firewall/antivirus was the cause! I had that initial hunch too but forgot to mention it.. 😃 Glad it works now :)
