### ISSUE TITLE
GRPC example Hello World getting error calling envoy

### ISSUE THREAD

**Issue by Skebard** [grpc/grpc-web#1270]
I have cloned the repo and I wanted to try the example. It seems that due to the version of npm I can not execut `npx webpack ` and therefore I have decided to use BloomRPC as client.

When calling the service directly at localhost:9090 it works:

![image](https://user-images.githubusercontent.com/49041487/188183391-96f8592b-5e7f-4022-9b88-c1f49551ea41.png)

But when trying to call through the envoy proxy at  http://localhost:8080 I get the following error:

`{
  "error": "full url: http://localhost:8080/helloworld.Greeter/SayHello, code: 14, err: Http response at 400 or 500 level"
}`

![image](https://user-images.githubusercontent.com/49041487/188182975-17794bc8-36a6-449d-89b0-c3607b111fc0.png)

Any idea of what is happening?

**Comment by sampajano** [comment]
hi.

i'm not familiar with BloomRPC but i suspect it's not using grpc-web protocol?

grpc-web speaks a different protocol (based on http/1.1 over Envoy) than grpc (based on http/2), and hence maybe the difference what you're seeing?

**Comment by maja42** [comment]
Bloom has a toggle-button in the upper right corner to switch between grpc and grpc-web.
You need to select grpc-web when talking via envoy.

**Comment by sampajano** [comment]
Hi :) I'm closing this because it's likely unrelated to the grpc-web library in specific.

Feel free to re-open or start another https://github.com/grpc/grpc-web/discussions if needed. Thanks! :)
