### ISSUE TITLE
grpc 中 request  和 request.toObject() 返回的数据不一致 导致存储的数据也不一致

### ISSUE THREAD

**Issue by VaneBoy** [grpc/grpc-web#1272]
request 返回
![a14fbd3884d0b7247b51b1baea7ff6e](https://user-images.githubusercontent.com/26101551/188416337-fcabcd38-0e23-4af0-8389-38358fc0c25f.png)

request.toObject()
![8a41c2d10042d0a73b201d02f80a879](https://user-images.githubusercontent.com/26101551/188416464-c5e81bee-cbb1-4f80-a575-2ded4ef123b7.png)

求解

**Comment by sampajano** [comment]
Hi :) I'm closing this issue because not sufficient details was provided.

It looks like an encoding issue, but it would be difficult to understand without more details.

If you could, please help setup a demo showcasing this issue (e.g. on github) and re-open this issue.

Thanks! 😃
