### ISSUE TITLE
Missing metadata trailer values on ReactJS + Typescript

### ISSUE THREAD

**Issue by mconrejas** [grpc/grpc-web#1304]
Can anyone please enlighten me why this code:

```
const metadata = {
  authorization: "Bearer ${jwtToken}`,
  "grpc-metadata-loginkey": `${loginKey}`
};

const req = new StockRequest();

req.setTicker(`${symbol}-${exchangeCode}`);

let stream;

stream = client.getPriceTicks(req, metadata);

stream.on('metadata', function (metadata) {
  console.log('metadata', metadata);
});
```

Is only showing this:
![Screenshot from 2022-11-21 15-42-52](https://user-images.githubusercontent.com/16751268/203438379-6099477f-7ebd-421a-b902-2bf26e7ca018.png)

when the stream returns a `401` on a ReactJS + Typescript project?

While it's showing this:
![Screenshot from 2022-11-21 18-38-09](https://user-images.githubusercontent.com/16751268/203438642-babc931f-9909-4cba-83d9-51437bb28003.png)

on a pure javascript project using the same set of codes.

My goal here is to show a custom error message included on the `metadata` trailers when the stream returns a `401`.

**Comment by sampajano** [comment]
Hi,

Could you clarify on what metadata you're expecting and why?

From the error, it seems like your got a 401 error with a detailed error-message indicating a login error. Would it be sufficient for your to proceed?

thanks :)

**Comment by sampajano** [comment]
Hi. I'm closing for now but feel free to reopen with more details. thanks!
