### ISSUE TITLE
XDS/Proxyless support?

### ISSUE THREAD

**Issue by akettmann-e24** [grpc/grpc-web#1317]
We are using grpc-web for a SPWA. Is proxyless/xds protocol supported ? If so is there documentation I have missed regarding it?

**Comment by sampajano** [comment]
Hi thanks for asking! I'm not familiar with proxyless/xds but as i understand gRPC-Web is designed for browsers so it is HTTP only.

**Comment by akettmann-e24** [comment]
Thanks for the info! XDS/proxyless (well the proxy is built into GRPC basically) gets rid of Envoy sidecars, and has your clients figure out the best endpoint themselves. XDS:/// is sidestepping normal DNS to allow it to figure out who you should ask.

**Comment by sampajano** [comment]
@akettmann-e24 Aha i see! Thanks a lot for the explanation! 😃
