### ISSUE TITLE
CORS spec and `Access-Control-Expose-Headers`

### ISSUE THREAD

**Issue by fracek** [grpc/grpc-web#1319]
I'm updating apisix's grpc-web plugin to follow the spec more closely and I noticed that [the spec doesn't explicitly mention `Access-Control-Expose-Headers`](https://github.com/grpc/grpc-web/blob/master/doc/browser-features.md#cors-support). 

Setting `Access-Control-Expose-Headers` to include `grpc-status,grpc-message` is required to have a working grcp-web setup so I believe the spec should be updated to reflect that.

What's your thoughts about this?

**Comment by sampajano** [comment]
@fracek Thanks so much for pointing it out! Good point! Will add it thanks!
