### ISSUE TITLE
UnaryInterceptor is not being called

### ISSUE THREAD

**Issue by usertest123test** [grpc/grpc-web#1342]
In My reactjs web app I am trying to use interceptors on grpc but the interceptor is not being called.

I tried some of the solutions provided around but could get it resolved. please someone assist me on this.

project details:
Package:
 "react": "^18.2.0",
 "grpc-web": "^1.3.1",

Below is my code:
Interceptor:

```
export const SimpleUnaryInterceptor = function () {};
SimpleUnaryInterceptor.prototype.intercept = function (request: any, invoker: any) {
  console.log("[Intercepting request]");
  return invoker(request).then((response: any) => {
    console.log("[Intercepting response]");
    return response;
  });
};
```

Biding interceptor:
```
export default class Api {
  myServicePromiseClient: MyServicePromiseClient;
  metadata: Metadata;

  constructor(public serviceURL: string) {
    this.myServicePromiseClient = new MyServicePromiseClient(serviceURL, null, { unaryInterceptors: [SimpleUnaryInterceptor] });
  }

  public user = new (class {
    constructor(public superThis: Api) {}
    public getMyUser = async (userId: string): Promise<UserObj> =>
      getMyUser( userId, this.superThis.myServicePromiseClient, this.superThis.metadata);
  })(this);
}
```

MyServicePromiseClient:
```
export class MyServicePromiseClient {
  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; });
```

and getMyUser grpc method is:

 ```
 getMyUser(
    request: user_pb.GetMyUserRequest,
    metadata?: grpcWeb.Metadata
  ): Promise<user_pb.MyUserResponse>;
```

Calling grpc-api:

`const response  = await new Api(MyServerUrl).user.getMyUser(123)`

**Comment by Ram-naik-zebra** [comment]
Any help on this ?

**Comment by usertest123test** [comment]
Any help on this ?

**Comment by sampajano** [comment]
Hi! Thanks for the report :)

Without debugging your code, i'm thinking you probably need to instantiate your interceptor, like:

```ts
{ unaryInterceptors: [new SimpleUnaryInterceptor()] })
```

instead of:

```ts
{ unaryInterceptors: [SimpleUnaryInterceptor] })
```

which you currently have.

Please let me know if this works for you. thanks!

**Comment by usertest123test** [comment]
@sampajano Thank you for the reply.
Since here interceptor is a function so cannot use new keyword for it but I had tried this and didn't work had also tried something like this, that also didn't help
{ unaryInterceptors: [SimpleUnaryInterceptor()] })

Even I am wondering something wrong in the initialization but not able to figure it out.

**Comment by sampajano** [comment]
aha ok!

Can you try writing your interceptor following this format?

https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/test/tsc-tests/client04.ts

It might help rule out a few variables.

Thanks!

**Comment by Ram-naik-zebra** [comment]
@sampajano I really appreciate your help,
I tried this with my code but that didn't work and when I tried your exact code it worked.
So it means when I try creating a EchoServicePromiseClient on fly with  dynamic hostname its not working.

I mean:
`const echoService = new EchoServicePromiseClient('http://localhost:8080', null, opts);` 
=> this is  working

but I need to create EchoServicePromiseClient with dynamicURL url passed in
` new EchoServicePromiseClient(**dynamicURL**, null, opts);``
=> this is not working

**Comment by usertest123test** [comment]
@sampajano I really appreciate your help.
I tried this with my code but that didn't work and when I tried your exact code it worked.
So it means when I try creating a EchoServicePromiseClient on fly with dynamic hostname its not working.

I mean:
const echoService = new EchoServicePromiseClient('http://localhost:8080', null, opts);
=> this is working

but I need to create EchoServicePromiseClient with dynamicURL url passed in
` new EchoServicePromiseClient(dynamicURL, null, opts);``
=> this is not working

**Comment by sampajano** [comment]
oh wow very interesting! you're very welcome! glad to hear at least the sample code worked! 😃 

> So it means when I try creating a EchoServicePromiseClient on fly with dynamic hostname its not working.

I wonder if it has something to do with how your javascript ["closure"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures) works? In that maybe you're not properly capturing the string in your lambda functions?

Could you try putting a `console.log` right before this line:

```
new EchoServicePromiseClient(dynamicURL, null, opts);
```

And see if it's indeed the right URL?

**Comment by usertest123test** [comment]
Hi @sampajano 
In console I could see same url is being passed in all the time.

Debugged more and able to isolate this issue a little more:
Issue is not about being passed in dynamic url, its about nested classes.

When I try your approach with direct class it is working as expected but when I try any solutions with nested class its not working.

To illustrate more:
**Step1:**
Creating a main class `export default class Api {` 
**Step2:**
generating myServicePromiseClient through a constructor 
**Step3:**
Also added another class inside **API** class as below
 **public user = new (class {
 })(this)**
( the whole idea to have this nested class is to have multiple properties in the **API** class and utilize them in the multiple child classes so we can avoid duplicate code in all child classes)
**Step4:**
Now when consumers try to access methods from **user** class, it gets all properties from the parent class(API-Class)
Ex: `await new Api(MyServerUrl).user.getMyUser(123)`
Now in this case in getMyUser method **this.superThis.myServicePromiseClient** has a uneryInterceptor properties but somehow that is not calling the intercept method. I have also attached a screenshot for this, please take a look.


![image](https://github.com/grpc/grpc-web/assets/137183415/c4016ff4-fc0d-458c-94d7-d297dcb0c034)

**Comment by sampajano** [comment]
Oh wow nice investigation!!

I'm sorry that it's an issue for you. i hope that gets resolved soon! (Or you can temporarily disable the plugin when needed.. :))

I'll close this issue now as it's not related to our specific implementation. Please keep us updated if there's anything new from your/their side.

Thanks! :)

**Comment by usertest123test** [comment]
Thank you @sampajano for your valuable suggestions. :-) 
Will update once I receive any update on this.

**Comment by sampajano** [comment]
> Thank you @sampajano for your valuable suggestions. :-) Will update once I receive any update on this.

You're very welcome! 😊 

And thank you that would be much appreciated! 😃
