### ISSUE TITLE
request.serializeBinary is not a function

### ISSUE THREAD

**Issue by Muzzamil75** [grpc/grpc-web#1347]
Encountering this issue in 2023
Am having latest **24.0-rc2** protoc version.
Why its happening in my react app. Is there any step am missing I have not configured any proxy, just made the client code with proto file.

**Comment by sampajano** [comment]
@Muzzamil75 Hi! Thanks for the report!

Could you try to follow the Hello world example and see if it works for you?
https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld

If that works, you could also try to build and run the TS echo example here:
https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo/ts-example

If you could compare your code against these examples, you should be able to find out what's missing.

Hope it helps!
