### ISSUE TITLE
How do you use Nginx with GRPC WEB

### ISSUE THREAD

**Issue by Nedimko123** [grpc/grpc-web#1372]
After some configuration I get 
`Paused on exception
RpcError: missing trailers`

But I do get the data back, though...

**Comment by sampajano** [comment]
@Nedimko123 Thanks for the feedback. :)

Nginx support is not part of grpc-web's core feature, and would be better supported by the larger community.

I'll convert this into a discussion in case anyone could help with it.

Thanks! :)
