### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by EByrdS** [grpc/grpc-web#1377]
The latest release available is 1.4.2 from October 2022, there have been many bug fixes since. The one of my interest is https://github.com/grpc/grpc-web/issues/1328.

Can someone create a new minor release that includes that fix? It would be greatly helpful. Otherwise, is there a roadmap for the next release?

I can contribute if needed.

Thanks

**Comment by EByrdS** [comment]
https://github.com/grpc/grpc-web/issues/951

**Comment by sampajano** [comment]
Thanks for the ping.. Indeed there's several updates since.. I'll cut a new release soon! Thanks! :)

**Comment by sampajano** [comment]
FYI - A new release 1.5.0 was recently cut ([here](https://github.com/grpc/grpc-web/releases)). Thanks for the patience. :)
