### ISSUE TITLE
hello world example,frontend visit backend,net::ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by xuleixie** [grpc/grpc-web#1378]
![image](https://github.com/grpc/grpc-web/assets/26809087/704adb1d-132b-4ed3-916f-5a60fbb38047)

**Comment by sampajano** [comment]
Thanks for reaching out :)

Do you mean check the HTTP response code and error message in your networking tab? It should help in identifying what's going wrong.

Also, for a preexisting demo, you can run:

```docker-compose up --build node-server envoy commonjs-client```

And check if that's working out for you. (And note the difference from that with your setup.)

**Comment by sampajano** [comment]
Closing for now due to inactivity. Feel free to reopen later with more details. Thanks! :)
