### ISSUE TITLE
VSCode intellisense hinting not working in example project

### ISSUE THREAD

**Issue by ratwizzard** [grpc/grpc-web#1380]
When I open up the `helloworld` example in my IDE (vscode) and I edit `client.js` for some reason I am not seeing any code hints, e.g when I delete the `streamRequest.setCount(5);` line and I start typing `streamRequest.` I cannot see the `setCount` method in the list of options: 

![image](https://github.com/grpc/grpc-web/assets/1326786/7fe97a96-828a-49c3-bc99-58b11e8b2080)

Is there some way this can be enabled?

**Comment by sampajano** [comment]
@ratwizzard Hi :)

I think editor hint would only work after you've generated the API stubs following this step:
https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld#generate-protobuf-messages-and-client-service-stub

I wonder if that's something you've already done?

**Comment by sampajano** [comment]
Closing for now. Feel free to reopen if you still have questions :)
