### ISSUE TITLE
hello world example,503 service unavailable

### ISSUE THREAD

**Issue by xuleixie** [grpc/grpc-web#1383]
![image](https://github.com/grpc/grpc-web/assets/26809087/91eb8bfa-9cf5-4b58-af2f-b3760418ec15)

**Comment by sampajano** [comment]
Hi!

503 Error seems to indicate that there's some mis-configuration on the backend, hence making it not available.

Could you try the following Echo example and see if it works for you?
https://github.com/grpc/grpc-web#advanced-demo-browser-echo-app

And if it does, you can try compare what you're doing differently from the echo app, to understand what's wrong.

**Comment by xuleixie** [comment]
thank you,echo example running success！

**Comment by xuleixie** [comment]
thank you very much!
![image](https://github.com/grpc/grpc-web/assets/26809087/36183c31-8b57-4fd5-9c32-7b870d48d74a)

**Comment by sampajano** [comment]
Aha ok! good to hear!

In that case, you can try comparing your Envoy config with what's used in the echo example, showed below:

https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/envoy/Dockerfile
https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml

If nothing stands out, you can check the node server config below:

https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/node_server/Dockerfile
https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/node-server/server.js

Most likely, you'd have mis-configured one of the above in the hello world example, hence it wasn't working.

**Comment by sampajano** [comment]
Closing for now. Feel free to reopen if you still have issues :)
