### ISSUE TITLE
mode=grpcweb support server streaming in http2 actually

### ISSUE THREAD

**Issue by jmzwcn** [grpc/grpc-web#1391]
mode=grpcwebtext: The default generated code sends the payload in the grpc-web-text format.

Content-type: application/grpc-web-text
Payload are base64-encoded.
Both unary and server streaming calls are supported.
mode=grpcweb: A binary protobuf format is also supported.

Content-type: application/grpc-web+proto
Payload are in the binary protobuf format.
**Only unary calls are supported for now. ==> Both unary and server streaming calls are supported.**

**Comment by sampajano** [comment]
Thanks so much for the info!!

See https://github.com/grpc/grpc-web/discussions/1322#discussioncomment-7804499

I'd like to have one more confirmation here before i update our docs! 😃

**Comment by jmzwcn** [comment]
furthermore, I find: based on grpc-web, we could directly send pb msg to grpc-server without any proxy.

https://github.com/emart-io/cross/blob/main/zwan/internal/cmd/main.go#L49

**Comment by sampajano** [comment]
> Furthermore, I find based on grpc-web, we could directly send pb msg to grpc-server without any proxy.
> 
> https://github.com/emart-io/cross/blob/main/zwan/internal/cmd/main.go#L49

@jmzwcn Aha interesting! Good to note!! I guess grpc-server would have recently added grpc-web support..?

**Comment by jmzwcn** [comment]
No, if server stream is always sending without stop,  grpc-web client will don't fetch those stream.
