### ISSUE TITLE
Status of streaming with the binary wire format

### ISSUE THREAD

**Issue by dimo414** [grpc/grpc-web#1396]
The readme section for `mode=grpcweb` notes that "Only unary calls are supported for now". This line [dates back to 2018](https://github.com/grpc/grpc-web/pull/251). Is this still correct? Are there any plans to resolve this wire format incompatibility?

**Comment by sampajano** [comment]
Yeah i believe this is still true. And unfortunately no, nothing is planned around improving streaming support in binary mode.. :)

**Comment by sampajano** [comment]
I'll close this issue for now. Please feel free to open another feature request issue if there's a good reason why it would be beneficial to add this support. thanks! :)

**Comment by dimo414** [comment]
Is the expectation then that we should just always use the text format? It's a really surprising limitation of the binary format that it lacks features the text format supports.

At a minimum it would be helpful to remove the "for now" if there are not actually any plans to resolve this discrepancy.

**Comment by sampajano** [comment]
> Is the expectation then that we should just always use the text format? It's a really surprising limitation of the binary format that it lacks features the text format supports.

For streaming i guess so. I was not involved in the earlier design/implementations, but afaiu there's some limitations with how messages are encoded/decoded which makes streaming decode not feasible when binary format is used..

> At a minimum it would be helpful to remove the "for now" if there are not actually any plans to resolve this discrepancy.

That's quite fair! Let me remove that "for now" text then! :)
