### ISSUE TITLE
Roadmap.md needs updating

### ISSUE THREAD

**Issue by gilperopiola** [grpc/grpc-web#1401]
[Streaming roadmap.md](https://github.com/grpc/grpc-web/blob/master/doc/streaming-roadmap.md
)

- Fetch cancellation support - **2023**
- Finalizing keep-alive support (via Envoy) - **2023+**
- Performance improvements and whatwg Fetch/streams support, including service workers - **2023+**
- Addressing runtime behavior gaps between Fetch and XHR - **2023+**
- Full-duplex (bi-directional) streaming. **Planned for 2023+.**

**Comment by sampajano** [comment]
Thanks for the reminder. It indeed needs to be updated.. Some bigger changes are coming soon :)

BTW, i've modified the language used in the OP, as per https://github.com/grpc/grpc-web/blob/master/CODE-OF-CONDUCT.md.  Please use respectful language next time. :)

**Comment by nguyensonghao94** [comment]
@gilperopiola, regarding Full-duplex (bi-directional) streaming, do you have a detailed plan for this feature? We are looking forward to this feature.

**Comment by gilperopiola** [comment]
@nguyensonghao94 not really, I'm not an expert on this just a dude who was high at 3am and ended up on that readme xd

**Comment by sampajano** [comment]
> @gilperopiola, regarding Full-duplex (bi-directional) streaming, do you have a detailed plan for this feature? We are looking forward to this feature.

@nguyensonghao94 Hi. We don't have a detailed plan yet. But experimentation should start this year (following our Typescript migration).
