### ISSUE TITLE
Are there any plans to simplify the request

### ISSUE THREAD

**Issue by sunny1d** [grpc/grpc-web#1402]
Now I create a new request that looks like this：
```
   let request = new xxx.Request();
    request.setName('name');
    request.setAge(12);
```
I want to implement the request like this：

```
  let request = new xxx.Request({
      name:'name'，
      age:12
  });
```

**Comment by sampajano** [comment]
Hi! So basically what we currently have is part of the JS protobuf API, and it's not likely to change for the lifespan of the project.

Although, we are actually looking into alternative "protobuf" solutions overall, so when that happens i think something like you proposed could be possible :)

**Comment by sampajano** [comment]
Closing for now. Feel free to re-open and follow up later if there are more updates. Thanks!
