### ISSUE TITLE
 Why optional message types compile inconsistently?

### ISSUE THREAD

**Issue by sunny1d** [grpc/grpc-web#1413]
Given a proto file like
```
syntax = "proto3";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service ProjectService {
  rpc UpdateProject(Project.Request) returns (google.protobuf.Empty);
}

message Project {
  message Request {
    string id = 1;
    google.protobuf.Timestamp update_time = 2;
    optional bool has_right = 3;
    optional string content = 4;
    optional uint32 percent = 5;
  };
}
```
Running the generator with options --js_out=import_style=commonjs,binary:. --grpc-web_out=import_style=typescript,mode=grpcwebtext:.
in the generated _pb.d.ts file ,The parameters of **setUpdateTime** are optional that are not the same as the others **setXXX** .
Why are other fields compiled with parameters that are required?

```
 //  _pb.d.ts file
  export class Request extends jspb.Message {
    getId(): string;
    setId(value: string): Request;

    getUpdateTime(): google_protobuf_timestamp_pb.Timestamp | undefined;
    setUpdateTime(value?: google_protobuf_timestamp_pb.Timestamp): Request; // value is optional
    hasUpdateTime(): boolean;
    clearUpdateTime(): Request;

    getHasRight(): boolean;
    setHasRight(value: boolean): Request;  // value is required

    getContent(): string;
    setContent(value: string): Request;   // value is required
    hasContent(): boolean;
    clearContent(): Request;

    getPercent(): number;
    setPercent(value: number): Request;   // value is required
    hasPercent(): boolean;
    clearPercent(): Request;

  }
```

**Comment by sampajano** [comment]
Hi!

I think the difference is that "google.protobuf.Timestamp" is a message type so that it would be possible to set an "empty" message, but it's not the same for primitive types.

See:
https://github.com/protocolbuffers/protobuf-javascript/blob/main/docs/index.md#singular-message-fields

 Hope that makes sense!

**Comment by sunny1d** [comment]
Got it! Many thanks.  @sampajano 
I have another question I'd like help with.
I need to update some fields of message.
```
message Project {
  message Request {
    string id = 1;
    optional bool has_right = 3;
    optional string content = 4;
    optional uint32 percent = 5;
  };
}
```
I have a number of requests where the fields to be updated are randomised for each request. For example, first request is to update the content field, second request is to update the content field and percent field. 

How do I make it happen? Is the  FieldMask  the only way?

**Comment by sunny1d** [comment]
Got it! Many thanks.  @sampajano 
I have another question I'd like help with.
What's the best way to update some of the fields in a message?
```
message Project {
  message Request {
    string id = 1;
    optional bool has_right = 3;
    optional string content = 4;
    optional uint32 percent = 5;
  };
}
```
Situation:  request only submits fields changed. I set ‘request.setXXX(**ChangeValue**)‘ for the changed field. If  **ChangeValue** of a change field is empty string or null, then the change field will not be updated.

How to ensure that all changes are updated？ Can FieldMask do it?

**Comment by sampajano** [comment]
@sunny1d You're welcome! Glad it helped! :)

> I have another question and need help.

> The requirement I encountered was to submit only the values of fields whose values had changed.

> For example (based on the proto file above)：
> The "content" value and "percent" value have changed, and the values of the remaining fields remain unchanged. At this time, only the changed fields "content", "percent", are submitted.

This is more of a protobuf question, but i think since all these fields are already optional, you have 2 options:

1. Call [`clone()`](https://github.com/protocolbuffers/protobuf-javascript/blob/main/docs/index.md#messages) on the original proto and make corresponding changes, then send the full updated proto to server.

2. Optionally set only the fields of the proto which needs update (essentially using this proto as a "diff"), and on server side for each field check if the field is set, and process accordingly.

Hope that helps :)

**Comment by sunny1d** [comment]
@sampajano I'm confused.

> 1. Call [`clone()`](https://github.com/protocolbuffers/protobuf-javascript/blob/main/docs/index.md#messages) on the original proto and make corresponding changes, then send the full updated proto to server.

I don't understand. Do you have more details?

> 2. Optionally set only the fields of the proto which needs update (essentially using this proto as a "diff"), and on server side for each field check if the field is set, and process accordingly.
> 
How to Modify Fields to Default Values.  According to the protobuf  [Default Values](https://protobuf.dev/programming-guides/proto3/#default) ，once a message is parsed there’s no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all

**Comment by sampajano** [comment]
> @sampajano I'm confused.

@sunny1d no problem! I misunderstood about your original comment, so the first option i gave probably is irrelevant (it's about first cloning the entire proto then modifying necessary fields).

> > 1. Call [`clone()`](https://github.com/protocolbuffers/protobuf-javascript/blob/main/docs/index.md#messages) on the original proto and make corresponding changes, then send the full updated proto to server.
> 
> I don't understand. Do you have more details?
> 
> > 2. Optionally set only the fields of the proto which needs update (essentially using this proto as a "diff"), and on server side for each field check if the field is set, and process accordingly.
> 
> How to Modify Fields to Default Values. According to the protobuf [Default Values](https://protobuf.dev/programming-guides/proto3/#default) ，once a message is parsed there’s no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all

Ah that's a good point..

From my understanding, there isn't a way to distinguish between a default value (e.g. `0`), with an explicitly set `0`.

So if that's what you need, you could maybe use a [oneof](https://protobuf.dev/programming-guides/proto3/#oneof) to achieve that.

Or, maybe never allow a value to be "updated" to the defaults in protobuf (but rather if you need to unset it you can set it to `-1` or something). Not sure if that makes sense to you.. :)
