### ISSUE TITLE
Getting `Property 'proto' doesn't exist` every time running 

### ISSUE THREAD

**Issue by rizdaputra** [grpc/grpc-web#1458]
The error i get after generating and running the app using the generated file is  `Property 'proto' doesn't exist` i use the typescript format for the auto generated and the error comes from the js file. Any help would be appreciated
![image](https://github.com/user-attachments/assets/1ecb96a1-0aa0-4b30-a1ad-9279fb263724)

**Comment by sampajano** [comment]
@rizdaputra Thanks for reaching out!

Could you check out our documentation in our Typescript example [here](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo/ts-example) on how to work with Typescript?

Note specifically that it's generally expected that you use a JS bundler like webpack to compile the code before directly running it (like [here](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo/ts-example#step-4---build-js-files)), which I believe is what you might be missing.
