### ISSUE TITLE
Echo demo build failed

### ISSUE THREAD

**Issue by carlskii** [grpc/grpc-web#179]
I followed the instruction to build the docker image, however its failing with this: 

    [HOSTCXX] Compiling src/compiler/ruby_generator.cc
    configure.ac:66: installing './ar-lib' 
    configure.ac:61: installing './compile' 
    configure.ac:46: installing './config.guess'
    configure.ac:46: installing './config.sub'
    configure.ac:48: installing './install-sh'
    configure.ac:48: installing './missing'
    benchmarks/Makefile.am: installing './depcomp'
    parallel-tests: installing './test-driver'
    previous directory /github/grpc-web/third_party/grpc/third_party/protobuf changed before 
    entering /tmp/arBtvFPU, expected dev=1048683 ino=791940, actual dev=1048683 ino=792742, 
    aborting. at /usr/share/autoconf/Autom4te/General.pm line 196.
    END failed--call queue aborted.
    Makefile:1342: recipe for target 'third_party/protobuf/configure' failed
    make: *** [third_party/protobuf/configure] Error 22
    make: *** Waiting for unfinished jobs....
    The command '/bin/sh -c cd /github/grpc-web/third_party/grpc &&   make && make install' returned a non-zero code: 137

**Comment by stanley-cheung** [comment]
Is it still an issue? I can't quite reproduce this. Running the docker commands on a VM seems fine.

**Comment by stanley-cheung** [comment]
Closed due to inactivity.
