### ISSUE TITLE
Make web plugin on Windows

### ISSUE THREAD

**Issue by atecce** [grpc/grpc-web#182]
<img width="943" alt="screen shot 2018-05-09 at 9 23 50 pm" src="https://user-images.githubusercontent.com/10567112/39847512-079d2da2-53d0-11e8-9663-f8952a3891df.png">

When running `make` from `javascript/net/grpc/web` on Windows to generate the plugin, it (predictably, perhaps) fails because the `-I` flag on `g++` is configured with the Unix path `/usr/local/include`, in mind.

<img width="768" alt="screen shot 2018-05-09 at 9 26 25 pm" src="https://user-images.githubusercontent.com/10567112/39847564-48c132ba-53d0-11e8-818b-794f87fca4aa.png">

Even when (maybe naively) simply changing the path to where `choco` drops the `include` directory, you get a similar error.

<img width="866" alt="screen shot 2018-05-09 at 9 28 00 pm" src="https://user-images.githubusercontent.com/10567112/39847544-33716772-53d0-11e8-8587-4d38ff6da310.png">

Sorry if this is just a "hai guys how do i use make on windows" question. But wasn't sure where else to inquire about this.

**Comment by atecce** [comment]
My work around is using Ubuntu in Docker seeing as I'm on 2016. Going to keep it open just in case you want an issue around for supporting Windows

**Comment by stanley-cheung** [comment]
Sorry currently Windows is not supported. Due to resource and priorities, it will probably be a while we get to this :)

**Comment by atecce** [comment]
np. just to be clear, this doesn’t preclude me deploying an nginx grpc-web service on windows, yes? just building the js client

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stanley-cheung** [comment]
Folding this into #250
