### ISSUE TITLE
Stalled project?

### ISSUE THREAD

**Issue by ravihugo** [grpc/grpc-web#189]
I'm not trying to throw shade, but... obviously a lot of people are being walked through gRPC by google advocates, and this project is extremely key to understanding how to move forward with grpc in websites or simply in phonegap/react-native style apps that use REST still. How shall we migrate away from REST when so many items seem to be hinged up on this project that isn't really moving forward?

**Comment by stanley-cheung** [comment]
Sorry for the delay. Are there specific features that your use case is waiting on? We are working on some of the features we set out in the [spec](https://github.com/grpc/grpc-web/blob/master/PROTOCOL-WEB.md). For example, we will be adding support to suppress CORS preflight requests shortly. (Second bullet point of https://github.com/grpc/grpc-web/blob/master/PROTOCOL-WEB.md#cors-support) We are also working on Retry support etc.

**Comment by ravihugo** [comment]
I think my use-case is generally in need of the following:
* typescript protoc output.
* JS streams (without callbacks) would be nice, for example using RX Observables would likely fit the streaming bill nicely.
* Windows/Mac localhost development model (without docker) - Presumably without running nginx locally or some other web server for local development.

**Comment by IanDuncanson** [comment]
I would second the feedback above. I think the reliance on nginx is problematic for us (we deploy on Windows, nginx is slow and not approved for our servers). I think the approach taken by improbable for the proxy is at least a lot more scalable and easier to deploy in multiple environments. And the typescript output is invaluable for front end web development.

**Comment by glerchundi** [comment]
Same opinion here.

Additionaly it would be more than interesting to have javascript grpc-web client published as a commonjs module in npm registries.

**Comment by johanbrandhorst** [comment]
Nginx as the proxy choice has been a major headache for me as well. Personally I would welcome more of a joint approach with Improbable and ideally move any features of this proxy to theirs and focus development in one place. The fact that two options exists and they basically live in isolation of each other is bad for the community and adoption of either project. Maybe settle on ONE proxy and release rival clients? The proxies are almost identical in functionality already.

**Comment by wenbozhu** [comment]
@ravihugo Thanks for the feedback! 

TS and better streaming APIs (i.e. besides the Node streams) are on the road-map.

Unlike other languages, grpc-web/JS is being developed internally for Google/Alphabet's own projects first. This limits how quickly we are able to release features for OSS users. At the same time, web ecosystems are prolific in every layer ... E.g.  Google closure support is a must, which is used by Google search/gmail/... but not so much externally.

On proxies, our immediate plans are:
1. Improve Envoy support; and possibly make Envoy the default proxy.  gprc-web is already integrated in Envoy, which means there is no custom code to build.
2. Publish our inter-op tests, and include the Improbable Go proxy as part of the interop test suite. This will ensure the two client libraries will work against different proxies. We have worked closely with  Improbable team in the past in defining the gprc-web protocol spec.
3. Support in-process proxying in more languages (in addition to Go). For this, we are planning to add Python support first, and [contributions are always welcome](https://github.com/grpc/grpc-web/blob/master/ROADMAP.md).

===

@glerchundi Could you help file an issue on the npm registry?

**Comment by IanDuncanson** [comment]
Making Envoy the default proxy does not help us poor souls who have Windows backends, in fact it makes it impossible

**Comment by wenbozhu** [comment]
Add an Envoy developer just passed me this

https://github.com/Microsoft/envoy

**Comment by IanDuncanson** [comment]
@wenbozhu thanks for this link, very interesting. We use mainly C# and C++ on our backend, but our GRPC services are C++. I will try build this up and give it a go.

**Comment by ravihugo** [comment]
Blown away by all the updates recently. Going to invest time into this again! Sounds like GA in Oct 👍
