### ISSUE TITLE
Relationship with grpc-gateway

### ISSUE THREAD

**Issue by benmccann** [grpc/grpc-web#198]
Hi, I'm having a hard time understanding the difference between this project and [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway)

What is it that nginx/envoy are being used for in this project?

Why do we need a JavaScript client library? Is the goal of this project to parse binary protobuf instead of json provided by grpc-gateway? If so, why? Is that more performant? Do you have any benchmark to demonstrate that this would be faster than the browser's native `JSON.parse`?

Is there a way to generate openapi specs and documentation when using grpc-web as we can do with grpc-gateway?

**Comment by jonahbron** [comment]
grpc-gateway exposes a RESTful/JSON API, which is more easily integrated in some cases.  GRPC-Web is a spec patch that makes GRPC/Protobuf communication possible that isn't with the base GRPC spec.

The actual spec doc will make things more clear:

https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

**Comment by wenbozhu** [comment]
@benmccann   To add to what Jonah said, we have no plan to generate openapi specs etc as part of the current gprc-web project. The binary protobuf messages are not necessarily more performant than JS but it allows us to pass the messages directly to a grpc server end-point. 

In google, we  use a JSON compatible format under the same protobuf API for grpc-web, but the format is not yet open-sourced.
