### ISSUE TITLE
How does auth work?

### ISSUE THREAD

**Issue by oferb** [grpc/grpc-web#207]
I'm wondering how auth works in grpc-web.
I searched for `auth` and `token` in the repo and didn't find anything.

Thanks!

**Comment by stanley-cheung** [comment]
Auth is orthogonal to gRPC-Web. Depending on your auth scheme, you obtain a token or a key separately and set them as key:value in the `metadata` argument per-RPC call.

We might have to provide a way to turn `WithCredentials` to `true` in the underlying transport but so far we haven't found a compelling and common use case yet.

**Comment by N1nJaC0d3** [comment]
how to work with social auth like facebook/twitter...? Nowadays, almost every web client requires social login feature along with typical username/password auth...

**Comment by N1nJaC0d3** [comment]
> Auth is orthogonal to gRPC-Web. Depending on your auth scheme, you obtain a token or a key separately and set them as key:value in the `metadata` argument per-RPC call.
> 
> We might have to provide a way to turn `WithCredentials` to `true` in the underlying transport but so far we haven't found a compelling and common use case yet.

So, how to implement it with metadata .? any example?

**Comment by Koulwa** [comment]
Best practices for gRPC web token authentication would be pretty cool rather than trying to hack at it myself. Like yes, put it in metadata, but then how do you protect routes? is there an intercepter of sorts? where it captures and validates that token before the actual gRPC requested is returned?
