### ISSUE TITLE
docker-compose up not working

### ISSUE THREAD

**Issue by inyourpc** [grpc/grpc-web#208]
I am running docker on windows, docker installation was successful, however, 
docker-compose up 

`docker-compose up
Creating network "grpcwebmaster1_default" with the default driver
Building prereqs
Step 1/7 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
Gracefully stopping...`

Threw error, 

Also after navigating to /net/grpc/gateway/examples/echo
and running 
 docker build -t grpc-web:echo-server  -f net/grpc/gateway/docker/echo_server/Dockerfile 

Does not help threw this error 
`unable to prepare context: unable to evaluate symlinks in Dockerfile path: GetFileAttributesEx C:\Users\dell\Desktop\grpc-web-master1\net\grpc\gateway\examples\echo\net: The system cannot find the file specified.
`

**Comment by stanley-cheung** [comment]
Is there someone from the community that can help with this Windows issue? Sorry I don't have the bandwidth to support clients installed on Windows for now.

**Comment by akoserwal** [comment]
@inyourpc @stanley-cheung: I am not able to reproduce this issue. I tested on windows 10. It is working fine.
