### ISSUE TITLE
Question: response metadata

### ISSUE THREAD

**Issue by ewang** [grpc/grpc-web#220]
Is there currently a way to access response metadata sent by the server?

**Comment by stanley-cheung** [comment]
For streaming calls, you can register a callback to the `status` event, like this: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/echoapp.js#L73

For unary calls, that's not currently exposed, and we should probably do something about it :)

**Comment by prabak** [comment]
Does this work with typescript? I have implemented a grpc-web client call with Typescript.  i.e. ```import_style=commonjs+dts```. I am using **envoy** as proxy. I can see the metadata on the response headers however, when i try to access it in the following code, it is undefined.

```
gcall.on('status', (status: grpcWeb.Status) => {
// status.metadata is undefined
});
```

Do I need to do anything special on the envoy.yaml file? or anywhere else?

thank you
