### ISSUE TITLE
documentation:gprcweb options

### ISSUE THREAD

**Issue by alexcpn** [grpc/grpc-web#231]
In https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/tutorial.md
the option is wrongly given as 

`$ protoc -I=. --plugin=protoc-gen-grpc-web=<path to plugin> \
  --grpc-web_out=out=echo.grpc.pb.js,mode=grpcwebtext:. ./echo.proto`

which gives the error 
`--grpc-web_out: my.proto: options: invalid mode - grpcwebtext`

correct option seems to be `mode=grpcweb` which is working

**Comment by stanley-cheung** [comment]
Can you try recompiling the grpc-web protoc plugin? The `mode=grpcwebtext` was only recently added. Here's part of our continuous testing: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/commonjs_client/Dockerfile#L24 which is using `mode=grpcwebtext`. 

There are other outdated part for `tutorial.md` but `mode=grpcwebtext` should be correct. Can you please try again?
