### ISSUE TITLE
require not working in ES6

### ISSUE THREAD

**Issue by lionelee** [grpc/grpc-web#237]
When I use `const {EchoRequest} = require('./generated/echo_pb.js'); ` in ES6 module,

I got the following error:
`recorder_service_pb.js?bd75:200 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

**Comment by stanley-cheung** [comment]
Looks like you can't mix ES6 `import` with CommonJS `module.exports`. ES6 is not supported by [protobuf](https://github.com/google/protobuf/tree/master/js) yet.

**Comment by stanley-cheung** [comment]
Added a note to main [README](https://github.com/grpc/grpc-web#import-style) that ES6 style `import` is not supported yet.

**Comment by juanjoDiaz** [comment]
Any intention fo implementing this in the future?

I think that it would be very beneficial to support ES6 imports since most people are using them nowadays.

**Comment by stanley-cheung** [comment]
ES6-style import has been implemented! 

Please check the [main page](https://github.com/grpc/grpc-web#typescript-support) for more information.

**Comment by juanjoDiaz** [comment]
But that requires TypeScript, right?
It would be good to have standard ES6 which should be very similar to TS but without the types.
something like `es6` and `es6+dts`.

**Comment by stanley-cheung** [comment]
I see. It would be nice to have in the future, but you might note that standard ES6-style import is not supported by [protobuf](https://github.com/protocolbuffers/protobuf/tree/master/js) yet. The reason why the `.d.ts` approach works right now is that we can still leverage the `.js` output (commonjs style) from protobuf and output a minimally viable set of typings for them to make it work.

Just ES6 style support would need cooperation from the protobuf side first. We will certainly keep an eye on that.

**Comment by juanjoDiaz** [comment]
Thanks! That makes sense!

Should this ticket be renamed to `Add support ES6 imports` and kept open so it's not forgotten?

**Comment by darrelladjei** [comment]
Hi there, wondering if es is now supported, doesn't seem to be the case in the docs?

**Comment by Masterxiechengxun** [comment]
is support es6?
