### ISSUE TITLE
Support compiling multiple .proto files with a single command

### ISSUE THREAD

**Issue by rwlincoln** [grpc/grpc-web#245]
`protoc` supports passing multiple `.proto` files with a single call. Typically, the output directory is specified and the file names are based on the names of the `.proto` files.

Currently, if more than one `service` is defined in more than one `.proto` file, `protoc` returns an error:

```
... Tried to write the same file twice.
```

**Comment by rwlincoln** [comment]
That issue refers to:

>Passing multiple packages' worth of *.proto files...

I have a single package that is defined across multiple `.proto` files in the same directory. Compiling them works unless there are services defined in more than one of the `.proto` files. In that case, the above error is returned.

**Comment by johanbrandhorst** [comment]
Ah ok, slightly different issue then. Sorry for any confusion.

**Comment by rwlincoln** [comment]
Here is an example with two separate services defined in the same package. It also relates to #244:

`apis/myproject/mayapi/v1/service-a.proto`

```protobuf
// Copyright 2018. All rights reserved.

syntax = "proto3";

package myproject.myapi.v1;

import "google/protobuf/wrappers.proto";

service ServiceA {
  rpc MethodA (google.protobuf.StringValue) returns (google.protobuf.StringValue);
}
```

`apis/myproject/mayapi/v1/service-b.proto`

```protobuf
// Copyright 2018. All rights reserved.

syntax = "proto3";

package myproject.myapi.v1;

import "google/protobuf/wrappers.proto";

service ServiceB {
  rpc MethodB (google.protobuf.StringValue) returns (google.protobuf.StringValue);
}
```

With `wrappers.proto` vendored into `apis/google/protobuf/wrappers.proto`. It should be possible to call `protoc` like this:

`$ protoc -I./apis  ...  ./apis/myproject/mayapi/v1/service-a.proto ./apis/myproject/mayapi/v1/service-b.proto`

This is possible with the aforementioned `golang/protobuf` plug-in, which would generate:

```
./pkg/myproject/myapi/v1/service_a.pb.go
./pkg/myproject/myapi/v1/service_b.pb.go
```

However, with `grpc-web` I have to call `protoc` separately for each file with a service and specify the output file name rather than just the output directory.

Perhaps the `out` [configuration option](https://github.com/grpc/grpc-web#client-configuration-options) could be made optional and when omitted a file could be generated for each input `.proto` that contains a service, with the file name determined by the name of the `.proto` file.

**Comment by ytkang** [comment]
I'm looking for similar but, In my case,

serviceA/a.proto
serviceB/b.proto
...
serviceN/n.proto

I can build these all by one command 
`protoc --go_out=plugins=grpc:. **/*.proto`

**Comment by hungpv-2039** [comment]
This is worked for me
`
protoc  --grpc-web_out=import_style=typescript,mode=grpcweb:$OUT_DIR \
        ./protos/*.proto`
