### ISSUE TITLE
Compling "protoc-gen-grpc-web" on windows.

### ISSUE THREAD

**Issue by CodebyOmar** [grpc/grpc-web#250]
After spending hours trying to figure out how to run make command on windows powershell, i finally figured it out, but i still couldn't compile the **protoc-gen-grpc-web** plugin. This is the error i get when i run ```make plugin```.

```
process_begin: CreateProcess(NULL, uname, ...) failed.
process_begin: CreateProcess(NULL, pwd, ...) failed.
cd ""/javascript/net/grpc/web && make
The system cannot find the path specified.
make: *** [plugin] Error 1
```

**Comment by CodebyOmar** [comment]
Tried it on git bash and i'm now having a different error.

```
cd "/c/Users/HP PC/Downloads/grpc-web-master/grpc-web-master"/javascript/net/grp                                                               c/web && make
make[1]: Entering directory `C:/Users/HP PC/Downloads/grpc-web-master/grpc-web-m                                                               aster/javascript/net/grpc/web'
g++ -std=c++11 -I/usr/local/include -pthread  -c -o grpc_generator.o grpc_genera                                                               tor.cc
grpc_generator.cc:19:10: fatal error: google/protobuf/compiler/code_generator.h:                                                                No such file or directory
 #include <google/protobuf/compiler/code_generator.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [grpc_generator.o] Error 1
make[1]: Leaving directory `C:/Users/HP PC/Downloads/grpc-web-master/grpc-web-ma                                                               ster/javascript/net/grpc/web'
make: *** [plugin] Error 2
```

**Comment by stanley-cheung** [comment]
Unfortunately Windows is not currently supported well. The `Makefile` above is not supposed to work on Windows yet. Instructions like `-I/usr/local/incude` to try to find the protobuf headers is very 'linux'-centric.

**Comment by CodebyOmar** [comment]
If I compile it on Linux, can I be able to use to plugin on windows? 🌚🤔

**Comment by Yannic** [comment]
@CodebyOmar I doubt that compiling on Linux and running on Windows will work.
You might be able to compile the plugin on Windows using [Bazel](https://docs.bazel.build/versions/master/windows.html).

`bazel build --compilation_mode=opt //javascript/net/grpc/web:protoc-gen-grpc-web`
The compiled plugin will be located at `bazel-bin/javascript/net/grpc/web/protoc-gen-grpc-web`.

**Comment by CodebyOmar** [comment]
Okay @Yannic I’ll try that

**Comment by stanley-cheung** [comment]
See also #186

**Comment by CodebyOmar** [comment]
@Yannic tried to build using bazel and it wasn't successful
```ERROR: bazel does not currently work properly from paths containing spaces (com.google.devtools.build.lib.runtime.BlazeWorkspace@44f745e2).```

**Comment by zaucy** [comment]
@CodebyOmar Looks like the full path you're running bazel on contains spaces. That would be a bazel problem and outside the scope of this project.

**Comment by henpanta** [comment]
@stanley-cheung can you confirm that compiling on Linux and running on Windows will work?

**Comment by stanley-cheung** [comment]
@henpanta Compiling on Linux and running on Windows will not work.

**Comment by henpanta** [comment]
@stanley-cheung : thank you, just for being sure: does it mean grpc-web is not working on windows, or just the protoc-gen-grpc-web tool?

**Comment by tam15** [comment]
Hello, I'm trying to use bazel to compile this plugin however I'm getting a "no such package" error, has this changed location since @Yannic 's solution?

$ bazel build @com_google_protobuf//:protoc //javascript/net/grpc/web:protoc-gen-grpc-web
ERROR: python.exe not found on PATH
Loading:
Loading: 0 packages loaded
ERROR: Skipping '//javascript/net/grpc/web:protoc-gen-grpc-web': no such package 'javascript/net/grpc/web': BUILD file not found on package path
WARNING: Target pattern parsing failed.
ERROR: no such package 'javascript/net/grpc/web': BUILD file not found on package path
INFO: Elapsed time: 0.404s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by stanley-cheung** [comment]
The pre-built binaries for the `protoc-gen-grpc-web` plugin for Windows has been uploaded along with the latest 1.0.3 release. Please check it out.

https://github.com/grpc/grpc-web/releases
