### ISSUE TITLE
Add Typescript definition file for the grpc-web npm package

### ISSUE THREAD

**Issue by aberasarte** [grpc/grpc-web#255]
Now that the grpcweb runtime is available as an npm package 🎉 🎉 , it would be even better if the package could include a Typescript definition file as well. This way, it would be much easier to consume the grpcweb runtime from Typescript code. 

If this isn't feasible I'm thinking about submitting a d.ts file to [definitely typed](https://github.com/DefinitelyTyped/DefinitelyTyped) but this is not the best solution.

**Comment by jonahbron** [comment]
I might be able to contribute a new file with the basic outline this week.

**Comment by glerchundi** [comment]
This would be fantastic!

**Comment by stanley-cheung** [comment]
I started a PR #258 to show how the `index.d.ts` might work. Any feedback appreciated!

**Comment by stanley-cheung** [comment]
PR #258 merged. The `index.d.ts` typings should be making it into the next release `0.4.0` currently planned for next week. 

After that user should be able to do `import * as grpcWeb from 'grpc-web';` after an `npm i grpc-web`.

**Comment by aberasarte** [comment]
Great! Thanks for adding this @stanley-cheung .

**Comment by stanley-cheung** [comment]
The npm package version `0.4.0` has been pushed. Please try it out!
