### ISSUE TITLE
JS error in docker-compose demo

### ISSUE THREAD

**Issue by dshuffma-ibm** [grpc/grpc-web#256]
Running the docker-compose setup I get this JS error when submitting my text:

![image](https://user-images.githubusercontent.com/16085295/44408778-07efc480-a52f-11e8-884f-df78624ff596.png)

The dummy websever seems to run fine, no 404s:
![image](https://user-images.githubusercontent.com/16085295/44408945-64eb7a80-a52f-11e8-882d-6aa9b6d5e21f.png)

- docker compose command: `docker-compose up echo-server envoy commonjs-client`
- using Firefox v61.0.2
- using grpc-web v0.3.0 (`caee772`)

**Comment by stanley-cheung** [comment]
Hm, I cannot quite reproduce this. It runs fine in my Firefox. The docker image seems to be brought up, but there seems to be some sort of problem when compiling the JS with webpack?

What happened if you try to run `docker-compose up echo-server envoy closure-client`?

**Comment by dshuffma-ibm** [comment]
@stanley-cheung ha... try clicking the blue "send" button instead of hitting enter!

**Comment by stanley-cheung** [comment]
Got it. Nice find! :) #257
