### ISSUE TITLE
Java (Jetty) proxy

### ISSUE THREAD

**Issue by henpanta** [grpc/grpc-web#271]
Hi all,

is there any proxy solution in Java instead of Go or NGINX? I'd like to use a single webserver, and Jetty is already in the application for other purposes.

best regards,
N.

**Comment by wenbozhu** [comment]
No. Do you like to help create a prototype ;), ideally as a servlet filter (e.g. which checks on content-type) that can be ported to other sevlet containers too?

We have some idea on a general guideline for developing in-process proxies, for different languages.  I worked on servlet 3.x/4.x specs and the async model in 3.x should be sufficient to implement grpc calls from a filter.

**Comment by flozano** [comment]
BTW, I think it'd be better if this was implemented at the same level as the grpc Java server: a netty codec that transforms the GRPC-Web requests into GRPC's native HTTP/2 messages that are handled in the netty pipeline the same way as native GRPC calls.

**Comment by wenbozhu** [comment]
Our current thinking is to implement grpc-web over the servlet API ... mostly for Web tier integration.  Due to similar work on grpc-swift, we plan to write up a doc on "recommended" approaches to integrate grpc-web with grpc on the server side.
