### ISSUE TITLE
Build Error on Ubuntu18.04 --- grpc-web version: 0.4.0

### ISSUE THREAD

**Issue by purebluesong** [grpc/grpc-web#275]
## Error Log:
g++ -std=c++11 -I/usr/local/include -pthread  -c -o grpc_generator.o grpc_generator.cc
grpc_generator.cc: In function 'std::__cxx11::string grpc::web::{anonymous}::GetRootPath(const string&, const string&)':
grpc_generator.cc:226:20: error: 'count' is not a member of 'std'
   size_t slashes = std::count(from_filename.begin(), from_filename.end(), '/');
                    ^~~
<builtin>: recipe for target 'grpc_generator.o' failed
make[1]: *** [grpc_generator.o] Error 1

## Command:
make install-plugin

**Comment by stanley-cheung** [comment]
Hm, I can't quite reproduce. I made a fresh Ubuntu 18.04 VM and the plugin compiles fine:

```
~/grpc-web$ sudo  make install-plugin
cd "/home/stanleycheung/grpc-web"/javascript/net/grpc/web && make install
make[1]: Entering directory '/home/stanleycheung/grpc-web/javascript/net/grpc/web'
g++ -std=c++11 -I/usr/local/include -pthread  -c -o grpc_generator.o grpc_generator.cc
g++ grpc_generator.o -L/usr/local/lib -lprotoc -lprotobuf -lpthread -ldl -o protoc-gen-grpc-web
install protoc-gen-grpc-web /usr/local/bin/protoc-gen-grpc-web
make[1]: Leaving directory '/home/stanleycheung/grpc-web/javascript/net/grpc/web'
~/grpc-web$

$ uname -a
Linux stanleycheung-ubuntu18 4.15.0-1018-gcp #19-Ubuntu SMP Thu Aug 16 13:38:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

But I perhaps did a bunch of `apt-get install` to start out of habit. Perhaps `build-essential` did help. Will look more into this.

**Comment by purebluesong** [comment]
It didn't work, still the same error. Do you need any env information else?

Actually, another problem occurs before this problem.

```shell
cd "/go/grpc-web-0.4.0"/javascript/net/grpc/web && make install
make[1]: Entering directory '/go/grpc-web-0.4.0/javascript/net/grpc/web'
g++ -std=c++11 -I/usr/local/include -pthread  -c -o grpc_generator.o grpc_generator.cc
grpc_generator.cc:19:53: fatal error: google/protobuf/compiler/code_generator.h: No such file or directory
 #include <google/protobuf/compiler/code_generator.h>
                                                     ^
compilation terminated.
<builtin>: recipe for target 'grpc_generator.o' failed
```

And then I run `apt-get install libprotoc-dev` fix this.

**Comment by purebluesong** [comment]
```
$ uname -a
Linux sprout-VirtualBox 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by purebluesong** [comment]
No problem when building on mac with bazel or makefile.

**Comment by stanley-cheung** [comment]
Just a guess: are you running `make install-plugin` as `root`, or using `sudo`? If former, can you try the latter?

**Comment by stanley-cheung** [comment]
#276 should fix this.

**Comment by purebluesong** [comment]
It works! Thank you.
