### ISSUE TITLE
wrong libprotoc.so library

### ISSUE THREAD

**Issue by Tails128** [grpc/grpc-web#278]
Hi,
Since release 0.2 I'm getting the following error as i follow your INSTALL.MD :

```
libprotoc.so.15: cannot open shared object file: No such file or directory
make: *** [/grpc-web/third_party/grpc/gens/src/proto/grpc/channelz/channelz.pb.cc] Error 127
```

I've worked with the 0.1 version of grpc-web succesfully on an ubuntu machine but due to various issues I'm now on an arch system with the latest version of grpc-web.
I've created a Dockerfile starting from ubuntu 16.04 in order to asses the problem's not the os, but the problem persists (same line but with a different path, which is the one i pasted) 

Either I'm missing something from install.md or there's something missing in it... 
I suggest adding a install.sh script to prevent user errors.

```
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y autoconf automake build-essential curl git \
  default-jdk default-jre libtool libpcre3-dev libssl-dev make wget zip

RUN git clone https://github.com/grpc/grpc-web.git
WORKDIR /grpc-web/scripts
RUN ./init_submodules.sh

WORKDIR /grpc-web
RUN git submodule update --init
WORKDIR /grpc-web/third_party/grpc
RUN git submodule update --init

WORKDIR /grpc-web/third_party/grpc/third_party/protobuf
RUN ./autogen.sh \
    && ./configure \
    && make \
    && make install

WORKDIR /grpc-web/third_party/grpc
RUN make && make install

WORKDIR /grpc-web
RUN wget https://dl.google.com/closure-compiler/compiler-latest.zip -O compiler-latest.zip \
    && unzip -p -qq -o compiler-latest.zip *.jar > closure-compiler.jar \
    && make
```

**Comment by stanley-cheung** [comment]
We have updated the [INSTALL.md](https://github.com/grpc/grpc-web/blob/master/INSTALL.md) recently - some of what you had is not necessary anymore. 

We have a "prerequisites" docker image for reference: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/prereqs/Dockerfile

**Comment by Tails128** [comment]
With the updated procedure the problem shifted a bit, but it's still presenting whenever I use protoc-gen-grpc-web: I'm using the following command (also tryed changing base64 to grpcweb):

```
project-proto: $(PROJECT_PROTO) protoc-plugin
	protoc -I=$(dir $<) --js_out=import_style=closure,binary:$(dir $<) $<
	protoc -I=$(dir $<) --plugin=protoc-gen-grpc-web=$(PROTOC_PLUGIN) \
	       --grpc-web_out=out=automa.grpc.pb.js,mode=base64:$(dir $<) $<

```
And I'm getting the following error (here simply by running protoc-gen-grpc-web:

```
$ protoc-gen-grpc-web 
protoc-gen-grpc-web: error while loading shared libraries: libprotoc.so.15: cannot open shared object file: No such file or directory
```

but LSing for libprotoc.so.15 results in:

```
$ ls /usr/local/lib/libprotoc.so.15
/usr/local/lib/libprotoc.so.15
```

```
$ ls /usr/lib/libprotoc.so.15
/usr/lib/libprotoc.so.15
```

**Comment by stanley-cheung** [comment]
After you run `sudo make install` from the `third_party/protobuf` directory, perhaps try running `sudo ldconfig`? It seems that you have another libprotoc installed in your system and `protoc-gen-grpc-web` got confused.

**Comment by Tails128** [comment]
Done it already with no result, i have the .so.13 from a previous grpc-web installation

**Comment by stanley-cheung** [comment]
Can you share your Dockerfile? I'll see whether I can reproduce this

**Comment by Tails128** [comment]
I was forgetting: I've adopted a solution for this problem while i was trying to figure out how to resolve the lib confusion problem:

I'm using a dockerfile from `grpcweb/common` in a `generate.sh` file like this as a solution:

```
docker build -t extractorbuild .
CONTAINER_ID=$(docker create extractorbuild)
docker cp "$CONTAINER_ID:/output/compiled/proto.js" ./compiled/proto.js

```

Dockerfile:

```

FROM grpcweb/common

RUN mkdir /output
RUN mkdir /output/src
RUN mkdir /output/src/grpc
RUN mkdir /output/compiled/
RUN apt-get update
RUN apt-get install -y wget unzip
RUN wget https://dl.google.com/closure-compiler/compiler-latest.zip -O compiler-latest.zip
RUN unzip -p -qq -o compiler-latest.zip *.jar > closure-compiler.jar
RUN rm compiler-latest.zip
RUN mv closure-compiler.jar /github/grpc-web/

//COPY the makefile you need
//COPY the proto/protos you need

WORKDIR /output
RUN make
```

And then i simply run ./generate.sh and get the proto.js file (I'm probably shifting to a $PATH variable to avoid copying every time).

**Comment by Tails128** [comment]
I'm not entirely sure why, but the `grpcweb/prereqs` image started to work as well...
I've used the same `cd /github/grpc-web && make install-plugin && protoc-gen-grpc-web` command as before (didn't use ldconfig since it's on the prereqs docker image) ... I probably used the old image again, it's a bit late and I got distracted, sorry about that.

**Comment by stanley-cheung** [comment]
So, all good? :)

**Comment by Tails128** [comment]
Yup, we can close the issue.
Sorry if it took me a while to answer, I wanted to do a couple tests to be sure!
