### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by Emixam23** [grpc/grpc-web#280]
Hey !

I am coming today because I would like to pass from REST HTTP exchange to gRPC. My microservices 

However, multiple question comes to my mind right now...

- How does work a "stub",  should it be a client with which I make each exchange (like a pipe, a socket) or should I generate a new one for each grpc exchange with my API?
- If it's better to keep the same client for each exchange, what's the best way to keep it available for the whole app? Should I use the state of my app?
- I saw as well with another repo you mentioned (in *https://github.com/improbable-eng/grpc-web/issues/114#issuecomment-361073333*) that they have a "redux middleware". I would like to know then what are the best practices in order to save the incoming data from my API with redux and the authentication (How to link redux and grpc's exchanged data)

I hope I am clear, feel free to ask details if needed :) I am new in react, my client isn't that big so I understand only the basic of React I think at the moment

Best,

Max

**Comment by stanley-cheung** [comment]
A 'stub' is just a regular class generated by the `protoc` plugin, one per service in your `.proto` definitions. For example, if you have an `AccountService` defined with several RPC methods, a `AccountServiceClient` class will be generated for you. You can then use this `AccountServiceClient` to make RPC with a backend server implementing that service.

For your other questions, it depends on the framework you use. I personally am not very familiar with redux. But at the end of the day, it's some data you get from a backend service. You can manipulate however you see fit.
