### ISSUE TITLE
Stream data callback not called till after last stream element sent

### ISSUE THREAD

**Issue by ctoomey** [grpc/grpc-web#281]
I'm calling a grpc function with a stream response as shown in the `serverStreamingEcho()` example in the README, but even though the server sends a stream element every 1/2 second, my `stream.on('data', ...)` callback doesn't get called until after the whole stream has been sent down (then it gets called for each element). So it's not actually "streaming". I'm using the Envoy grpc-web filter.

Is there a special request header that needs to be sent or something else that needs to be done to get streaming to work? Thanks.

**Comment by stanley-cheung** [comment]
1. Which platform, browser and browser version are you using?
2. Are you able to run our pre-packaged [Quick demo](https://github.com/grpc/grpc-web#quick-demo)? Typing "4 Hello" into the box should stream 4 "Hello" messages 0.5 seconds apart back to the browser. If that works, we should see how the pre-packaged demo is different from yours. If even that doesn't work, then we should focus on which environment you are running your code from.

**Comment by stanley-cheung** [comment]
Also just as a guess, when you run the `protoc-gen-grpc-web` plugin, did you pass in `mode=grpcwebtext`? If you had passed in `mode=grpcweb` streaming won't work, yet.

**Comment by ctoomey** [comment]
Yep I used mode=grpcwebtext. Will change that tomorrow and confirm
streaming works, thanks.

**Comment by ctoomey** [comment]
I meant I had used `mode=grpcweb`, I've confirmed it works when I use `mode=grpcwebtext`. What's the ETA for it working w/ `mode=grpcweb` and is there a tracking ticket for that? Thanks for your help.

**Comment by stanley-cheung** [comment]
Is there any particular reason you need to use `mode=grpcweb`?

**Comment by ctoomey** [comment]
Mainly we'd like to benefit from the smaller bandwidth needed for the
binary messages, and seems that should normally be the default for grpc
implementations.

**Comment by stanley-cheung** [comment]
I see. Currently, there are limitation on browsers on receiving partial binary data. See a more detailed comment [here](https://github.com/grpc/grpc-web/issues/87#issuecomment-290256077).

**Comment by ctoomey** [comment]
Got it, helpful to know that this won't be coming soon. Thanks for your help, closing this ticket.

**Comment by fawdlstty** [comment]
> Also just as a guess, when you run the `protoc-gen-grpc-web` plugin, did you pass in `mode=grpcwebtext`? If you had passed in `mode=grpcweb` streaming won't work, yet.

Hello. Is there any new information for this issue?

**Comment by sampajano** [comment]
@fawdlstty Thanks for checking :)

Just to confirm, are you referring to the streaming support when `mode=grpcweb`?

**Comment by fawdlstty** [comment]
> Just to confirm, are you referring to the streaming support when `mode=grpcweb`?

yes

**Comment by sampajano** [comment]
@fawdlstty Aha thanks for clarifying!

Actually there's been a related recent thread below:
https://github.com/grpc/grpc-web/discussions/1409

Our previous understanding that streaming won't work with `mode=grpcweb`, but the above discussion is bringing the question of whether it might be made to work in some environments (or maybe it's already working).

Please feel free to follow the above thread and/or chime in if you wish.

Thanks :)

**Comment by fawdlstty** [comment]
@sampajano  Thank you for your reply. I will keep an eye on this discussion

**Comment by sampajano** [comment]
@fawdlstty Great! You're welcome! 😃
