### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by Generalomosco** [grpc/grpc-web#285]
I'm having cors issue giving below error while using grpc in nodejs server backend and locally using grpc-web outside my backend server. 

`Cross-Origin Read Blocking (CORB) blocked cross-origin response http://data.xx.win/books.BookService/List with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

**Comment by stanley-cheung** [comment]
Which proxy did you deploy to handle the grpc-web requests?

**Comment by Generalomosco** [comment]
This is what i does in my `Additional Apache directives`  to reserve proxy from domain root and it works with socket.io but don't work with grpc when i reserve the port to gprc server port.

```
RewriteEngine On
RewriteCond %{REQUEST_URI}  ^/            [NC]
RewriteRule /(.*)           http://localhost:50051/$1 [P,L]

ProxyPass        / http://localhost:50051/
ProxyPassReverse / http://localhost:50051/
```
