### ISSUE TITLE
Requesting images

### ISSUE THREAD

**Issue by n4uti** [grpc/grpc-web#286]
Hello!
We just developed a couple of requests with straight forward rpc calls returning simple objects. 
We now have the questions how we handle rpc calls returning image data and display them inside an img element with the src tag. Can this be done with grpc-web?

We tried to request the image as base64 data but we do not think this is the way to load images in a correct way with grpcweb - but it works rendering them in the src of an img element.

Same question for requesting and viewing video content.

Please help us with your expertise, thanks!

**Comment by stanley-cheung** [comment]
This is more of how you define your .proto API. I suppose you can define a protobuf message like

```
message ContentChunk {
  bytes chunk = 1;
}
```

And a streaming method like

```
service StreamingService {
  rpc Stream(StreamingRequest) returns (stream ContentChunk);
}
```

As to how to chunk-up the data from the server side and piece the data back at the client side, that's up to specific application / codec etc and is out of the scope of this library. Hope this helps!

**Comment by doug** [comment]
Grpc-web should support
https://github.com/googleapis/googleapis/blob/master/google/api/httpbody.proto

google.api.HttpBody
