### ISSUE TITLE
`end` event occasionally not emitted

### ISSUE THREAD

**Issue by thesamet** [grpc/grpc-web#289]
I am making a streaming RPC call and listening using `on()` to `data`, `status` and `end` events. I'm always getting the data, and always getting a status with code 0, but the `end` event only appears about 20% of the time. My client code only sends that one single streaming request.

Is this a known issue, or are there any obvious things I might be missing? If not, I'll share some minimal code to demonstrate this issue.

**Comment by thesamet** [comment]
Chrome on Linux, envoy

**Comment by thesamet** [comment]
This repository has a self contained minimal example.

https://github.com/thesamet/grpc-web-no-end

```
git clone https://github.com/thesamet/grpc-web-no-end.git
cd grpc-web-no-end
docker-compose up
```

Then direct your browser to http://localhost:8080 and open the javascript console from the developer tools.

You will see the streaming request logged, but the `end` event never gets logged.

Here is how to get it to log intermittently:
```
cd jsclient
npm install
protoc --js_out=import_style=commonjs:gen --grpc-web_out=mode=grpcwebtext,import_style=commonjs:gen ../protos/myservice.proto -I../protos
browserify main.js -o static/bundle.js
```

and open index.html directly in your browser (by going to file:///home/...)

**Comment by thesamet** [comment]
I used the above to reproduce this problem on Mac OS X, both Chrome 68 and Safari 11.

**Comment by stanley-cheung** [comment]
Thanks for the information. I will try to reproduce.

**Comment by stanley-cheung** [comment]
Sorry for the delay. I was working on #302 and tried to reproduce this and found this (this is tested with Chrome, Linux, Envoy):
 - If the backend grpc server was implemented in c++, I get the `'end'` signal about ~50% of the time (or maybe slightly less).
 - If the backend grpc server was implemented in Node, I get the `'end'` signal 0% of the time!

I suspect this is something in the Envoy layer, but that may take some time to track the root cause down. I will keep looking.

**Comment by mitar** [comment]
@thesamet How do you know which message in the stream is the last message?

**Comment by TBoshoven** [comment]
I have observed the missing "end" event as well. Firefox on Linux, Envoy.
I'm getting about 50% success rates with my call.

**Comment by TBoshoven** [comment]
I noticed that for streams with no items in them, I never get the "status" event, so the work-around does not really help.

**Comment by jonno317** [comment]
I'm noticing this behavior consistently with node.js for the grpc servers and envoy.

Specifically I have 2 streaming RPCs in different services pointing at the same node service. In effect this means I have 2 routes (one for each service) both pointing at the same cluster in Envoy. This is mostly so I have the option of splitting the service implementations later and only needing to update the Envoy configuration. 

With this setup, 1 of the RPCs has consistently triggered the end event (100% of the time as far as I can tell). The other RPC never triggers the end event. 

Both RPCs share the same definition signature are are implemented nearly identically (just streaming different data).
