### ISSUE TITLE
About another grpc-web

### ISSUE THREAD

**Issue by purebluesong** [grpc/grpc-web#291]
Any official comments for this repo https://github.com/improbable-eng/grpc-web ?

**Comment by wenbozhu** [comment]
We collaborated on the spec, and improbable/grpc-web is definitely a valuable contribution for the gRPC ecosystem.

grpc/grpc-web uses google-closure/JS to ensure compatibility and performance (for both grpc-web and protobuf) and google-closure is a must for Google web apps. TS support is experimental and full TS support with protobuf is yet to be released.

For other details, you should check the road-map, user guides on each project.

**Comment by jackielii** [comment]
I think this should be added to the README, it confused me a lot in the beginning, especially there is and example that uses the `grpcwebproxy` , and a link to the other repo.
