### ISSUE TITLE
Maps<key, value> are decoded as arrays

### ISSUE THREAD

**Issue by Tails128** [grpc/grpc-web#296]
Hi,
I'm working with a map item inside a message and I've noticed the structure of the map is a bit odd.
The item I'm sharing looks like this (don't mind the generic names, they are just for simplicity) :
```
message: {
    "key0": "value0",
    "key1": "value1"
}
```
The way grpc streams it is
```
message {
    key: "key0",
    value: "value0"
},
message:{
    key: "key1",
    value: "value1"
},
```
The item given by grpc-web's proto is:
```
message: Array[
    0: Array["key0", "value0"],
    1: Array["key1", "value1"],
]
```

What I'd expect on the js by a map message is:
```
{
   "key0": "value0",
   "key1": "value1",
}
```

**Comment by stanley-cheung** [comment]
This is more of a question for [protobuf](https://github.com/protocolbuffers/protobuf/tree/master/js).

Issue similar to this:
 - https://github.com/protocolbuffers/protobuf/issues/2056
 - https://github.com/protocolbuffers/protobuf/issues/2789

Looks like for now, the APIs being supported are `set`, `get`, `has`, etc. I believe what you are looking for is something like `toObject`. The method was there but it is not doing what you expected. Please file an issue (or follow their development) with protobuf.

**Comment by Tails128** [comment]
I see... reading those issues it seems they do not feel like it's an issue right now, I think I'll just update my parser class for npm use in case anyone has the same problem.

Thank you!
