### ISSUE TITLE
error code is a string instead of int

### ISSUE THREAD

**Issue by thesamet** [grpc/grpc-web#297]
When I set up envoy, but the upstream grpc server is not set up, the error code that is returned to the app is `"14"` as a string, instead of a number.

This line might be the culprit: https://github.com/grpc/grpc-web/blob/92aa9f8fc8e7af4aadede52ea075dd5790a63b62/javascript/net/grpc/web/grpcwebclientreadablestream.js#L200  - maybe the header needs to be converted to a number?

**Comment by stanley-cheung** [comment]
Acknowledged.
