### ISSUE TITLE
Generated invalid code

### ISSUE THREAD

**Issue by mitar** [grpc/grpc-web#306]
I tried generating files based on the guide, and in my case it generates invalid output:

```js
const grpc = {};
grpc.web = require('grpc-web');

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var value_pb = require('./value_pb.js')
const proto = {};
proto. = require('./core_pb.js');
```

See the final line. So I have `value.proto` and `core.proto` files. I am using protoc 3.5.1, and today's master branch of this repo.

Also the final line is:

```
module.exports = proto.;
```

**Comment by mitar** [comment]
My `.proto` files do not have `package` defined.

**Comment by mitar** [comment]
So it seems it is not possible to generate code for service which is not inside a package. This is a problem because on the server side we have such code (in Python). If I add a package name on the client and not on the server (for compatibility with other clients) it does not work because method names are different. Client prefixes them with package name.

So the question is how to generate code without the package/outside of the package.

**Comment by stanley-cheung** [comment]
Will fix.

**Comment by mitar** [comment]
I now run the following commands which make it work:

```
sed -i 's/module\.exports = proto\.;/module.exports = proto;/g' core_grpc_web_pb.js
sed -i 's/const proto = {};/const proto =/g' core_grpc_web_pb.js
sed -i 's/proto\. = require/require/g' core_grpc_web_pb.js
```

In short, I replace:

```
module.exports = proto.;
```

with:

```
module.exports = proto;
```

And:

```
const proto = {};
proto. = require('./core_pb.js');
```

with:

```
const proto = require('./core_pb.js');
```
