### ISSUE TITLE
Cannot access options

### ISSUE THREAD

**Issue by mitar** [grpc/grpc-web#307]
In our proto files we do something like:

```
extend google.protobuf.FileOptions {
    string protocol_version = 54001;
}

option (protocol_version) = "1.2.3";
```

This allows us to encode the version of the API into the API itself. Then user of the API can do (in Python):

```python
version = core_pb2.DESCRIPTOR.GetOptions().Extensions[core_pb2.protocol_version]
```

To retrieve this constant from the API file.

I see in generated JavaScript file that file options are extended. But the option itself is not stored anywhere. Could you add it as well?

**Comment by stanley-cheung** [comment]
This may be an issue for [protobuf](https://github.com/protocolbuffers/protobuf), but I will confirm.

**Comment by stanley-cheung** [comment]
Yea this is a protobuf issue: https://github.com/protocolbuffers/protobuf/issues/3554

**Comment by mitar** [comment]
Oh, my own issue there. How time flies. :-)

**Comment by stanley-cheung** [comment]
Yea that part was controlled by `--js_out`. This repo's plugin is responsible for `--grpc-web_out`.
