### ISSUE TITLE
has it been released for production use?

### ISSUE THREAD

**Issue by SantoshSah** [grpc/grpc-web#319]
As it is mentioned that it will be released by Oct. 2018 for general availability but i did not find it released version any where. has it been released for production use?

**Comment by stanley-cheung** [comment]
We are very close. We are just going through some administrative process before marking a 1.0 release. In fact, the website update PR: https://github.com/grpc/grpc.github.io/pull/737 has been ready for quite a while, just pending a merge. And the version bump #288 is ready as well.

cc @hsaliak

**Comment by SantoshSah** [comment]
Thank you @stanley-cheung and team for great work. Waiting to use its official release.

**Comment by stanley-cheung** [comment]
Release 1.0.0 has been tagged.
