### ISSUE TITLE
mixed content error

### ISSUE THREAD

**Issue by nigeltiany** [grpc/grpc-web#325]
I am running the echo example in istio with transport layer security. Sending a request shows a mixed content error.  ```main.js:405 Mixed Content: The page at 'https://example.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.com/EchoService.EchoService/Echo'. This request has been blocked; the content must be served over HTTPS.``` 

How do i fix this if its not a grpc-web bug. Also couldn't find any documentation on how to use credentials or options parameter when creating a client  like here -> ```new EchoServiceClient(window.location.origin, credentials=null, options=null);``` Could there be a tls options flag that i'm missing?

**Comment by nigeltiany** [comment]
Found the cause. GRPC redirection isn't a thing so although my istio gateway redirects all traffic to port 443, the client still tries a http request to port 80 even though window.location.origin is ```https://site.com```. I changed the client code to
```js
var protocol = window.location.protocol;
var echoService = new EchoServiceClient(window.location.origin + (protocol === 'https:' ? ':443' : ':80'), null, null);
```

**Comment by nigeltiany** [comment]
Yes I got it working but setting the url to ```https://example.com``` doesn't use the correct port. You have to explicitly set it to ```https://example.com:443```

**Comment by stanley-cheung** [comment]
That seems like a config issue on the endpoint. Closing this for now. Let me know if you have other questions!
