### ISSUE TITLE
Go gRPC server with javascript frontend?

### ISSUE THREAD

**Issue by emailtovamos** [grpc/grpc-web#326]
In this example here (https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/tutorial.md) the backend is written in javascript so that the client can simply "require" the corresponding .js file and access the functionality. 
How exactly would this work if I want to write the backend using Go? Is it possible? 
Sorry if this is a simply question as I am new to this.

**Comment by stanley-cheung** [comment]
Yes, you can implement the backend gRPC service in any language supported by gRPC, including Go. See the [gRPC Basics: Go](https://grpc.io/docs/tutorials/basic/go.html) page for more details.
