### ISSUE TITLE
Handling OPTIONS request

### ISSUE THREAD

**Issue by nigeltiany** [grpc/grpc-web#333]
I am running the echo example on a kubernetes with an istio service mesh. The example works great, but when I move the server to ```api.example.com``` and the client to ```client.example.com```, options requests stay pending for a while then fail.

**Comment by nigeltiany** [comment]
Never mind. Found it. 
```js
var echoService = new EchoServiceClient('api.example.com:443', null, { suppressCorsPreflight: true });
```

**Comment by stanley-cheung** [comment]
@nigeltiany FYI `suppressCorsPreflight` is not a fully supported nor documented feature for now. There are risks using this feature for now, and not all proxies are supporting this. We are still working on better defining this feature internally.

**Comment by bitsmaker** [comment]
@nigeltiany I am relatively new to grpc-web. I am trying to get my client to connect via https. Could you please share your config for kubernetes and istio?
Thanks
