### ISSUE TITLE
Web Sockets support

### ISSUE THREAD

**Issue by lgordey** [grpc/grpc-web#350]
Hi guys!

Is there `WebSocket` support in `grpc-web`?
All current examples are about http REST.

**Comment by weilip1803** [comment]
There is only server side streaming now on grpc-web where the client makes a unary request and the server streams a response till it gets canceled.

 Grpc-Web does not support 2 way/bidi streaming yet like websocket does. You can add your use case here at this [link](https://github.com/grpc/grpc-web/issues/24).

**Comment by wenbozhu** [comment]
Yes, use cases are always useful. 

With websockets over http/2 becomes more widely available and supported by proxies, we will look into supporting ws for bidi streaming, with proper fall-backs.

This is also covered in the[ road-map doc](https://github.com/grpc/grpc-web/blob/master/ROADMAP.md).
