### ISSUE TITLE
Code generator: npm CLI package or docker builder image

### ISSUE THREAD

**Issue by smnbbrv** [grpc/grpc-web#356]
Hi guys,

your project is super!

Do you have any plans on creating some sort of NPM cli package (e.g. grpc-web-cli) that generates the code without cloning the repository and compiling it locally, like e.g. node-sass does it?

So, I can add it to any web project by `npm i -D grpc-web-cli` and generate the code flawlessly on any physical / virtual machine without any problem.

**Another option**

The official docker image for generating the code would be also sufficient. E.g.

```sh
docker run -v proto:/var/proto grpc/grpc-web-generator
```

**Comment by pumano** [comment]
@smnbbrv currently you can use as workaround https://github.com/juanjoDiaz/grpc-web-generator docker image

**Comment by smnbbrv** [comment]
would be super if this workarund would be quite official one and mentioned in the README :)

**Comment by stanley-cheung** [comment]
The pre-built binaries for the `protoc-gen-grpc-web` plugin has been uploaded along with the latest 1.0.3 release. Please check it out.

https://github.com/grpc/grpc-web/releases
