### ISSUE TITLE
How big is the performance gap between the grpc-web compared with gprc ?

### ISSUE THREAD

**Issue by xeoshow** [grpc/grpc-web#364]
Hello,

If using grpc-web with envoy, and in the same env, compared with grpc native client (backend is the same grpc server), How big is the performance gap between the grpc-web compared with gprc ?

Googled but seems did not find anything useful, any help is highly appreciated!

Best regards, Jason

**Comment by wenbozhu** [comment]
The latency is pretty much decided by the browser and then the Envoy (proxying overhead). 

However, (with https) most browsers will speak HTTP/2 against Envoy.

CPU is dominated by the protobuf more than anything else.

**Comment by xeoshow** [comment]
Hello wenbo, 

Thanks for quick help. I found a below pic, which shows gRPC-Web (from Browser) connect to envoy via HTTP/1.1, if so, could it still utilize the good features from HTTP/2? And this is why I would like to question about the performance... 
https://cdn-images-1.medium.com/max/1000/1*XzL4BnES1u_DXz3qXq73xQ.png

And regarding the browser and Envoy, if we assume their overhead is negligible, how about the performance comparison?

Sorry new to gRPC-Web and need your further kind help!~

Best regards, Jason

**Comment by xeoshow** [comment]
Aha, got it, so that pic should replace HTTP/1.1 with HTTP/2 if the browser supports HTTP/2 ...

And I can think of the performance gap is minor from theory when assuming the overhead of browser and Envoy is negligible?

Thanks a bunch!

Best regards, Jason

**Comment by wenbozhu** [comment]
Pretty much all browsers will negotiate http/2 with the proxy for https.

Re: performance gap, correct, when the browser also speaks http/2.

===

OTOH, the binary protobuf is noticeably slower than JSON in browsers. As mentioned on the road-map doc, we are in the process of open-sourcing a more efficient (text) encoding format for protobuf for web clients.

**Comment by xeoshow** [comment]
Got it. And last question: since grpc-web could be installed via npm as below, so it should can be used in the nodejs server context? If so, still the same situation regarding performance? Thanks!
`npm i grpc-web`

**Comment by wenbozhu** [comment]
No, grpc-web only works from browsers.

**Comment by stanley-cheung** [comment]
No, the `grpc-web` npm package is only meant to be used in browsers
