### ISSUE TITLE
Fix the link to our project's site

### ISSUE THREAD

**Issue by peaceiris** [grpc/grpc-web#371]
![screen shot 2018-11-12 at 3 46 46](https://user-images.githubusercontent.com/30958501/48316965-df5b0080-e62d-11e8-90c5-eb622a6a9770.jpg)

I suggest the link change.

```diff
- http://grpc.io
+ https://grpc.io
```

**Comment by stanley-cheung** [comment]
Fixed. Thanks for pointing that out!
