### ISSUE TITLE
gRPC-web nginx module does not work with latest nginx v1.15.6

### ISSUE THREAD

**Issue by sirudog** [grpc/grpc-web#372]
Hi, 

I have compiled nginx 1.15.6 with the custom nginx module found in this repo successfully. The commit I used for nginx is: https://nginx.googlesource.com/nginx/+/13a0072553ac718a26220f68747cd2875dec52e2 

Then I used this grpc-web-enabled nginx in the echo example, but I got errors. 
After that I realized that nginx is a submodule in this repo and it is fixed to this commit: https://nginx.googlesource.com/nginx/+/6feddd653e37517f888d8ba7a38ceb4f71063818

Compiling this version of nginx makes the echo example work again. 
This is more than 1 and a half year old version of nginx, v1.11.13. 
Is this a known issue and is there a plan to make this nginx module work with newer versions of nginx?

**Comment by stanley-cheung** [comment]
Unfortunately, there is currently no plan to make sure the custom grpc-web module works with later version of Nginx. Our tests rely on the fact that the third_party/nginx module is pinned to this older version.

**Comment by dalu** [comment]
May I ask something?

Do I require this nginx module when I have a grpc service sitting behind nginx?
I just checked this repo again and saw that it was >=v1.0.
Congratulations, this is a big step imho.

**Comment by sirudog** [comment]
@dalu Yes. This module translates between grpc-web and grpc protocols. So in your nginx config you can proxy (with grpc_pass) to your grpc service behind nginx.

**Comment by stanley-cheung** [comment]
Yea. We kind of have an example on how you can use this Nginx grpc-web module here: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/nginx/Dockerfile

You will need to compile with something similar to `make standalone-proxy` and need a `nginx.conf` with a `grpc_pass` config line like this: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/nginx.conf#L24
