### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by javoire** [grpc/grpc-web#376]
Having JSON support for payloads in gRPC web would be great. One of the reasons why is that It's possible that the native parsing of JSON is faster in slower devices like TVs than grpc-web protobuf base64 decoding.

Cheers

**Comment by QuentinBrosse** [comment]
I think that it's already in [the roadmap](https://github.com/grpc/grpc-web/blob/master/ROADMAP.md#non-binary-message-encoding) :)

**Comment by javoire** [comment]
you're right, thx :)
