### ISSUE TITLE
e.serializeBinary is not a function

### ISSUE THREAD

**Issue by cenyG** [grpc/grpc-web#377]
Hi, I do everything according to Readme, but it's not working for me.
Ok, I thought, may be something wrong with my environment and I tried to do the way with dockers. Copy/Paste from Readme.md :
```
$ docker-compose pull prereqs common node-server envoy commonjs-client
$ docker-compose up -d node-server envoy commonjs-client
```
But I still have an error 
```
Uncaught TypeError: e.serializeBinary is not a function
    at module$contents$grpc$web$AbstractClientBase_AbstractClientBase.MethodInfo.requestSerializeFn (main.js:8)
    at module$contents$grpc$web$GrpcWebClientBase_GrpcWebClientBase.rpcCall (main.js:8)
    at n.helloworld.GreeterClient.sayHello (main.js:8)
```

Can you help me please?

**Comment by stanley-cheung** [comment]
Can you make sure no other programs are running at port `:8080`. `:8081` and `:9090`? That's the only thing I can think of right now

**Comment by cenyG** [comment]
Now it works like in Readme.md, but I don't know why.
It's not about ports, I retried a lot of times and then it suddenly start working))
You can close it.

**Comment by basque21** [comment]
I have the same problem, any idea of why could it be?

**Comment by colin353** [comment]
It may be due to outdated protoc - I had this issue and updating fixed it. Try reinstalling protoc from here: https://github.com/protocolbuffers/protobuf/releases
