### ISSUE TITLE
Help: easily from js-object to ts-object in typeScript?

### ISSUE THREAD

**Issue by jmzwcn** [grpc/grpc-web#393]
How to easily from js-object to ts-object in angular/typescript? the below is so ugly...

const ordersClient = new OrdersClient(environment.apiUrl, null, null);
          const order = new Order();
          const contact = new Contact()
          contact.setName(this.person.name);
          contact.setTel(this.person.tel);
          order.setContact(contact);
          let from = new Position();
          from.setName(this.order.from.name);
          from.setAddress(this.order.from.address);
          order.setFrom(from);
          let to = new Position();
          to.setName(this.order.tos[0].name);
          to.setAddress(this.order.tos[0].address);
          order.setTosList([to])
          order.setType(this.order.type);
          order.setFee(this.order.fee);
          // order.setAnnotationsList([{ "name1": "test1" }, { "name2": "test2" }])
          console.log('==', this.order);
          const call = ordersClient.add(this.order, { 'custom-header-1': 'value1' },
            (err: grpcWeb.Error, response: Order) => {
              console.log(err);
              console.log(response);
            });
          call.on('status', (status: grpcWeb.Status) => {
            console.log(status); call.on('status', (status: grpcWeb.Status) => {
              console.log(status);
            });
          });
        }

I saw already having ts.toObject, it is really useful. Seems ts.fromObject is missing... or change ts.object's getter/setter to key/value, so appreciated for your help. 

similar issue: https://github.com/grpc/grpc-web/issues/382

**Comment by iCovarrubias** [comment]
I found this while looking for a similar thing (any means to go from a plain JS Object to Protobuf):

https://github.com/protocolbuffers/protobuf/blob/master/js/message.js#L180

It seems that the option is turned off by default, however, I can't find a way on how to turn that option on.

See also the "Messages" section here:
https://developers.google.com/protocol-buffers/docs/reference/javascript-generated

> set jspb.Message.GENERATE_TO_OBJECT to false before code generation.

Again, no idea on how to do that, although this flag gets rid of the handy `toObject` method, I was thinking that figuring out how to set this flag can help us to figure out how to turn on the other flag and get the `fromObject` method generated.

**Comment by shaxbee** [comment]
I made pull request on protobuf repo: https://github.com/protocolbuffers/protobuf/pull/5397
After trying this a while in private codebase we found out some issues with this approach:
* it is *not* JSON format described in https://developers.google.com/protocol-buffers/docs/proto3#json
* it prefixes reserved identifiers with `pb_`, eg. `package` becomes `pb_package`
* it requires forking type definitions of google-protobuf for well-known types
* it requires forking grpc-web to patch typings generator with `fromObject` definitions

As hard as it sounds the easiest approach would be to write separate plugin that auguments js classes and typings with methods for converting from/to JSON format.

**Comment by stanley-cheung** [comment]
Closing this for now. This sounds like a protobuf API issue. And we don't have official TypeScript support from protobuf.

**Comment by Volankey** [comment]
> How to easily from js-object to ts-object in angular/typescript? the below is so ugly...
> 
> const ordersClient = new OrdersClient(environment.apiUrl, null, null); const order = new Order(); const contact = new Contact() contact.setName(this.person.name); contact.setTel(this.person.tel); order.setContact(contact); let from = new Position(); from.setName(this.order.from.name); from.setAddress(this.order.from.address); order.setFrom(from); let to = new Position(); to.setName(this.order.tos[0].name); to.setAddress(this.order.tos[0].address); order.setTosList([to]) order.setType(this.order.type); order.setFee(this.order.fee); // order.setAnnotationsList([{ "name1": "test1" }, { "name2": "test2" }]) console.log('==', this.order); const call = ordersClient.add(this.order, { 'custom-header-1': 'value1' }, (err: grpcWeb.Error, response: Order) => { console.log(err); console.log(response); }); call.on('status', (status: grpcWeb.Status) => { console.log(status); call.on('status', (status: grpcWeb.Status) => { console.log(status); }); }); }
> 
> I saw already having ts.toObject, it is really useful. Seems ts.fromObject is missing... or change ts.object's getter/setter to key/value, so appreciated for your help.
> 
> similar issue: #382

You can try this library https://github.com/Volankey/grpc-web-from-object.
