### ISSUE TITLE
426 error code when using nginx as react.js frontend proxy

### ISSUE THREAD

**Issue by chenxiang-roadstar** [grpc/grpc-web#420]
Hi, 
We are using java grpc backend with standard envoy as proxy server. We deploy these two image as sidecar in kubernetes server.  It works fine if we directly using IP address like http://10.0.0.1/ from react.js. But when we try to use nginx as react.js frontend proxy. below is our nginx conf:
    location /grpc {
        proxy_pass_request_headers      on;
        proxy_set_header Content-Type "application/grpc";
        proxy_pass  http://10.0.0.1;
    }
we keep getting 426 error code as below:
![image](https://user-images.githubusercontent.com/40410364/50469541-c306ef00-0961-11e9-8b4e-0a701e610aec.png)
Any idea what is different  when using nginx proxy or directly using IP address?

Thanks,
Alex

**Comment by VladymyrPavlov** [comment]
Hi, 
May be this help you. [gRPC + Nginx](https://www.nginx.com/blog/nginx-1-13-10-grpc/)

**Comment by chenxiang-roadstar** [comment]
hi,found out just need to specify Nginx proxy http version as http 1.1
