### ISSUE TITLE
Document browser support

### ISSUE THREAD

**Issue by bryanburgers** [grpc/grpc-web#423]
I’m on a team evaluating gRPC-web. I can’t find anywhere in the readme or in any of the introductory blog posts any mention of what browsers are supported.

Is there any information about what features a browser needs to support in order to do gRPC-Web?

I guess, specifically, the question will be what is the minimum version of IE that a client will need to use a web app built with gRPC-Web?

**Comment by stanley-cheung** [comment]
gRPC-Web was built using the Google Closure library so we support whatever browsers supported by the Google Closure library. Looks like some of the features might not work with IE8 or below. IE9 or newer should be fine.
