### ISSUE TITLE
VueJS + Grpc-Web "Module not found: Error: Can't resolve"

### ISSUE THREAD

**Issue by theobouwman** [grpc/grpc-web#431]
I've created a fresh VueJS application with TypeScript functionality.

When I generate using: 
```
protoc -I=. service.proto --js_out=import_style=typescript:. --grpc web_out=import_style=typescript,mode=grpcwebtext:.
```

I get the following files:
<img width="193" alt="screenshot 2019-01-06 at 16 37 46" src="https://user-images.githubusercontent.com/16098190/50738172-762cdf00-11d1-11e9-9fb8-273fba66802e.png">

When I move them to `src/_protos` in my VueJS project and try to `import { PlatformClient } from '@/_protos/ServiceServiceClientPb';` it gives me the following error:
```
Failed to compile.
./src/_protos/ServiceServiceClientPb.ts
Module not found: Error: Can't resolve './service_pb' in '/Users/theobouwman/dev/woodyshousing/woody_web/src/_protos'
```

Why is this?

**Comment by pumano** [comment]
looks like you not resolve it properly at typescript config? You use @ sign, it properly resolve path?

**Comment by theobouwman** [comment]
@pumano that resolves to `src/`

**Comment by eberkund** [comment]
I also have this issue, with and without `@` sign.

**Comment by stanley-cheung** [comment]
`--js_out=import_style=typescript:.`: this doesn't work. The message part of the .proto generated by `protoc --js_out=` only supports `import_style=commonjs` or `import_style=closure`. You need to use the former. 

`--grpc-web_out=import_style=typescript` will output a minimal set of typings for the messages in a `.d.ts` file.

**Comment by eberkund** [comment]
Thanks @stanley-cheung that fixed it for me

**Comment by theobouwman** [comment]
@stanley-cheung what do you mean with "You need to use the former."?

**Comment by eberkund** [comment]
>@stanley-cheung what do you mean with "You need to use the former."?

The `--js_out` parameter doesn't support `typescript` so what you actually want is:

```
protoc -I=. service.proto --js_out=import_style=commonjs:. --grpc web_out=import_style=typescript,mode=grpcwebtext:.
```

**Comment by jonas27** [comment]
just for clarification, the flag should be `--grpc-web_out`
