### ISSUE TITLE
Custom code generators

### ISSUE THREAD

**Issue by goodmind** [grpc/grpc-web#434]
Support custom code generators, without recompiling and hardcoding them in https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/grpc_generator.cc#L53

**Comment by Yannic** [comment]
I have an idea how this could work. However, it requires (possibly significant) changes to the architecture of the generator.

@stanley-cheung Can you comment on whether it is possible to do this without breaking google or maintaining two seperate generators.

**Comment by stanley-cheung** [comment]
It's like unlikely we have the bandwidth to support this in the near future.
