### ISSUE TITLE
CORS error using Go GRPC Gateway

### ISSUE THREAD

**Issue by eberkund** [grpc/grpc-web#435]
I have a Golang GRPC server on port 9090 and a proxy server using https://github.com/grpc-ecosystem/grpc-gateway on port 9191.

I generated TypeScript code from my `.proto` file using 

```
protoc -I=proto api.proto \
--js_out=import_style=commonjs:frontend/src/generated \
--grpc-web_out=import_style=typescript,mode=grpcwebtext:frontend/src/generated
```

However I get this error when I try to make requests

```javascript
    const url = new URL(window.location.href);
    url.protocol = 'http';
    url.port = '9191';

    // @ts-ignore
    const service = new PublicClient(url.href, {}, {
      // suppressCorsPreflight: true,
    });
    const request = new OpenFolderRequest();
    request.setPath('Hello');

    service.openFolder(request, {},
      (err: grpcWeb.Error, response: OpenFolderResponse) => {
        console.log(response);
        commit('setSession', p);
        commit('setFolder', response.getShotsList());
      });
```

```
Access to XMLHttpRequest at 'http://localhost:9191/#//api.Public/OpenFolder' from origin 'http://localhost:3984' has been blocked by CORS policy: Request header field x-user-agent is not allowed by Access-Control-Allow-Headers in preflight response.
```

When I enable `suppressCorsPreflight` then I no longer get CORS errors but then I get this weird query string when I make the request and a 404 error

![image](https://user-images.githubusercontent.com/4555959/51078255-79681500-1680-11e9-8f33-68cd49abebc5.png)

I am able to make regular HTTP JSON requests just fine.

**Comment by stanley-cheung** [comment]
I don't believe https://github.com/grpc-ecosystem/grpc-gateway  supports grpc-web. You need to use Envoy for that purpose.

**Comment by mojodevagentfour** [comment]
@stanley-cheung then, I can't call rest APIs from the browser, right?
