### ISSUE TITLE
protoc-gen-grpc-web-1.0.3-windows-x86_64.exe  for window users

### ISSUE THREAD

**Issue by extremety1989** [grpc/grpc-web#438]
i downloaded protoc-gen-grpc-web-1.0.3-windows-x86_64.exe and renamed it as protoc.exe , then i tried to run 

protoc -I=. echo.proto \ --js_out=import_style=commonjs:. \ --grpc-web_out=import_style=commonjs,mode=grpcwebtext:.
protoc: Unknown option: -I=.

i get the error Unknown option: -I=.

**Comment by stanley-cheung** [comment]
You need to download protoc.exe separately from the protobuf releases page https://github.com/protocolbuffers/protobuf/releases
