### ISSUE TITLE
Error code: 14 "Http response at 400 or 500 level" 

### ISSUE THREAD

**Issue by extremety1989** [grpc/grpc-web#439]
webpack generated client.js code,  node server !

**Comment by pumano** [comment]
it's envoy error, when your backend not available

**Comment by extremety1989** [comment]
> 
> 
> it's envoy error, when your backend not available

yes because i run  " node server.js " envoy.yml cannot be executed with node ?

**Comment by heiy** [comment]
how to settled this question
