### ISSUE TITLE
enhencement to well-known type in typescript

### ISSUE THREAD

**Issue by jmzwcn** [grpc/grpc-web#443]
import * as google_protobuf_any_pb from "./google/protobuf/any_pb";
import * as google_protobuf_api_pb from "./google/protobuf/api_pb";
import * as google_protobuf_descriptor_pb from "./google/protobuf/descriptor_pb";
import * as google_protobuf_duration_pb from "./google/protobuf/duration_pb";
import * as google_protobuf_empty_pb from "./google/protobuf/empty_pb";
import * as google_protobuf_field_mask_pb from "./google/protobuf/field_mask_pb";
import * as google_protobuf_source_context_pb from "./google/protobuf/source_context_pb";
import * as google_protobuf_struct_pb from "./google/protobuf/struct_pb";
import * as google_protobuf_timestamp_pb from "./google/protobuf/timestamp_pb";
import * as google_protobuf_type_pb from "./google/protobuf/type_pb";
import * as google_protobuf_wrappers_pb from "./google/protobuf/wrappers_pb";

e.g:
https://www.npmjs.com/package/@types/google-protobuf

**Comment by shaxbee** [comment]
Well-known types are already being imported in generated typings on master.

**Comment by jmzwcn** [comment]
I saw it, but I find generated well-konwn type in each *.d.ts and have a bit difference from ./google/protobuf/***, e.g:timestamp.toDate()/fromDate(), it don't have convenience like @types/google-protobuf/***.

**Comment by shaxbee** [comment]
If you generate using plugin build from master well-known types are no longer included in .d.ts - see https://github.com/shaxbee/grpc-web-dts-example/blob/master/master/example/example_pb.d.ts

**Comment by jmzwcn** [comment]
Yes, it has been improved in master build. thanks!
