### ISSUE TITLE
Hello World demo has minor bugs that cause breaking issues

### ISSUE THREAD

**Issue by diericx** [grpc/grpc-web#449]
I spent a while tonight trying to get the Hello World demo to work and after scouring the issues it came down to 2 simple edits. I would create a PR but I don't have permission to so I'll post the edits here.  
For anyone else searching the error I was getting was  
`upstream connect error or disconnect/reset before headers`

The envoy yaml is broken right now. Instead of localhost the socket_address should be changed to this:  
`address: host.docker.internal`  

In the [Readme](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld) at the very bottom the line to run the envoy container should be changed from  
`docker run -d -p 8080:8080 --network=host helloworld/envoy`  
to  
`docker run -d -p 8080:8080 helloworld/envoy`  

After these minor changes everything works perfectly! :)

**Comment by stanley-cheung** [comment]
Which OS are you trying to run the docker image from?

**Comment by diericx** [comment]
> Which OS are you trying to run the docker image from?

MacOS High Sierra 10.13.6

**Comment by stanley-cheung** [comment]
Yea unfortunately `host.docker.internal` only works on Mac but not on Linux. We are aware of this and probably should add a documentation note somewhere. So yes the out-of-the-box docker image basically only works on Linux for now. I wish `host.docker.internal` would work on Linux then it will simplify lives a lot :)
