### ISSUE TITLE
please release 1.0.4 with the latest 31 commit?

### ISSUE THREAD

**Issue by jmzwcn** [grpc/grpc-web#463]
please release 1.0.4 with the latest 31 commit, otherwise we have to build it with all dependencies.

**Comment by TBoshoven** [comment]
This has been discussed in #456 . Looks like it's being worked on, just taking a really long time.

**Comment by stanley-cheung** [comment]
Yea thanks for pinging. As of right now, all the relevant code are in sync between here and our internal code base. (Yay!) And all tests are passing both here and internally. 

There are still a few pending PRs that I'll need contributors to rebase and get those in as well. 

But just to tell everyone that we are definitely chucking along :)

**Comment by TBoshoven** [comment]
@stanley-cheung is there any new progress on this?

**Comment by stanley-cheung** [comment]
`1.0.4` has just been released. https://github.com/grpc/grpc-web/releases Please check that out. Thanks.

**Comment by jmzwcn** [comment]
congratulations!

**Comment by TBoshoven** [comment]
Awesome. I could get rid of my workaround :)
