### ISSUE TITLE
grpc-web should warn when the Content-Type of a response is not supported

### ISSUE THREAD

**Issue by hach-que** [grpc/grpc-web#466]
We started using grpc-web on the client with the https://github.com/improbable-eng/grpc-web/tree/master/go/grpcweb Go package, and all of our requests would just hang, without any logging or error messages.

It turns out that the Go package sets the Content-Type to be "application/grpc-web+proto", which isn't any of the handled Content-Types in this code here: https://github.com/grpc/grpc-web/blob/bb3624ea8d014dae0a7ed120ae94fac29eddae7c/javascript/net/grpc/web/grpcwebclientreadablestream.js#L132-L144

When this happens, the callback simply never fires, even when the response is complete. Instead, if the Content-Type isn't recognized, an error should be propagated to the caller so this issue can be identified faster.

**Comment by hach-que** [comment]
Okay it looks like our server is actually responding with Content-Type `text/plain` or `application/octet-stream` depending on whether `grpcweb` or `grpcwebtext` mode is used, but still, the client library should propagate an error.

**Comment by stanley-cheung** [comment]
This should be fixed in `1.2.0`
