### ISSUE TITLE
ReactJs issues with grpc-web using go backend

### ISSUE THREAD

**Issue by Emixam23** [grpc/grpc-web#473]
Hey !

I am trying to use `grpc-web` in order to connect my react js app to my golang backend. However, i get stuck again and again, even before achieving a simple step.. I am coming today because I would like a huge clearification about how to use `grpc-web` with **React Js**.

Let say I have this protobuf file:

    syntax = "proto3";

	package stub_v1_API_web_service;

	import "google/api/annotations.proto";

	option go_package = "stub_v1_API_web_service";

	//
	// The API web service definition.
	//

	service API_WebService {
		rpc SayHello (SayHelloRequest) returns (SayHelloResponse) { option (google.api.http) = { post: "/say_hello" body:"*" }; }
	}

	//
	// API web service parameters/returns data definition.
	//

	message SayHelloRequest {
		User User = 1;
	}

	message SayHelloResponse {
		string response = 1;
	}

	// Models

	message User {
		string Firstname = 1;
		string Lastname = 2;
		int Sexe = 3;
	}

As you can see in this file (which is the one used by the API), you have an `option`. As you can see, this is an HTTP option that makes me able to make a REST request. However, for it, I need to import `"google/api/annotations.proto"`. In Golang my files got generated perfectly and everything works fine (I have multiple services that communicates throughout gRPC exchanges and everything works). However for ReactJs... It's another story.. First, annotation and the options make the protofile invalid so I created a script that removes these parts and I get the following:

    syntax = "proto3";

	package stub_v1_API_web_service;

	

	option go_package = "stub_v1_API_web_service";

	//
	// The API web service definition.
	//

	service API_WebService {
		rpc SayHello (SayHelloRequest) returns (SayHelloResponse) {  }
	}

	//
	// API web service parameters/returns data definition.
	//

	message SayHelloRequest {
		User User = 1;
	}

	message SayHelloResponse {
		string response = 1;
	}

	// Models

	message User {
		string Firstname = 1;
		string Lastname = 2;
		int Sexe = 3;
	}

**First Question: ***If I have different protofile (I mean like the one above, without the import and the google http option), will it work still? I ask that because I saw that there is a file descriptor by the end of the generated file (on the golang side) so I was wondering for reactjs if it was a possible issue?*

From this file, I can then generated multiple files from the following commands (the interesting part is only the last one but I felt that some details could help. This comes from a "script.sh" a wrote based on https://github.com/grpc/grpc-web#client-configuration-options): 

```
###########################
### API stub generation ###
###########################

echo ""

# import the base protofile from the API
cp ${sub_proto_folder}/${sub_proto} ${protoDir};

# take out the parts that are useless for react (and that create errors)
inner_replace_import_annotation ${protoDir} ${sub_proto}
inner_replace_options ${protoDir} ${sub_proto}

# generate the stub
protoc -I=${protoDir} ${sub_proto} --js_out=import_style=commonjs,binary:${outputDir} --plugin=protoc-gen-grpc-web=${protoGenGrpcWeb} --grpc-web_out=import_style=commonjs,mode=grpcwebtext:${outputDir}
```

> Generated files:
> api_web_service_grpc_web_pb.js
> api_web_service_pb.js
> sayhellorequest.js
> sayhelloresponse.js
> user.js

Now, the first errors I get (following the same logic as https://github.com/grpc/grpc-web#typescript-support) are:

> ./src/api_stub/sayhellorequest.js
>  Line 10:    'goog' is not defined      no-undef
>  Line 11:    'goog' is not defined      no-undef
>  Line 12:    'goog' is not defined      no-undef
>  Line 13:    'goog' is not defined      no-undef
>  Line 15:    'goog' is not defined      no-undef
>  Line 28:    'proto' is not defined     no-undef
>  Line 29:    'jspb' is not defined      no-undef
>  Line 31:    .........

From this I began to search on internet and found some questions/answers that were mentioning to add `/* eslint-disable */` by the beginning of each generated files.

However, to be honest, it seems totally broken to me if I can say so... But anyway, I add this and.. **HERE WE GO AGAIN..**

**ReferenceError: goog is not defined**
./src/api_stub/sayhellorequest.js
*src/api_stub/sayhellorequest.js:12*

The first lines of this file are:

```
/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.stub_v1_API_web_service.SayHelloRequest'); // <--- **ReferenceError: goog is not defined**

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.stub_v1_API_web_service.User');

// ........
```

I first tried to exchange this line with the `goog.require('jspb.BinaryReader');` line but the errors hits for the same reason this new first line...

I am pretty new to ReactJs but... I think even new or not, it's so complicated to put everything together.. To reach that points it took me a couple of days of my free time and I still can't move forward and I don't even get what are those errors about..

To me, it should be like in golang or android.. I generate the file and it works :( 

Hope I am clear enough on the details of the situation. Feel free to ask for more, thanks in advance for any help !

Max

**Comment by clehene** [comment]
@Emixam23 indeed, I'd label the library as alpha / experimental.
Before diving in, you may want to check out https://github.com/improbable-eng/grpc-web which is more mature. Some context here https://grpc.io/blog/state-of-grpc-web. Otherwise it's a bumpy road that I'm also wasting time with.

For some reason, annotations are not part of core protobuf / grpc definitions.
They are part of 
https://github.com/googleapis/googleapis

Likely your go code has a dependency on a library that provides those - see https://github.com/googleapis/api-common-protos (this copies them from googleapis)

> Note however that the node.js lib referenced in api-common-protos - https://www.npmjs.com/package/google-proto-files doesn't actually have the `.js` files, only `.proto`. Instead it assumes https://github.com/dcodeIO/protobuf.js/  

Basically you need to have them at compile time (e.g. `protoc -I=/usr/local/include` or a path that has the `google/api/annotations.proto`) in order to resolve the .proto imports **and** at runtime to resolve the imports in .js. 

I was trying to get this fixed through a npm package (note, my first npm package..) 
https://www.npmjs.com/package/proto-google-common-protos

However, once generating the files, they will import annotations with a relative path

```
var google_api_annotations_pb = require('./google/api/annotations_pb.js');
```
So depending on a npm package doesn't quite work. Again, not a JS programmer and barely knowing npm, I assume it won't out of the box, so you'd have to relocate the .js files. 

Here's the generator code that handles the case
https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/grpc_generator.cc#L334-L342

So long story short, you can generate the `.js` for the common protos (or get them from the npm package above) and have them available for imports by the generated code if you want to get it working.

**Comment by longfellowone** [comment]
Hi Max, I have put together a small sample application using ReactJS and Golang you can checkout here. 

https://github.com/longfellowone/grpcwebtest

Maybe this will help!

**Comment by Emixam23** [comment]
Hey :) Getting back on it with React TypeScript (and to be honest, typescript approach is way easier for me to understand than full js). So now that I generated the typescript output of the protobuf file, I am still missing the file so I will investigate based on your answers
