### ISSUE TITLE
d.ts file inclusion in Angular 6 Typescript

### ISSUE THREAD

**Issue by rkorebrits** [grpc/grpc-web#484]
We are having issues trying to include the generated declarations into our Angular (multi-application) project. We are using the following to generate the `d.ts` and `js` files (do we need both?), which works fine.

	protoc  --proto_path=${GOPATH}/sharedproto \
		--grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:${GOPATH}/web/upgrade/projects/common/src/lib/models/sharedproto \
		--js_out=import_style=commonjs:${GOPATH}/web/upgrade/projects/common/src/lib/models/sharedproto \
		target/sample.proto target/etc.proto

However, when we now try and import the generated file, like:

    import { ResultScreen } from 'common/models/sharedproto/wallet/result_pb.d';

We get the following error:

	ERROR in ../common/src/lib/models/sharedproto/wallet/result_pb.d.ts
	Module build failed: Error: /Users/rkorebrits/workspace/core/web/upgrade/projects/common/src/lib/models/sharedproto/wallet/result_pb.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
	    at AngularCompilerPlugin.getCompiledFile (/Users/rkorebrits/workspace/core/web/upgrade/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:749:23)
	    at plugin.done.then (/Users/rkorebrits/workspace/core/web/upgrade/node_modules/@ngtools/webpack/src/loader.js:41:31)
	    at process._tickCallback (internal/process/next_tick.js:68:7)

What is the right way to include the files in Typescript (Angular 6)

**Comment by jonahbron** [comment]
The `*.d.ts` files contain only type definitions for the contents of the `*.js` files.  You do need both.

Together, the `.js` and `.d.ts` files together behave just like a `.ts` file as far as the module system is concerned.  So the correct way to import is:

    
import { ResultScreen } from 'common/models/sharedproto/wallet/result_pb';

**Comment by rkorebrits** [comment]
Thanks for the quick reply @jonahbron! I've got it working now, however I'm just curious about the properties vs. getters and setters. I see that the javascript has these getters and setters in the code, but we are currently not including the JavaScript, so the getters and setters and not available on runtime. Instead we are using `const data = Request.AsObject = {...}` and `onQuery(res: Response.AsObject) {` to make the code work. Is this the recommended approach, or should we be including the javascript and use the getters and setters?
