### ISSUE TITLE
Async await + Vue.js

### ISSUE THREAD

**Issue by irvdev** [grpc/grpc-web#485]
Hello! 

I want to use async/await in my project. I want to avoid using callback

For example:

`const result = await client.method()`
`if (result.err) { return result.err }`
`if (result.response) { return result.response }`

Can I use async/await?

Thanks!

**Comment by AndreFrelicot** [comment]
Hello, 
do you have a solution for this ? is async await supported out of the box ?

thanks

**Comment by irvdev** [comment]
Hello. Yes. You need to initialize promise client
