### ISSUE TITLE
Generated TypeScript typings should extend google-protobuf typings

### ISSUE THREAD

**Issue by neilcarpenter** [grpc/grpc-web#488]
Currently typings generated for proto `message`s only include getters/setters to proto message fields, but do not include typings for inherited methods from `jspb.Message`, resulting in TypeScript compiler errors when trying to use `Message` methods.

Discovered this when trying to  use `Message.clone()`.

**Comment by stanley-cheung** [comment]
I believe this is fixed in `master` via #444

**Comment by stanley-cheung** [comment]
This should be fixed in release `1.0.4`.
