### ISSUE TITLE
Feedback for grpc-web (multiple things :)

### ISSUE THREAD

**Issue by buehler** [grpc/grpc-web#489]
Hey there!

First, I'd like to thank you for creating this project, it's very convenient to access proto generated elements from the web directly.

Since I'm a web-engineer and a very happy user of typescript (with angular, react and other frameworks) I'd like to give my feedback here.

If requested / required I'm gladly creating single issues out of my points below and would be happy to help implement some of the proposed elements.

### CI / CD
This is a small but very important part IMO. I'd suggest the usage of `semantic-release` since it enables the repository to release on each merge into the master branch. This is requested by other issues here as well.
[semantic-release](https://github.com/semantic-release/semantic-release) could solve some of those problems.

### grpc-web
The normal base code `grpc-web` is nice, so the used client to communicate with the envoy proxy isch easy to use. Maybe it could be a good idea to rewrite the client in typescript? Then the support would be given by free and all the features that come with it.

The generated elements don't have the correct constructors with them, so while a `User` message does contain a constructor (not in typescript / dts but in the generated code), a map does not.

```proto
message User {
  map<string, string> ...
}
```

This does generate a user object with the `setXXX` for the map element list. But the effective type `ElementEntry` is not created. So there is no chance to actually use this feature of proto.

The generated objects could support method chaining, meaning that the given message
```proto
message Test {
  string a = 1;
  string b = 2;
}
```

Could generate the following TS / JS code: 
```javascript
class Test {
  setA(a) {
    // the grpc client magic to set value of a;;
    return this;
  }
}
```

Also this could (in TS) be supported by properties:
```typescript
class Test {
  public get a(): string {
    return this.getA();
  }
  public set a(value: string) }
    this.setA(value);
  }
}
```

I'd be happy to help to implement this package in typescript or other things... just need some feedback for it ;-)

**Comment by jmzwcn** [comment]
Yes, we need CI/CD to the latest binary.

**Comment by stanley-cheung** [comment]
There had been some discussion before about rewriting the client in TypeScript in #405. Unfortunately since our internal use case + build system is heavily tied to the Google Closure library, it would be hard for us to maintain two separate implementations. There would also be a challenge because the current implementation is built on top of the Google Closure `goog.net.streams` library, mainly on the parser and calling into the http stack.

Yes we will definitely looking into semantic-release for the plugin and npm package side of things.
