### ISSUE TITLE
Map deserialize binary AssertionError

### ISSUE THREAD

**Issue by ivan-sysoi** [grpc/grpc-web#49]
I have added map field to [echo.proto](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/echo.proto).
When map key or value is 0 or False respectively, request callback is not called and no any exceptions appear in the console.

After adding try catch in `grpc.web.ClientReadableStream.prototype.on` I get `goog.asserts.AssertionError` in the `jspb.Map.deserializeBinary`.

Proto:
```
syntax = "proto3";

message EchoResponse {
  string message = 1;
  int32 message_count = 2;
  map<int32, bool> map = 3;
}
service EchoService {
  rpc Echo(EchoRequest) returns (EchoResponse);
}
```

Server:
```
class EchoServiceServicer(echo_pb2.EchoServiceServicer):
    def Echo(self, request, context):
        data = {
            'message': 'Hello %s' % request.message,
            'message_count': 1,
            'map': {0: True} 
        }
        request = echo_pb2.EchoResponse(**data)
        return request
...
```

Thanks.

**Comment by Michael-F-Bryan** [comment]
> Closing this as this is a JS protobuf issue.

@stanley-cheung, do you know if an issue was made upstream? I believe I'm running into this issue where serializing a `map<uint32, bool>` from binary will fail with an `AssertionError`.

In my case if the server returns `{0: true}` it'll get through to the JavaScript code just fine, but when you return more than one item (i.e. `{0: true, 2: false}`) the assertion will be triggered.

```
uncaught exception: AssertionError: Assertion failed google-protobuf.js:81
    DEFAULT_ERROR_HANDLER google-protobuf.js:81
    doAssertFailure_ google-protobuf.js:82
    assert google-protobuf.js:83
    deserializeBinary google-protobuf.js:411
    deserializeBinaryFromReader server_pb.js:588
    readMessage google-protobuf.js:384
    deserializeBinaryFromReader server_pb.js:587
    readMessage google-protobuf.js:384
    deserializeBinaryFromReader server_pb.js:440
    deserializeBinary server_pb.js:420
    Y index.js:49
    Bb index.js:34
    N index.js:33
    fc index.js:41
    N index.js:40
    K index.js:40
    <anonymous> self-hosted:844
```
