### ISSUE TITLE
how to config protoc-gen-grpc-web-1.0.3-windows

### ISSUE THREAD

**Issue by MonkeyDBean** [grpc/grpc-web#490]

**Comment by weilip1803** [comment]
Does not work with windows yet.

**Comment by MonkeyDBean** [comment]
as follows, it's ok:
protoc ./helloworld.proto --js_out=import_style=commonjs,binary:.

and as follows, it's wrong:
protoc ./helloworld.proto --grpc-web_out=import_style=commonjs,mode=grpcwebtext:.
cmd shows
--grpc-web_out: protoc-gen-grpc-web: Plugin failed with status code 1

**Comment by MonkeyDBean** [comment]
> Does not work with windows yet.

protoc-gen-grpc-web-1.0.3-windows-x86_64.exe has published, it's useless?

**Comment by weilip1803** [comment]
Refer to this issue. https://github.com/grpc/grpc-web/issues/342

**Comment by MonkeyDBean** [comment]
protoc -help
find no --grpc-web_out

and  protoc --version is libprotoc 3.7.0

**Comment by stanley-cheung** [comment]
You can specify where to find the plugin by adding a flag like `--plugin=protoc-gen-grpc-web=<path to protoc-gen-grpc-web>`

**Comment by MonkeyDBean** [comment]
> You can specify where to find the plugin by adding a flag like `--plugin=protoc-gen-grpc-web=<path to protoc-gen-grpc-web>`

thank you!@stanley-cheung , it works

**Comment by martinwangen** [comment]
I had the same issue. tried adding the flag:

$ protoc ./helloworld.proto --grpc-web_out=import_style=commonjs,mode=grpcwebtext:. --plugin=protoc-gen-grpc-web=C:\Program Files (x86)\Protoc\protoc-gen-grpc-web\protoc-gen-grpc-web-1.0.4-windows-x86_64.exe

terminal shows:
Files: No such file or directory
