### ISSUE TITLE
error:client is not a constructor

### ISSUE THREAD

**Issue by MonkeyDBean** [grpc/grpc-web#491]
var echoService = new proto.mypackage.EchoServiceClient(
  'http://localhost:8080');

errors: Uncaught TypeError: proto.mypackage.EchoServiceClient is not a constructor

what's wrong?

**Comment by willks** [comment]
I ran into this issue as well. Have not been able to solve this at all.

Looks like grpc-web is just too experimental for Typescript - definitely not GA yet.

**Comment by stanley-cheung** [comment]
Please provide more information. Are you missing some sort of `require()` statements?

**Comment by MonkeyDBean** [comment]
> Please provide more information. Are you missing some sort of `require()` statements?

ok, I did it for test : https://github.com/MonkeyDBean/BeanLaboratory/blob/master/HelloGrpc/src/test/note.md

I required two statements, maybe missing some parts, a little puzzled
