### ISSUE TITLE
import_style=typescript generates code in Src and src folder

### ISSUE THREAD

**Issue by Liu-Kai-1991** [grpc/grpc-web#496]
I take the helloworld.proto from the example folder, put it in my project /src/main/proto/helloworld.proto,
In client/app/ ,I ran:

protoc -I=../ ../src/main/proto/helloworld.proto --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:./proto

Got file
client/app/proto/Src/main/proto/helloworldServiceClientPb.ts
client/app/proto/src/main/proto/helloworld_pb.d.ts

note that one is in Src and one is in src

 @Liu-Kai-1991

**Comment by Liu-Kai-1991** [comment]
I take the helloworld.proto from the example folder.

And I ran:

protoc -I=../ ../src/main/proto/helloworld.proto --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:./proto

Got file 
/proto/Src/main/proto/helloworldServiceClientPb.ts
/proto/src/main/proto/helloworld_pb.d.ts

note that one is in  Src and one is in src

**Comment by ridhozhr10** [comment]
have you already test it in recent version, mine working fine in v1.0.4

**Comment by ridhozhr10** [comment]
command used 
```
protoc -I=. ./src/main/proto/echo.proto \
--grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:./proto
```
output : 
```
ls -l proto/src/main/proto/     
total 12
-rw-rw-r-- 1 ridho ridho  803 Mar 23 19:43 echo_grpc_web_pb.d.ts
-rw-rw-r-- 1 ridho ridho 3182 Mar 23 19:43 echo_grpc_web_pb.js
-rw-rw-r-- 1 ridho ridho 1300 Mar 23 19:43 echo_pb.d.ts
```
