### ISSUE TITLE
Unable to test and use the grpc-web call using nginx proxy.

### ISSUE THREAD

**Issue by vinthedark** [grpc/grpc-web#503]
Hi Team, 

I understand that grpc-web doesn't work with latest version of nginx.

In that regards, I followed the [guide](https://github.com/grpc/grpc-web/issues/381) to build the [docker image](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/nginx/Dockerfile) but i wasnt able to find the mentioned image in the [Docker Hub](https://hub.docker.com/u/grpcweb). Also based on the comment of @stanley-cheung, i tried to tweak the mentioned [nginx file](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/nginx.conf#L24) according to the need and tried. 

Getting the below error.

`*1 upstream rejected request with error 2 while reading response header from upstream, client: `

Any guide or steps on how to go about it would be helpful.

**Comment by stanley-cheung** [comment]
You can build the nginx proxy by running the following:

```
$ docker-compose -f advanced.yml up echo-server nginx commonjs-client
```

And then open `localhost:8081/echotest.html`.

**Comment by vinthedark** [comment]
The shared echo-server is running fine, but when i changed the grpc_pass to point my server, it is throwing bad request error. Are there any other configuration changes that needs to be done along with changing the grpc_pass parameter?

**Comment by uqee** [comment]
> You can build the nginx proxy by running the following:
> 
> ```
> $ docker-compose -f advanced.yml up echo-server nginx commonjs-client
> ```
> 
> And then open `localhost:8081/echotest.html`.

According to [this](https://github.com/grpc/grpc-web/commit/781f53da9472d2519c510f0cddb8d7ed1ea82476#diff-04c6e90faac2675aa89e2176d2eec7d8R314) it should now be

```
$ docker-compose up echo-server nginx commonjs-client
```

bit it fails for me anyway.
