### ISSUE TITLE
Migrate Bazel rule to toolchain

### ISSUE THREAD

**Issue by Yannic** [grpc/grpc-web#507]
I'm planning to change the implementation of `closure_grpc_web_library` to use Bazel's support for [toolchains](https://docs.bazel.build/versions/master/toolchains.html) instead of hard-coding the compiler and runtime. This will give users more flexibility in how they can configure and use that rule.
For example: Assuming Google Open-Sources their JSON-like wire format or one of those alternative modes ([1](https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/grpc_generator.cc#L49)), if someone wants to switch to that, they have to update every `closure_grpc_web_library`-target. When the configuration is passed as a toolchain, it's sufficient to tell Bazel to use that new toolchain, and updating individual targets is no longer required.

On the downside, this might be considered to be a breaking change because it will require a trivial (but manual) addition to the `WORKSPACE` file to register the (default) toolchain.
See [rules_go](https://github.com/bazelbuild/rules_go#setup) for an example of what that would look like.

Let me know if there are any concerns regarding this change.

**Comment by Yannic** [comment]
Additionally, I'd like to propose that we ask for grpc-web to be added to Bazel's [CI system](https://github.com/bazelbuild/continuous-integration). That way, we will be notified if there are any breaking changes instead of periodically checking whether everything is still fine (#501, #494).
@stanley-cheung WDYT?

**Comment by Yannic** [comment]
Since there hasn't been any feedback on this, I'll assume that everyone is happy with the changes proposed here.
I'll create a PR implementing this soon (TM).

**Comment by sampajano** [comment]
Hi :) Closing due to being obsolescence — `closure_grpc_web_library` was cleaned up #1138. Thanks for the contributions, Yannic :)
