### ISSUE TITLE
Building protoc-gen-grpc-web plugin on Windows failed

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc-web#510]
I was trying to build the `protoc-gen-grpc-web` plugin on Windows ahead of the 1.0.4 release and I got error when trying to compile the plugin via `bazel` (like we did for 1.0.3, same process)

```
stanleycheung@stanleycheung-windows2 MSYS /c/Users/stanleycheung/grpc-web
$ bazel build javascript/net/grpc/web:protoc-gen-grpc-web
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
ERROR: C:/users/stanleycheung/_bazel_stanleycheung/lddznicz/external/io_bazel_rules_closure/closure/protobuf/closure_proto_library.bzl:66:21: name 'ProtoInfo' is not defined (did you mean 'protos'?)
ERROR: error loading package '': Extension 'closure/protobuf/closure_proto_library.bzl' has errors
ERROR: error loading package '': Extension 'closure/protobuf/closure_proto_library.bzl' has errors
INFO: Elapsed time: 5.473s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by stanley-cheung** [comment]
@Yannic FYI

**Comment by stanley-cheung** [comment]
Bah - 
```
$ bazel version
Starting local Bazel server and connecting to it...
Build label: 0.19.2
```

Upgrading bazel ....

**Comment by stanley-cheung** [comment]
Works now

**Comment by user-ZJ** [comment]
Hi, I also have this problem. How did you solve it.Thanks

**Comment by user-ZJ** [comment]
> Hi, I also have this problem. How did you solve it.Thanks

update bazel, I solve this problem

**Comment by navono** [comment]
how to use `protoc-gen-grpc-web` in proto project with bazel to produce generated file like `*.pb.go` or `*.d.ts`?

**Comment by venuswu** [comment]
> Bah -
> ```
> $ bazel version
> Starting local Bazel server and connecting to it...
> Build label: 0.19.2
> ``` 
> Upgrading bazel ....

What's the version of bazel to solve this problem ?
