### ISSUE TITLE
Question: Use with flatbuffers?

### ISSUE THREAD

**Issue by shaunc** [grpc/grpc-web#515]
While grpc itself allows flatbuffers usage, this seems very wedded to protobuf. It it possible to use with flatbuffers? We are designing a web visualization tool that is to connect to services that currently use flatbuffers (but not grpc). 

Although protobuf is more compressible, we wanted to use flatbuffers because we hoped to keep the data structures compressed in the browser, and worry about browser memory if we need to expand them. (Also our data changes infrequently -- flatbuffers can be stored in local memory on the client which mitigates slower transmission.)

**Comment by stanley-cheung** [comment]
Not right now. We will keep this in mind for the future.
