### ISSUE TITLE
Unable to install protoc-gen-grpc-web (Windows 10 Pro)

### ISSUE THREAD

**Issue by jpreese** [grpc/grpc-web#516]
Every time I run the executable to install grpc-web, it just seems to do nothing. I've waited for quite some time, and the screen remains blank. 

I've tried versions 1.0.4 and 1.0.3 of the executables on the releases page.

![image](https://user-images.githubusercontent.com/6980197/54861823-e80fc180-4d06-11e9-9b2f-1c9a724b6e4e.png)

**Comment by ridhozhr10** [comment]
in linux it behave like this too, but when you use it with protoc command it should work just fine..
just make sure protoc-gen-grpc-web is already in your $PATH variable and running something like 
```
$ protoc -I=$DIR echo.proto \
--js_out=import_style=commonjs:$OUT_DIR \
--grpc-web_out=import_style=commonjs,mode=grpcwebtext:$OUT_DIR
```
should work fine

**Comment by jpreese** [comment]
Yep! Thanks.

I could've swore I saw somewhere saying to download the installer and I landed there. So I assumed the exe was actually an installer and not the plugin itself. Added it to the PATH and it's fine.

**Comment by ridhozhr10** [comment]
well perhaps it will be nice tho to have exe installer so you doesnt need to setup the path manually haha.
well, glad it working for you :+1:

**Comment by stanley-cheung** [comment]
The `protoc-gen-grpc-web` is meant to be a *plugin* to the main `protoc` tool (and true to all other gRPC languages). So yes, running the `protoc-gen-grpc-web` plugin itself will do nothing. 

See the main documentation here: https://github.com/grpc/grpc-web#code-generator-plugin

I hope that all our gRPC-Web documentation around the plugin will be in the form of `protoc --js_out=.... --grpc-web_out=...`. If there's a piece of documentation out there about using `protoc-gen-grpc-web` standalone, it's almost certainly incorrect and please let us know.

**Comment by jpreese** [comment]
@stanley-cheung nope I think it was on me, or at least how I interpreted some previous comments (install vs. download).

I eventually got everything up and running and got my first application up and running with grpc-web! https://github.com/jpreese/grpc-catfact 👍
