### ISSUE TITLE
c.toArray is not a function when setting message to an object

### ISSUE THREAD

**Issue by barrymichaeldoyle** [grpc/grpc-web#532]
I have the following request that crashes whenever I set it's value to an object. But the object is the required input for that request :/

See this:

```
const request = new PricingMethodRequest()
request.setFromDate({ nanos: 0, seconds: 1555064508 }) // <--- Crashes on this line
```

How do I sort this out?

[More detailed SO question here](https://stackoverflow.com/questions/55630469/grpc-web-c-toarray-is-not-a-function-when-setting-a-date-value-on-my-request)

**Comment by stanley-cheung** [comment]
Can you share the .proto please? What's the definition of that message?

**Comment by ktm-labs** [comment]
It looks like this has been resolved at SO.

"It turns out I had to create a Timestamp type for the fromDate."

@barrymichaeldoyle does this seem to be resolved for you?

**Comment by barrymichaeldoyle** [comment]
Yeah it's resolved thanks.
