### ISSUE TITLE
goog.AssertError on go `nil` element in map

### ISSUE THREAD

**Issue by RXminuS** [grpc/grpc-web#533]
We just had a really hard to detect bug. If you have a `map<string, MapItem>` in your proto then the Go structure becomes a `map[string]*MapItem`. This means that in Go you can do `map["id-1"] = nil` but this will crash grpc-web if you send this data to the client.

I've tried it with both commonjs+dts as well as Typescript, and grpcweb and grpcwebtext. The problem is consistent across the board. We are using the envoy grpc-web filter in Ambassador 0.53.

I saw there was a discussion already about getting rid of the internal asserts and making sure that even in extreme cases the error handler is called, so I won't discuss that further here. But hopefully, this bug can be solved.

**Comment by RXminuS** [comment]
Oh, I think this might be related! https://github.com/grpc/grpc-web/issues/49 . But given that the issue was first raised over a year ago...maybe having it closed and pushing to protojs hasn't been the right approach? Can we at least link the issue at protojs here and keep both open?

**Comment by stanley-cheung** [comment]
Looks like it's https://github.com/protocolbuffers/protobuf/issues/4500?
