### ISSUE TITLE
Getting Bad request error when nginx is made to point to my service.

### ISSUE THREAD

**Issue by vinthedark** [grpc/grpc-web#534]
The shared echo-server is running fine, but when i changed the grpc_pass to point my server, it is throwing bad request error. Are there any other configuration changes that needs to be done along with changing the grpc_pass parameter?

_Originally posted by @vinthedark in https://github.com/grpc/grpc-web/issues/503#issuecomment-482442816_

**Comment by orchie** [comment]
> The shared echo-server is running fine, but when i changed the grpc_pass to point my server, it is throwing bad request error. Are there any other configuration changes that needs to be done along with changing the grpc_pass parameter?
> 
> _Originally posted by @vinthedark in [#503 (comment)](https://github.com/grpc/grpc-web/issues/503#issuecomment-482442816)_

Do you resolve this? 
I met the same error with you,and try to do everything I can find but no success.  #622 
thanks of all !

**Comment by stanley-cheung** [comment]
Sorry I have to declare Bug Bankrupcy on some of these older issues. If this is still an issue, please open a new one.
