### ISSUE TITLE
Simple typescript example won't compile

### ISSUE THREAD

**Issue by AndreFrelicot** [grpc/grpc-web#539]
Hello,

I generated the code with :

`protoc -I protos ./protos/helloworld.proto --js_out=import_style=typescript:./jsproto --grpc-web_out=import_style=typescript,mode=grpcwebtext:./jsproto`

TypeScript tsc: 3.4.1
libprotoc 3.7.0

sample source: https://github.com/AndreFrelicot/grpc-web-typescript-vuejs

Proto used: https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto

Error: 
```
ERROR in /home/andre/grpc-web-typescript-vuejs/src/HelloworldServiceClientPb.ts
39:5 Argument of type '(bytes: Uint8Array) => HelloReply' is not assignable to parameter of type '(bytes: {}) => HelloReply'.
  Types of parameters 'bytes' and 'bytes' are incompatible.
    Type '{}' is missing the following properties from type 'Uint8Array': BYTES_PER_ELEMENT, buffer, byteLength, byteOffset, and 26 more.
    37 |       return request.serializeBinary();
    38 |     },
  > 39 |     HelloReply.deserializeBinary;
       |     ^
    40 |   );
    41 | 
    42 |   sayHello(

```

thank you

**Comment by sergey-shambir** [comment]
PR #537 should fix the issue

**Comment by stanley-cheung** [comment]
See the comment [here](https://github.com/grpc/grpc-web/issues/431#issuecomment-453328164). 

`--js_out=import_style=typescript` is not a valid option. `--js_out=import_style=` only support `import_style=commonjs` or `import_style=closure`. You probably want to use `import_style=commonjs`.

**Comment by AndreFrelicot** [comment]
Thank you it works.

do you have a hint on how to generate the typescript code with PromiseClient support ? I don't see how in the documentation.

**Comment by AndreFrelicot** [comment]
Got it, I should generate with commonjs+dts, the typescript generator don't handle PromiseClient for now.

`protoc helloworld.proto --js_out=import_style=commonjs:./src/ --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:./src/
`
