### ISSUE TITLE
How to store private data on the client side?

### ISSUE THREAD

**Issue by wangh09** [grpc/grpc-web#541]
Sorry, this question was asked in the grpc repo but I think here is the right place for it.
 I have been searching for how to manipulate tokens on the client side of a web app for days. As we all know, the only secure storage on the client side is the http-only cookie, but it seems that grpc has no way to interact with it, and one can only store the token obtained from trailer metadata in the local storage (or something like that) and put it in the header metadata when calling other functions. Since local storage can be stolen by any js code, is there a better way to handle such data? Thanks!

**Comment by swuecho** [comment]
>  it seems that grpc has no way to interact with it

this is not accuate, check the issue 351. hope it helps.

https://github.com/grpc/grpc-web/issues/351
