### ISSUE TITLE
`end` event occasionally STILL not emitted?

### ISSUE THREAD

**Issue by sirudog** [grpc/grpc-web#543]
Hi,

I have upgraded my project to 1.0.4 so that I can eliminate the workaround taken from issue https://github.com/grpc/grpc-web/issues/289 needed for being notified about end of server-side streaming. In my project I use nginx (grpc-web enabled), C# gRPC service and a common.js+dts client.

**Unfortunately, this bug still seems to be not fixed: sometimes the `end` event is just not fired.**

Before raising this issue, I installed the echo example (https://github.com/grpc/grpc-web/tree/1.0.4#advanced-demo-browser-echo-app) using win10 + docker desktop.  I started it in chrome, but I never got a console message of `stream end signal received`, so the issue there is even worse. Only `Received metadata` message is logged on `status` event, as the screenshot below shows.
![image](https://user-images.githubusercontent.com/1550561/56584799-d313a000-65dc-11e9-8296-969c60c4f6cc.png)

I believe the end event handler in below code sample taken from the echo example should have also been called at end of each streaming response.
```
o.EchoApp.prototype.repeatEcho = function(e, t) {
        o.EchoApp.addLeftMessage(e),
        t > o.EchoApp.MAX_STREAM_MESSAGES && (t = o.EchoApp.MAX_STREAM_MESSAGES);
        var r = new this.ctors.ServerStreamingEchoRequest;
        r.setMessage(e),
        r.setMessageCount(t),
        r.setMessageInterval(o.EchoApp.INTERVAL);
        var n = this.echoService.serverStreamingEcho(r, {
            "custom-header-1": "value1"
        })
          , g = this;
        n.on("data", function(e) {
            o.EchoApp.addRightMessage(e.getMessage())
        }),
        n.on("status", function(e) {
            g.handlers.checkGrpcStatusCode(e),
            e.metadata && (console.log("Received metadata"),
            console.log(e.metadata))
        }),
        n.on("error", function(e) {
            o.EchoApp.addRightMessage("Error code: " + e.code + ' "' + e.message + '"')
        }),
        n.on("end", function() {
            console.log("stream end signal received")
        })
    }
```
I would appreciate if someone could check this.

**Comment by sirudog** [comment]
Anyone has the same issue with the echo example? Or with 'end' event of server-side streaming in general?

**Comment by martinblostein** [comment]
I have noticed the same issue with both the echo example, and originally in my own code.

**Comment by annismckenzie** [comment]
Yup, still happening for me with a real gRPC service in Golang with Envoy 1.10 at the ingress (via Contour v0.14.1).

**Comment by perrywky** [comment]
me too, end or status event never occurred, my stack:

grpc-web: 1.0.5

**Comment by perrywky** [comment]
another hint: when deployed in the k8s, the request never ends, Chrome DevTools shows this:

![image](https://user-images.githubusercontent.com/456070/63660014-22feaf80-c7e7-11e9-8655-05ff8e4bd37e.png)

and the request will end up in a failed status

![image](https://user-images.githubusercontent.com/456070/63660124-956f8f80-c7e7-11e9-8434-3dd45a636535.png)

this doesn't happen when running on my macbook pro.

I guess may be the response EOF is dropped somehow?

**Comment by stanley-cheung** [comment]
Closing this for now. If this is still an issue, please open a new one.
