### ISSUE TITLE
How to run hello world example on iOS?

### ISSUE THREAD

**Issue by WeroNikaNa** [grpc/grpc-web#552]
It is working for me on Ubuntu 16 with:
protoc --version
libprotoc 3.3.0
node --version
v10.15.3
And on iOS 10.11.6 I am getting errors in the browser(chrome):
<img width="1263" alt="Zrzut ekranu 2019-05-07 o 12 32 38" src="https://user-images.githubusercontent.com/37484728/57293757-e9822700-70c5-11e9-96b8-3e6f569d064b.png">
protoc --version
libprotoc 3.3.0(I tried also with more new one)
node --version
v11.14.0

Are there some requirements to run it on iOS?
I would be grateful for some ideas which can help to solve this problem

**Comment by ktm-labs** [comment]
This was also discussed [here](https://github.com/grpc/grpc-web/issues/380).  There may be some useful information/discussion.
