### ISSUE TITLE
Setting deadline to `Infinity` causes grpc-web to send "Infinitym" as grpc-timeout

### ISSUE THREAD

**Issue by CatEars** [grpc/grpc-web#554]
I can set the deadline to `Infinity` in a server streaming call (maybe also unary?) and it will set the `grpc-timeout` header to `Infinitym`.

As far as I can tell it is cause by this line https://github.com/grpc/grpc-web/blob/d139a6ad994c9cc3ad619fdb1aa0a231a83e1d80/javascript/net/grpc/web/grpcwebclientbase.js#L220

**Comment by stanley-cheung** [comment]
Ha, that's embarrasing :)

**Comment by CatEars** [comment]
I wouldn't mind doing a pull request for this. Is the solution to just default to a certain value for `grpc-timeout` header when getting `Infinity` as input?

**Comment by stanley-cheung** [comment]
I think 1. we should not accept a string as an input and 2. handle accepting *Infinity* (a number) passed as an argument

**Comment by CatEars** [comment]
Solved with above PR
