### ISSUE TITLE
API Proposal - Client Interceptors

### ISSUE THREAD

**Issue by rogchap** [grpc/grpc-web#555]
# ~gRPC-Web Client Interceptors~

Proposal move to  https://github.com/grpc/grpc-web/pull/558
Previous description removed to avoid confusion

**Comment by stanley-cheung** [comment]
@rogchap This is a great start! Thanks for making this big effort to get this feature started.

Community, and users of gRPC-Web: please also review this to see if you have any feedback to the API design. Many people have asked about this before. Now is the time to speak up.

**Comment by Yannic** [comment]
This is amazing! Thanks for working on this!

I'll have a closer look at the proposed API next week, but it seems like this is a very good start.
In the meantime, it might be easier to have this as a PR so we can use the review feature to discuss specific parts of the proposal (`proposals/interceptors.md`?).

**Comment by stanley-cheung** [comment]
Yes, agreed. Having a PR with a `.md` file can facilitate discussion. We can do this similarly to other gRPC RFCs by making a PR in this repo: https://github.com/grpc/proposal/pulls

**Comment by rogchap** [comment]
Easily done; I have the .md file of my original write up on disk.

Wasn't sure where to submit to get the best visibility for the community; if the gRPC/proposal repo is the right one I'll submit a PR there

**Comment by stanley-cheung** [comment]
I think we can do it two phases: first we can get one PR here in this repo, then with enough review/revision, we can do one over at grpc/proposal for formality.

**Comment by rogchap** [comment]
@stanley-cheung @Yannic Moving this to https://github.com/grpc/grpc-web/pull/558
