### ISSUE TITLE
Optimize float conversion

### ISSUE THREAD

**Issue by wolfgang-braun** [grpc/grpc-web#560]
The JS stubs convert float values in a strange way:

Example proto: `float   test = 1;`
=>  In JS the value `1.2` becomes `1.2000000476837158`

Maybe something like `+floatValue.toFixed(1)` could be added to the stubs?

Thanks!

**Comment by stanley-cheung** [comment]
This is a protobuf issue. Please log an issue to https://github.com/protocolbuffers/protobuf and specify that this is a JS issue.
