### ISSUE TITLE
grpc-web nodejs stream service limit?

### ISSUE THREAD

**Issue by danzimal** [grpc/grpc-web#588]
I began with the tutorial https://grpc.io/docs/tutorials/basic/web/ and have been progressing nicely until a hard stop.
For some reason, my client/server implementation appears to be limited to about 7 server streaming rpc calls.

For example;

service status {
  **rpc StreamOne(OneRequest) returns (stream OneReply);
  rpc StreamTwo(TwoRequest) returns (stream TwoReply);
  rpc StreamThree(ThreeRequest) returns (stream ThreeReply);
  rpc StreamFour(FourRequest) returns (stream FourReply);
  rpc StreamFive(FiveRequest) returns (stream FiveReply);
  rpc StreamSix(SixRequest) returns (stream SixReply);
  rpc StreamSeven(SevenRequest) returns (stream SevenReply);**
  rpc StreamEight(EightRequest) returns (stream EightReply);
  rpc StreamNine(NineRequest) returns (stream NineReply);
}

I can pick any 7 rpc calls in any order from the above service and they work great.
No streaming is performed on any rpc after the 7th.

I'm using proto3, grpc-web, nodejs, envoy proxy, ngnix...

(:

Please advise

**Comment by stanley-cheung** [comment]
Some discussion of the 6-stream Chrome limit in #522
