### ISSUE TITLE
Use remote grpc server with full URL and no IP/Port.

### ISSUE THREAD

**Issue by wannamit** [grpc/grpc-web#598]
I have my GRPC running in a remote server which is exposed via a full URL eg: https://mygrpc.amitj.com.np and only this. Not even https://mygrpc.amitj.com.np:80
As cluster hosts I need to provide `hosts: [{ socket_address: { address: mygrpcserver, port_value: 9090 }}]`, here port_value cannot be empty. Is there any way I can use my remote URL instead of address and port?

**Comment by stanley-cheung** [comment]
This is more a question for Envoy. Looks like either `port_value` or `named_port` must be set https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/address.proto.html
