### ISSUE TITLE
client-side stream service are ignored by the generator

### ISSUE THREAD

**Issue by ericdesa** [grpc/grpc-web#606]
When I use `protoc` with a `commonjs` import style to build a service with a `client-side stream parameter`, the service is ignored.

I have no problem with a `server-side stream return`.

Here is an example of a proto file where the `ServerSide` is the only service generated. `Bidirection` & `ClientSide` are missing.

``` proto
syntax = "proto3";

package api;

service ApiService {
  rpc Bidirection (stream Empty) returns (stream Empty);
  rpc ServerSide (Empty) returns (stream Empty);
  rpc ClientSide (stream Empty) returns (Empty);
}

message Empty {
}
```

The files are generated with this command :

``` bash
protoc -I=./ api.proto \
    --js_out=import_style=commonjs:output \
    --grpc-web_out=import_style=commonjs,mode=grpcwebtext:output
```

The generated file is this one : 
[api_grpc_web_pb.js.txt](https://github.com/grpc/grpc-web/files/3456901/api_grpc_web_pb.js.txt)

I use the last versions of `protoc-gen-grpc-web` (v1.0.5) and `protoc` (3.9.0)

I am missing anything ?

**Comment by stanley-cheung** [comment]
Client side streaming and Bidi streaming are not supported at the moment.

**Comment by ericdesa** [comment]
Shouldn't we update the echo example then ?

https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/echo.proto#L87

```proto
  // A sequence of requests followed by one response (streamed upload).
  // The server returns the total number of messages as the result.
  rpc ClientStreamingEcho(stream ClientStreamingEchoRequest)
      returns (ClientStreamingEchoResponse);

  // A sequence of requests with each message echoed by the server immediately.
  // The server returns the same client messages in order.
  // E.g. this is how the speech API works.
  rpc FullDuplexEcho(stream EchoRequest) returns (stream EchoResponse);

  // A sequence of requests followed by a sequence of responses.
  // The server buffers all the client messages and then returns the same
  // client messages one by one after the client half-closes the stream.
  // This is how an image recognition API may work.
  rpc HalfDuplexEcho(stream EchoRequest) returns (stream EchoResponse);
```

**Comment by stanley-cheung** [comment]
Yea you are right. But unfortunately this file is being copied from a common shared project where those methods do matter in other context. So we can probably make a copy of this file and delete these methods but that introduced some additional maintenance cost. Will keep a note on this.
