### ISSUE TITLE
Envoy 503 Upstream Reset after upgrading to grpc v1.22

### ISSUE THREAD

**Issue by tobiasfriden** [grpc/grpc-web#613]
Hello,

I am running a gRPC service written in go, with an envoy proxy using the grpc-web filter. However, after recently updating my gRPC version from v1.18 to v1.22, I am seeing some strange 503 errors in the envoy log like this:
`"GET / HTTP/1.1" 503 UR 0 85 83 - "-" "GoogleHC/1.0" "c4b7e76e-8435-416b-bd09-a6475206c996" "10.166.0.49" "[::1]:6000"`
Downgrading back to `google.golang.org/grpc@v1.18.0` fixes the issue.

**Comment by stanley-cheung** [comment]
Interesting. We likely need to take this to the gRPC Go team. But first we need to make a simpler reproducible test case for them to look at. Ideally, the test case should have

- a simple docker image running the gRPC Go service (a helloworld will suffice)
- a simple docker image running Envoy with the gRPC-Web filter enabled 
- a hand-crafted curl command that sends a "gRPC-Web" request to Envoy, that will trigger the error in Envoy, if we switch the gRPC Go backend between 1.18 and 1.22

It may take me a while to put these together.

**Comment by tobiasfriden** [comment]
It might be worth mentioning that the 503 is triggered by the Google Cloud healthcheck (I am running my application in GKE). When switched down to v1.18 the health check returns 200.

**Comment by stanley-cheung** [comment]
@tobiasfriden In that case it might be easier to raise this issue directly with the gRPC Go team (github.com/grpc/grpc-go), mentioning the cloud healthcheck piece.
