### ISSUE TITLE
No Promise Handlers Get Called if net::ERR_INTERNET_DISCONNECTED

### ISSUE THREAD

**Issue by jakepoz** [grpc/grpc-web#620]
We have a GRPC-Web call on our React based javascript frontend:

```
        JigManagerService.flagMetadata(request).then(response => {
            console.log("SECTION A");
        }).catch(error => {
            console.log("SECTION B");
        });
```

Normally this code works, getting into Section A if there is a valid response, or Section B if the server returns an error.

However, if you load your page, then go to Chrome Developer Tools, Network Tab, and check "Offline", to simulate temporarily losing connection. Then, when you press your button which triggers the above code, neither Section A or Section B gets called. The console shows

```
index.js:1375 POST http://localhost:8000/JigManager/FlagMetadata net::ERR_INTERNET_DISCONNECTED
```

However, the promise does not return as an error. I'd expect to see an error with status code UNAVAILABLE.

(Tested with GRPC-Web 1.0.6)

**Comment by caseylucas** [comment]
Possibly related to https://github.com/grpc/grpc-web/issues/450 ?

**Comment by stanley-cheung** [comment]
Sorry for the delay - this should be fixed recently. We now have a [unit test](https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/test/generated_code_test.js#L121-L141) for this particular scenario. A network error should trigger the `.catch()` part of the promise.
