### ISSUE TITLE
Server stream pagination

### ISSUE THREAD

**Issue by stefan-prokop-cz** [grpc/grpc-web#623]
We are using grpc-web in our react app. Is there some possibility how to work with pages? Now we are using limit and offset but we would like to work with results like with stream - use pipes, pause stream and on another page continue reading it.

Is there some better ways how to do it?
Are you planning to work on it and when?

**Comment by leoluk** [comment]
This is something you would have to implement on the server side just like a unary endpoint, i.e. return a pagination token in the stream, cancel the stream, then open a new stream and specify limit/token.

**Comment by stanley-cheung** [comment]
Yes this would be how you design your proto service. You can potentially pass in a page number as an argument on a method.
