### ISSUE TITLE
Why does the protobuf JavaScript code generator suffix collections with the collection type?

### ISSUE THREAD

**Issue by herpiko** [grpc/grpc-web#627]
I've the same question as https://stackoverflow.com/questions/51508553/why-does-the-protobuf-javascript-compiler-suffix-collections-with-list-map and add its question here.

For example:
- repeated string names becomes obj.namesList
- map<string, string> bar becomes obj.barMap
And this is as per the documentation, here: https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#repeated

Why is that? It makes life difficult when using grpc-gateway with --swagger_out because the swagger API definitions don't match the generated JavaScript.

If I defined `repeated list = 3` then I get `response.getListList()` and the object became `obj.ListList`. Is there any option to disable this limitation?

**Comment by stanley-cheung** [comment]
This is a question for the https://github.com/protocolbuffers/protobuf
