### ISSUE TITLE
gRPC in docker container can't connect to services on host machine

### ISSUE THREAD

**Issue by danjenson** [grpc/grpc-web#636]
I have slightly modified this example: https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo. I am running envoy on a docker container with exposed port 8080. I am running all the services on my localhost (the host machine of the envoy docker container). However, I cannot seem to connect envoy in the docker container to the services running on the host machine.

I compiled `grpc_cli` in the container and when I run `grpc_cli ls 192.168.1.10:9000` (host's LAN IP address and the port the service is running on), I get
```
root@bdc9ac396a87:~/grpc# ./bins/opt/grpc_cli ls 192.168.1.10:9000
Received an error when querying services endpoint.
ServerReflectionInfo rpc failed. Error code: 14, message: failed to connect to all addresses, debug info: {"created":"@1569023274.866465052","description":"Failed to pick subchannel","file"
:"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1569023274.866463178","description":"failed to connect to all addresses","file":"
src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}
```
I get an almost identical error when I use the IP address of the docker0 interface, which should also provide a connection to the host machine.
```
root@bdc9ac396a87:~/grpc# ./bins/opt/grpc_cli ls 172.17.0.1:9000                                                                                                                             
Received an error when querying services endpoint.                                                                                                                                           
ServerReflectionInfo rpc failed. Error code: 14, message: failed to connect to all addresses, debug info: {"created":"@1569022455.801913949","description":"Failed to pick subchannel","file"
:"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1569022455.801910006","description":"failed to connect to all addresses","file":"
src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}
```
However, running a simple http server from the host with
```python -m http.server```
I can run the following commands from the container just fine:
```
wget 172.17.0.1:8000/test.txt // works
wget 192.168.1.10:8000/test.txt // works
```
A client on the host (not in the container) connects and works just fine with the service, so it's not a server problem. 

Does docker block certain types of traffic? I noticed in the example the server was placed on another docker container, and it worked (it also worked locally for me), but I'd prefer to have my services running on my host machine while I build and test them. Is there a setting somewhere to enable gRPC from the container to a service on the host machine?

Docker version 1.13.1, build 47e2230/1.13.1
Fedora 29

**Comment by stanley-cheung** [comment]
Sorry this seems like an issue with using docker in your environment. Try a variation of the `docker run -p 8080:8080` or `--link <from-docker-container-name>:<to-docker-container-name>`, or `--network=host` runtime params to expose your container's port to your host, or try to use `docker-compose`.

In this repo's basic example, i.e. `docker-compose up node-server envoy commonjs-client`, those 3 containers are running separately exposing each of their ports to the host machine. So it works. I'd recommend using our `docker-compose.yml` file as a base to see what you need to do.
