### ISSUE TITLE
TypeError: Cannot read property 'UNARY' of undefined

### ISSUE THREAD

**Issue by MeTheCat** [grpc/grpc-web#637]
Importing echo_grpc_web_pb.js gives me this error, and I can't figure out why or what I did wrong.

I followed the setup steps:
Made a simple echo proto file.
Generated echo_grpc_web_pb.js and echo_pb.js
Included them:
```
const {TestRequest, TestResponse} = require('./echo_pb.js');
const {ApiClient} = require('./echo_grpc_web_pb.js');
```
npx webpack client.js - No errors

When I tried to open an html with client.js inside - I see "Uncaught TypeError: Cannot read property 'UNARY' of undefined" in js console, referring to lines like "grpc.web.MethodType.UNARY,". It happens on the second line of code above, when I try t import echo_grpc_web_pb.js. 
I tried updating protoc, using different protoc-gen-grpc-web, rebuilding it - nothing helped so far. 
Any ideas how to fix it?

**Comment by MeTheCat** [comment]
Turns out there was an issue with package.json, not sure what exactly fixed it, but it definitely had something to do with dependencies, I was probably using an old version of something. 
Working package.json:
```
{
  "name": "grpc-test",
  "version": "0.1.0",
  "description": "gRPC-Web simple example",
  "devDependencies": {
    "@grpc/proto-loader": "^0.3.0",
    "google-protobuf": "^3.6.1",
    "grpc": "^1.15.0",
    "grpc-web": "^1.0.0",
    "webpack": "^4.16.5",
    "webpack-cli": "^3.1.0"
  }
}
```

**Comment by Gtanghaibo** [comment]
how did you fix it

**Comment by MeTheCat** [comment]
> 
> 
> how did you fix it

I don't think I narrowed it down to a specific dependency. So I would try updating grpc, grpc-web, proto to the latest available versions.

**Comment by congaductq** [comment]
> how did you fix it

Hope this helps:

I'm using the same version of:
- `protoc-gen-grpc-web` (https://github.com/grpc/grpc-web/releases)
- `grpc-web` (`package.json` in your project)

Currently, the newest version is 1.2.0:
- https://github.com/grpc/grpc-web/releases/tag/1.2.0
- `"grpc-web": "1.2.0"`
