### ISSUE TITLE
JSON encoding timeline?

### ISSUE THREAD

**Issue by uschen** [grpc/grpc-web#645]
saw something like this in gmail:

```json
{
  "1": 0,
  "2": [
    {
      "1": "thread-f:164528822743681xxxx",
      "3": [
        {
          "1": "msg-f:1645288227xxxx",
          "2": {
            "1": [
              {
                "1": 1,
                "2": "xxxx"
              }
            ],
            "5": "AUTO: xxxxx",
```

wonder there is a timeline when grpc-web will support that.

**Comment by wenbozhu** [comment]
Unfortunately, we don't yet have a timeline to open-source this format. The team is currently working on optimizing the binary-proto performance (in browsers, with v8).

Will keep everyone posted. 

Thanks!

**Comment by uschen** [comment]
@wenbozhu any updates regarding the timeline?

**Comment by uschen** [comment]
any updates?
