### ISSUE TITLE
base64 encode increase the msg size

### ISSUE THREAD

**Issue by jmzwcn** [grpc/grpc-web#658]
As we know, base64 encode increase the msg size, how we should avoid this disadvantage?

**Comment by stanley-cheung** [comment]
You can perfectly use the `mode=grpcweb` in the code generator plugin, which will not do the base64-encode. But that mode only support simple unary call. If you need streaming (server-side streaming), you need `mode=grpcwebtext`.

**Comment by jmzwcn** [comment]
I not only want use unary, also streaming... ^_^  laugh ^_^
