### ISSUE TITLE
Console error "grpc-status", "grpc-message" while data successfully come back

### ISSUE THREAD

**Issue by zsluedem** [grpc/grpc-web#659]
I am using a nginx proxy which is compiled according to docker example in the repo.

I send a request to the proxy and it can receive the data correctly while the console would log a lot of errors.

```
Refused to get unsafe header "grpc-status"
Refused to get unsafe header "grpc-message"
```
![image](https://user-images.githubusercontent.com/13496262/67073351-7bd04000-f1b9-11e9-8260-d31ae56d71da.png)

**Comment by sirudog** [comment]
I think you should add this to your nginx config to expose these headers to the browser: 
`add_header 'Access-Control-Expose-Headers' 'Content-Transfer-Encoding,Grpc-Message,Grpc-Status'`
Hope this helps

**Comment by stanley-cheung** [comment]
Yes you need to white list those headers in your nginx.conf

**Comment by stanley-cheung** [comment]
I see. We probably miss that in our own [example nginx.conf](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/nginx.conf#L37). We should probably fix it.

**Comment by zsluedem** [comment]
@stanley-cheung https://github.com/grpc/grpc-web/pull/663
