### ISSUE TITLE
Cannot retrieve gRPC metadata from responses

### ISSUE THREAD

**Issue by dtaniwaki** [grpc/grpc-web#662]
My server returns responses with trace ID for opentracing but it seems grpc-web client doesn't provide ways to retrieve them.

**Comment by stanley-cheung** [comment]
Can you show us a sample request/response from the browser developer console? I'd like to see how it looks like as the response.

**Comment by dtaniwaki** [comment]
Here's a sample request and response.
![headers](https://user-images.githubusercontent.com/1162120/67300667-4ca72f00-f529-11e9-8038-ccd8fc769037.jpg)
![response](https://user-images.githubusercontent.com/1162120/67300669-4d3fc580-f529-11e9-9c9d-173bbc8e3c1f.jpg)

`x-request-id` is the metadata I set in the server.

**Comment by c0m3tx** [comment]
I have the same issue.

I tried adding a block "onHeaders" to grpc.invoke function in generated JS and it works, but ofc it is overwritten each time I recompile the proto. I have no idea how to change the generator, else I would submit a PR.

```
ProtocolsClient.prototype.index = function index(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: [],
    headers: [],
  };
  var client = grpc.invoke(Protocols.Index, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    },
    onHeaders: function (headers) {
      listeners.headers.forEach(function (handler) {
        handler(headers);
      })
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};
```

This allows using

```
stream.on('headers', (header) => {
  // do smth with header
})
```

Any hint? I would like to contribute.
