### ISSUE TITLE
closure_grpc_web_library fails to pull transitive dependencies

### ISSUE THREAD

**Issue by rafikn** [grpc/grpc-web#673]
This is a known issue with protobuf `3.10.0` #575
but is also happening with `3.9.0`
example proto:
```
syntax = "proto3";

package echo;

import "google/protobuf/empty.proto";

service EchoServer {
  rpc Echo (google.protobuf.Empty) returns (EchoReply) {}
}


// The response message containing the greetings
message EchoReply {
  string response = 1;
}
```
example BUILD.bazel
```
load("@com_github_grpc_grpc_web//bazel:closure_grpc_web_library.bzl", "closure_grpc_web_library")

proto_library(
  name = "echo_proto",
  srcs = [
    "echo.proto",
  ],
  deps = [
    "@com_google_protobuf//:empty_proto",
  ]
)

closure_grpc_web_library(
  name = "echo_web_lib",
  deps = [":echo_proto"]
)
```
the `echo_proto` rule builds fine, but the `echo_web_lib` target fails with:
```
google/protobuf/empty.proto: File not found.
echo.proto:5:1: Import "google/protobuf/empty.proto" was not found or had errors.
echo.proto:8:13: "google.protobuf.Empty" is not defined.
Target //:echo_web_lib failed to build
```

protoc version:
```
bazel-out/host/bin/external/com_google_protobuf/protoc --version
libprotoc 3.9.0
```

Full demo: https://github.com/rafikn/closure_grpc_web_library

**Comment by Yannic** [comment]
This is caused by the flip of `--incompatible_generated_protos_in_virtual_imports` (https://github.com/bazelbuild/bazel/issues/9215). Strangely, `closure_proto_library` seems to work, though.

This will require the same fix as #575, hence duping into that issue. Close, please.

**Comment by rafikn** [comment]
duplicated in #575

**Comment by rafaelmagalhaes** [comment]
any updates on this,
I'm having the same problem

this is the command im running 
`    "proto:docker": "mkdirp proto && protoc --proto_path=./proto-files $(find ./proto-files/ -iname \"*.proto\") --js_out=\"import_style=commonjs,binary:proto\" --ts_out=\"service=grpc-web:proto\""`


this is the error I get back

```
google/protobuf/empty.proto: File not found.
ConsentNotificationService.proto: Import "google/protobuf/empty.proto" was not found or had errors.
ConsentNotificationService.proto:14:48: "google.protobuf.Empty" is not defined
```.
