### ISSUE TITLE
When will 1.0.7 be released?

### ISSUE THREAD

**Issue by Sovietaced** [grpc/grpc-web#674]
Hi folks. I have checked out the documentation but I cannot any information about the release cadence for this library. It appears that grpc follows a 6 week release cycle but that does not appear to be the case here as the last release was at the beginning of August. I am waiting on a release that contains #621 and just curious when to check back. If there is anything I can do I'd be happy to help.

**Comment by stanley-cheung** [comment]
Yes sorry I will do 1.0.7 as soon as I can, hopefully within the next few days. Sorry that we haven't been able to formalize this as "every 6 weeks" but that's something we definitely want to achieve say next year.

**Comment by Sovietaced** [comment]
> Yes sorry I will do 1.0.7 as soon as I can, hopefully within the next few days. Sorry that we haven't been able to formalize this as "every 6 weeks" but that's something we definitely want to achieve say next year.

thanks!

**Comment by stanley-cheung** [comment]
[1.0.7](https://github.com/grpc/grpc-web/releases/tag/1.0.7) has been released.
