### ISSUE TITLE
Support for retries

### ISSUE THREAD

**Issue by ericdudley** [grpc/grpc-web#677]
Is there any plans to implement a retry option for gRPC calls?

When working with an API that requires the usage of retries, it would be useful to have a built in option.

**Comment by loeffel-io** [comment]
+1

**Comment by sampajano** [comment]
Thanks for the interest!

Retry can in general be implemented as an interceptor.

Please take a look at that option and see if it works for you. (We might be able to provide some example implementations if necessasry, as some internal teams have created their own retry interceptors too.)

**Comment by abaoai** [comment]
This is very painful. Cloudflare sends 503 too often.

**Comment by sampajano** [comment]
An simple retry interceptor can be implemented like the following:

```typescript
export class RetryUnaryInterceptor {
  private maxRetries = 3;
  private initialBackoffMs = 100;

  constructor() {}

  async intercept<Q, S>(
    request: Request<Q, S>,
    invoker: (request: Request<Q, S>) => Promise<UnaryResponse<S>>
  ): Promise<UnaryResponse<S>> {
    let attempt = 0;
    let backoffMs = this.initialBackoffMs;

    while (attempt < this.maxRetries) {
      try {
        return await invoker(request);
      } catch (error: unknown) {
        if (error instanceof RpcError && isRetryable(error.code as number)) {
          attempt++;
          if (attempt >= this.maxRetries) {
            throw error;
          }
          await new Promise(resolve => setTimeout(resolve, backoffMs));
          backoffMs *= 2; // Exponential backoff
        } else {
          throw error;
        }
      }
    }
    throw new Error('Max retries exceeded');
  }
}
```

Given it's exactly what interceptor is intended to achieve, i think it doesn't NEED to be part of the core library.

But if someone wants to put out a PR to add it to a "contrib" part of the codebase, It'd be very welcome as well 😊

I'll close it for now as the above shows a simple way how the goal can be achieved :)
