### ISSUE TITLE
Parsing fails with byte type

### ISSUE THREAD

**Issue by pranaypratyush** [grpc/grpc-web#684]
I get the following error when I try to send a `byte` Type through the grpc-web passing through envoy 
```
Uncaught Error: The stream is broken @0/0. Error: invalid frame byte. With input:
1,0,0,1,214,31,139,8,0,0,0,0,0,0,3,227,218,173,165,180,73,235,255,141,255,15,24,...........,97,116,117,115,58,48,13,10,103,114,112,99,45,109,101,115,115,97,103,101,58,13,10
```
#561 tells me that envoy is adding the `grpc-encoding: gzip` header in the request and that this problem wouldn't happen without it. As I am using python for the server I have been trying to find a method to ignore it but have failed to do so. Any pointers would be highly appreciated. 
Something I noticed is that this error doesn't happen when the size of the payload is smaller than 70 bytes. Quite puzzling.

**Comment by stanley-cheung** [comment]
There are several issues like this. I am folding this into #561.
