### ISSUE TITLE
Warning export client was not found

### ISSUE THREAD

**Issue by 19700101000000** [grpc/grpc-web#688]
I'm using Vue.js and TypeScript.

```proto
service Example {
  rpc Example (Request) returns (stream Response) {}
}
```
this code successed buiding.
```bash
protoc -I protobuf/ protobuf/example.proto \
  --plugin=protoc-gen-ts=vue-project/node_modules/.bin/protoc-gen-ts \
  --js_out=import_style=commonjs,binary:vue-project/src/generateds \
  --ts_out=service=grpc-web:vue-project/src/generateds
```
showing this warning when excute `npm run serve`.
```bash
Warning in ./src/index.ts
"export 'ExampleClient' was not found in '@/generateds/example_pb_service'
```

`index.ts` and `example_pb_service.d.ts` writed this.
```ts
import {ExampleClient} from '@/generateds/example_pb_service';
```
```ts
export class ExampleClient {
  // ...
}
```
`chrome dev-tool's console`is showing this error.
```console
Uncaught ReferenceError: exports is not defined
```
but, I removed `stream` for `proto`'s code, there were no errors and warnings.
why is this happening?

**Comment by tmat-s** [comment]
@19700101000000 
Have you found any solution for this? I'm encountering same problem.

**Comment by 19700101000000** [comment]
@tmat-s 
I'm sorry.
I couldn't solve it. So gave up.

**Comment by chaozgz** [comment]
I have the same problem after making changes in the proto file and recompiling it.

**Comment by stanley-cheung** [comment]
Sorry I don't recognize this plugin `vue-project/node_modules/.bin/protoc-gen-ts`. Doesn't seem to be provided by this repo / project.
