### ISSUE TITLE
CXX should not be hardcoded to g++

### ISSUE THREAD

**Issue by abbec** [grpc/grpc-web#690]
When using nix to create a custom derivation on macOS for building `protoc-gen-grpc-web` I ran into an issue where the protobuf libraries in nixpkgs are compiled with clang and the `Makefile` inside `javascript/net/grpc/web` hardcodes CXX to g++.

It builds fine if CXX is set to clang++ so I would propose changing the `Makefile` line to read

```make
CXX ?= g++
...
```

to default to g++ but still allow overrides.

**Comment by stanley-cheung** [comment]
@abbec Thanks for the issue report!
