### ISSUE TITLE
missing metadata/headers in server side

### ISSUE THREAD

**Issue by shawncao** [grpc/grpc-web#691]
Hi,

I'm using a standard setup as "grpc-web -> enovy -> grpc server (c++)".
in client side, I make RPC call with metadata object and I expect those properties received in server side, however I don't see any metadata key except "user-agent". 

Here is the server side code debugging log:
`const auto& metadata = ctx->client_metadata();
  LOG(INFO) << "DEBUG: metadata=" << metadata.size();
  for (auto itr = metadata.cbegin(); itr != metadata.cend(); ++itr) {
    LOG(INFO) << "key=" << itr->first << ",value=" << itr->second;
  }
  LOG(INFO) << "DEBUG: metadata end";
`

sample log indicates only one key-value captured.
> server_1  | I1206 18:23:18.793750    12 NebulaServer.cpp:163] DEBUG: metadata=1
> server_1  | I1206 18:23:18.793764    12 NebulaServer.cpp:165] key=user-agent,value=grpc-node/1.24.2 grpc-c/8.0.0 (linux; chttp2; ganges)
> server_1  | I1206 18:23:18.793768    12 NebulaServer.cpp:167] DEBUG: metadata end

And here is the client call:
`    client.query(req, {
        "nebula": "test"
    }, (err, reply) => { ... });`

in Enovy.yaml, I added those keys to "allowed-headers" in the http connection manager filter

I don't know if this is caused by either:
- grpc-web doesn't interpret the metadata object and send over?
- enovy filtered the metadata/headers before transfer to grpc server?
- grpc server code issue, am I capturing the headers in the right place?

Any suggestions on how to debug this issue? Thank you!

**Comment by stanley-cheung** [comment]
You seem to be doing all the right things.

Did you specify the `allow_methods` too in your envoy.yaml? https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L30-L31

Your c++ server code seems correct. That's how I set up my example too. https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/echo_service_impl.cc#L41

**Comment by shawncao** [comment]
Thank you @stanley-cheung for the reply. Yes, allow_methods is specified, see [here](https://github.com/shawncao/nebula/blob/master/src/service/http/envoy.yaml#L30).

the request is sent from web server (nodejs) not browser. code reference [here](https://github.com/shawncao/nebula/blob/master/src/service/http/nebula/node.js#L482), I have local change to replace the empty metadata object with key-value pairs.

I'm thinking if there is way to print out each http request (headers) in envoy log to check if the headers are really sent.

**Comment by stanley-cheung** [comment]
This project is meant to be run from the browser because of the xhr dependencies, not from NodeJS. Basically the grpc-web library adds all the `metadata` as http headers for the underlying xhr request. I am not sure how the xhr request was handled in nodejs - do they allow sending arbitrary custom headers? This whole thing works from the browser because of the CORS mechanism - the browser first sent Envoy an OPTIONS request, the response to that determines which headers are allowed to be sent. I am not sure how this whole mechanism would have worked in NodeJS and is really out of the scope of this project.

**Comment by shawncao** [comment]
@stanley-cheung thanks for the comment. That sounds right, I have two modes, one is invoking service from browser and the other is using web server (nodejs) as proxy, yeah, so that makes sense if the headers are not set correctly in nodejs env, I'll dig a bit more over there. If I found anything conclusive, I'll share back.

**Comment by shawncao** [comment]
It turns out, from nodejs server, the rpc call doesn't go through envoy, and I have to construct grpc.Metadata rather than a plain object to make it reach grpc server.

`const metadata = new grpc.Metadata(); metadata.add("nebula", "test"); client.query(req, metadata, (err, reply) => { ... });`

Thanks for the help!

**Comment by janiskemper** [comment]
I have the same problem. I use grpc-web together with a Golang server. I used ```headers, ok := metadata.FromIncomingContext(ctx)``` which always shows me that there are no headers (ok == false). I tried both with ```metadata = { nebula: "test" }``` as is described in the docs here and with ```grpc.Metadata()``` (with ```import { grpc } from '@improbable-eng/grpc-web'```). Any suggestions?

**Comment by shawncao** [comment]
Sorry @janiskemper - it has been a while and I forgot details related to `grpc-web`, I believe late on we stopped using `grpc-web` lib. Here is the place we use grpc.Metadata object to pass the request headers I believe 

https://github.com/varchar-io/nebula/blob/master/src/service/http/nebula/node.js#L123-L127

and the node.js lib it's using is from `grpc` as noted here:
https://github.com/varchar-io/nebula/blob/master/src/service/http/nebula/package.json#L35

**Comment by janiskemper** [comment]
Thanks @shawncao. Your package.json was definitely helpful, however I already tried using the grpc package and it always breaks my Vue.js app with the error ```Uncaught TypeError: n.version is undefined```, so I cannot even try it out. But anyway, according to the docs a normal object should be working as well, so I think I open another issue on this. Thank you for the quick response!
