### ISSUE TITLE
TypeScript type generation wrong when using multiple files

### ISSUE THREAD

**Issue by joaomlneto** [grpc/grpc-web#693]
I'm currently migrating my GRPC service declarations from JS to Typescript and noticed that the code generation is wrong when referencing messages/types from other files.

Given the code below, the following `MyServiceServiceClientPb.ts` is generated:
```
...
  methodInfoaddOne = new grpcWeb.AbstractClientBase.MethodInfo(
    MyMessagesFile_pbInteger,
    (request: MyMessagesFile_pbInteger) => {
      return request.serializeBinary();
    },
    MyMessagesFile_pbInteger.deserializeBinary
  );
...
```

Note the correct type is `MyMessagesFile_pb.Integer` (the *dot* is missing)!

This is printed in [`grpc_generator.cc:713`](https://github.com/joaomlneto/grpc-web/blob/d03435fc6e39a3ae95ac385859c6f115d9b8c59f/javascript/net/grpc/web/grpc_generator.cc#L713).

---

Using `libprotoc 3.11.1` and `grpc-web 1.0.7`

`MyServiceFile.proto`
```
syntax = "proto3";
import "MyMessagesFile.proto";

service MyService {
  rpc addOne(Integer) returns (Integer);
}
```

`MyMessagesFile.proto`
```
message Integer {
  int32 number = 1;
}
```

`package.json`
```
{
  ...
  "scripts": {
    ...
    "grpc-generate": "mkdir -p src/proto && protoc -I=/path/to/proto/folder /path/to/proto/folder/*.proto --js_out=import_style=commonjs:src/proto --grpc-web_out=import_style=typescript,mode=grpcwebtext:src/proto && for f in src/proto/*.js; do sed -i '1s;^;/* eslint-disable */;' $f; done",
    "grpc-generate-macos": "mkdir -p src/proto && protoc -I=/path/to/proto/folder /path/to/proto/folder/*.proto --js_out=import_style=commonjs:src/proto --grpc-web_out=import_style=typescript,mode=grpcwebtext:src/proto && for f in src/proto/*.js; do sed -i '' '1s;^;/* eslint-disable */;' $f; done",
    ...
  }
  ...
}
```

**Comment by Jdban** [comment]
This is happening to us too. Extremely annoying... I guess I'm fixing it with sed for now?

**Comment by joaomlneto** [comment]
That’s how I’m approaching it. Since I don’t generate the files too often, and I don’t have that many, it’s not too bad to do it.

Fixing it does not look too hard, but I don’t have the bandwidth to tackle it at the moment. 

If you end up creating a generic-enough script to use as workaround, please post it here for everyone. :)

João

**Comment by nathanhleung** [comment]
> This is happening to us too. Extremely annoying... I guess I'm fixing it with sed for now?

Affecting me too... can you share your `sed` expression?

**Comment by Jdban** [comment]
> Affecting me too... can you share your `sed` expression @Jdban?

Sure, it's not very generic though. It's just doing an explicit find/replace on the string in all the .ts files. 

in our bash script:
```bash
# Handles this annoying bug: https://github.com/grpc/grpc-web/issues/693
ORIGINAL=shared_pbFilterRequest
REPLACEMENT=shared_pb.FilterRequest
grep -l -E "$ORIGINAL" **/*.ts  | xargs sed -i.bak "s#$ORIGINAL#$REPLACEMENT#g"
rm -rf js/*.bak   # Our files are in a js folder
```

**Comment by rieshy** [comment]
Unfortunately the fix does not seem to cover the "enum" entries defined in the imported proto. The "." is still missing for them using release 1.2.1
