### ISSUE TITLE
Ubuntu 16.04 - Nginx Make fails from example script

### ISSUE THREAD

**Issue by TylerHallPureEngineering** [grpc/grpc-web#694]
If you run the docker file for 16.04:
https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/ubuntu_16_04/Dockerfile

It will fail to compile the Nginx proxy, stating:
`/github/grpc-web/net/grpc/gateway/protos/pair.pb.cc:80:13: error: 'dynamic_init_dummy_pair_2eproto' defined but not used [-Werror=unused-variable]
 static bool dynamic_init_dummy_pair_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_pair_2eproto), true);
             ^
cc1plus: all warnings being treated as errors
make[2]: *** [objs/addon/protos/pair.pb.o] Error 1
objs/Makefile:1466: recipe for target 'objs/addon/protos/pair.pb.o' failed
make[2]: Leaving directory '/github/grpc-web/third_party/nginx/src'
make[1]: *** [all] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: Leaving directory '/github/grpc-web/third_party/nginx/src'
make: *** [nginx_static] Error 2
Makefile:72: recipe for target 'nginx_static' failed
The command '/bin/sh -c cd /github/grpc-web &&   make' returned a non-zero code: 2`

I could go in and ignore this warning. But, if this is an issue, I know others will be running on 16.04

I only found this because I'm running an Ubuntu 16.04 base with those RUN commands plus a few of my own. Running this Dockerfile from the latest master will fail.

But in node:10-stretch, with the same commands will successfully compile.

Running them one at a time in a clean Ubuntu 16.04, there is an issue after running make install in the third_party/grpc and it doesn't initialize correctly third_party/grpc/third_party/protobuf. 

I can move to node:10-stretch for the time, but I need to get this figured out

**Comment by TylerHallPureEngineering** [comment]
Also note, this was working since i last checked on this repo, but that was before 1.0.7 release.

**Comment by stanley-cheung** [comment]
Sorry we are slowly stopping support for these old nginx proxy code. I have recently removed these scripts.
