### ISSUE TITLE
--grpc-web_out: protoc-gen-grpc-web: Plugin failed with status code 3221225781.

### ISSUE THREAD

**Issue by Peng-Kun-Dai** [grpc/grpc-web#697]
When I execute the command "protoc --js_out=import_style=commonjs:. --grpc-web_out=import_style=commonjs,mode=grpcweb:. hi.proto" on Windows, the prompt is as follows, I cannot solve it

**Comment by MahamShakir** [comment]
The issue is closed without properly defining how to overcome this problem?

**Comment by Type1J** [comment]
You need to install the VC Runtime. You may be able to get away with just installing the runtime, but here's what I did (install the whole SDK).
```
curl -fSLo vs_BuildTools.exe https://download.visualstudio.microsoft.com/download/pr/c30a4f7e-41da-41a5-afe8-ac56abf2740f/167daa8a4c9c242a49400cb5daae6ed2077a41465b9e817b568c5369127168df/vs_BuildTools.exe `
&&  start /w vs_BuildTools ^ `
    --installPath C:\BuildTools ^ `
    --add Microsoft.Component.MSBuild ^ `
    --add Microsoft.VisualStudio.Component.Windows10SDK.18362 ^ `
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 ^ `
    --quiet --norestart --nocache --wait `
&&  del vs_buildtools.exe
```

**Comment by snaumau** [comment]
I have the same one, how to solve it?

**Comment by kms0219kms** [comment]
@incredible007 @snaumau Install vs_BuildTools.exe, it should solve your issue.
