### ISSUE TITLE
Server streaming to all connected users

### ISSUE THREAD

**Issue by coilnovasince1985** [grpc/grpc-web#699]
I do have a simple service which provides a server streaming to all users connected via grpc-web and a simple unary call to send a message to a specific user.

My question is, how can I send something to all grpc connected users ? what is the best approach?
I was thinking to store all connected users in a go map structure and then iterate over it, but this method doesn't really scale in case if I have multiple services. 

```
service NotificationsService {
    rpc SendNotificationMessage(NotificationMessageRequest) returns (NotificationMessageResponse) {};
    rpc GetLatestNotifications(NotificationsRequest) returns (stream NotificationsResponse) {};
}
```

**Comment by stanley-cheung** [comment]
See #743
