### ISSUE TITLE
grpc-web and knative

### ISSUE THREAD

**Issue by saschahofmann** [grpc/grpc-web#701]
We are running a grpc-python server on a k8s cluster with knative. We are able to connect to the server from a grpc-node client but struggle to set up the connection from a grpc-web client. Has anyone done that?

If I am not mistaken we are able to circumvent the istio-gateway and envoy sidecar in the case of the grpc-node call by connection to `service.namespace.cluster:port` but have to go through that for grpc-web. 

We tried following [this blog post](https://venilnoronha.io/seamless-cloud-native-apps-with-grpc-web-and-istio) which sets up a connection with a service through the istio gateway but we struggle to convert it to a knative setup.

**Comment by salanki** [comment]
Did you figure this out? My problem seems to be with the content type. `"Content-Type: application/grpc` is fine but `"Content-Type: application/grpc-web` is not

**Comment by ycd** [comment]
We were previously using an internal fork of [net-istio](https://github.com/knative-sandbox/net-istio) and a custom Envoy Gateway to achieve this.

Today i thought there might be an easier way and actually there is. 

The `grpc-web` uses **HTTP 1.1**, so we had to change two things.

1. Using `http1` in manifest.
```yaml
ports:
  - name: http1
    containerPort: 8080
```  

2. Using an another implementation of `grpc-web`(See: https://github.com/improbable-eng/grpc-web), which allows you to wrap the actual gRPC server.

```go
grpcServer := grpc.NewServer()

wrappedGrpc := grpcweb.WrapServer(grpcServer)

httpServer := http.Server{
	Handler: http.HandlerFunc(func(resp http.ResponseWriter, req *http.Request) {
		isGrpcWebRequest := wrappedGrpc.IsGrpcWebRequest(req)
		if isGrpcWebRequest {
			wrappedGrpc.ServeHTTP(resp, req)
			return
		}

		http.DefaultServeMux.ServeHTTP(resp, req)
	}),
}

g.Go(func() error {
	ln, err := net.Listen("tcp", addr)
	if err != nil {
		os.Exit(2)
	}
	return httpServer.Serve(ln)
})
```
