### ISSUE TITLE
Example seems not working

### ISSUE THREAD

**Issue by Mizumaki** [grpc/grpc-web#703]
I cloned this repository, and run `docker-compose up -d node-server envoy commonjs-client`, but failed with the error `Error code: 14 "upstream connect error or disconnect/reset before headers. reset reason: connection failure"`

![failedd](https://user-images.githubusercontent.com/31976113/72199425-43ba5f80-347f-11ea-8722-cfbb53ac9dd8.gif)

**Comment by stanley-cheung** [comment]
Were those docker images successfully built and were actually up? After you run that `docker-compose up -d ...` command, you can check whether those containers were actually up by running `docker ps -a`:

```
~/grpc-web$ docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                      PORTS                               NAMES
313bb602401e        grpcweb/envoy             "/docker-entrypoint.…"   15 seconds ago      Up 14 seconds               0.0.0.0:8080->8080/tcp, 10000/tcp   grpc-web_envoy_1
1922962eb380        grpcweb/node-server       "docker-entrypoint.s…"   15 seconds ago      Up 14 seconds               0.0.0.0:9090->9090/tcp              grpc-web_node-server_1
f91ab97bb032        grpcweb/commonjs-client   "docker-entrypoint.s…"   15 seconds ago      Up 14 seconds               0.0.0.0:8081->8081/tcp              grpc-web_commonjs-client_1
```

You should see the `STATUS` being `Up <duration>`.
