### ISSUE TITLE
protoc-gen-js: program not found or is not executable

### ISSUE THREAD

**Issue by gaoshanyu** [grpc/grpc-web#704]
I use `grpc_tools` to generate the code of proto files in `python` script, but I got errors after I installed `protoc-gen-grpc-web` and run the script. But the command `protoc -I=. *.proto --js_out=import_style=commonjs:.` is working without any errors in `Terminal`.

### My python script
```python
from grpc_tools import protoc

protoc.main((
    '',
    '-I.',
    '--python_out=./target/python',
    '--swift_out=./target/swift',
    '--js_out=import_style=commonjs:./target/js',
    './message_body.proto',
    './message_const.proto',
    './grpc_services/guardian.proto',
    './grpc_services/auth.proto'
))

protoc.main((
    '',
    '-I.',
    '--grpc_python_out=./target/python',
    '--swiftgrpc_out=Client=true,Server=false:./target/swift',
    '--grpc-web_out=import_style=commonjs,mode=grpcwebtext:./target/js',
    './grpc_services/guardian.proto',
    './grpc_services/auth.proto'
))

```

### The errors of my script
```
protoc-gen-js: program not found or is not executable
--js_out: protoc-gen-js: Plugin failed with status code 1.
```

***Warning***: the `grpc` code file is generated after run the script

How can I fix this for my script? Or do I need install the generator `protoc-gen-js`? Please help.

**Comment by stanley-cheung** [comment]
Doesn't seem like this is a grpc-web issue, especially if `protoc -I=. *.proto --js_out=import_style=commonjs:.` runs fine from the command line. This seems like an issue with `grpc_tools` itself.

**Comment by hbak** [comment]
https://github.com/protocolbuffers/protobuf-javascript/issues/105

**Comment by sfc-gh-shsharma** [comment]
If anyone is having this problem on macOS and got here from Google, a workaround that worked for me:

```
brew install protobuf@3
brew link --overwrite protobuf@3
```

https://github.com/protocolbuffers/protobuf-javascript/issues/127#issuecomment-1204202844

**Comment by yinzara** [comment]
I have created a npm package to help everyone.
https://www.npmjs.com/package/protoc-gen-js

You can now `npm i protoc-gen-js` inside a package.json directory to make the '--js_out' work in "scripts" in the package.json (i.e. if one of your package.json scripts calls 'protoc --js_out') and will allow you to specify the version of protoc-gen-js in your package.json

You can also `npm i -g protoc-gen-js` or `npm i -g protoc-gen-js@{version}` and that will make '--js_out' work everywhere at the latest or specific version specified.

**Comment by alsotang** [comment]
I don't want to downgrade my homebrew protobuf version. So I figured it out on my own.

On macOS,

1. Install official `protoc`: `$ brew install protobuf`, then you get the `protoc` executable. 
2. Download `protoc-gen-js` from https://github.com/protocolbuffers/protobuf-javascript/releases, according to your system and cpu arch. And download `protoc-gen-grpc` from https://github.com/grpc/grpc-web/releases/tag/1.5.0. 
3. run this command 
    ```shell
      protoc -I=. echo.proto \
      --plugin="protoc-gen-grpc-web=/Users/atang/Downloads/protoc-gen-grpc-web-1.5.0-darwin-aarch64" \
      --plugin="protoc-gen-js=/Users/atang/Downloads/protobuf-javascript-3.21.2-osx-aarch_64/bin/protoc-gen-js" \
      --js_out=import_style=commonjs,binary:./ts-example \
      --grpc-web_out=import_style=typescript,mode=grpcweb:./ts-example
    ```

It's a bit verbose I know, but I just use the latest version of anything, and all from the official repos.
