### ISSUE TITLE
ERROR Error: The stream is broken @0/0. Error: invalid frame byte.

### ISSUE THREAD

**Issue by RahulRathodGitHub** [grpc/grpc-web#713]
I am using nodejs server and angular frontend. Things work fine without encryption. However, when I put the snippet below in the server for encrypting payload....
![image](https://user-images.githubusercontent.com/42928792/72952339-a4358f00-3de5-11ea-9cd0-5cb1e3020e70.png)

The size of the payload decreases (10 -> 4 kb) but...

I get this error while logging the response:
![image](https://user-images.githubusercontent.com/42928792/72952373-c7603e80-3de5-11ea-81c7-fb60d16b3c7b.png)

What could be the reason behind this?

**Comment by stanley-cheung** [comment]
Probably same issue as #561

**Comment by RahulRathodGitHub** [comment]
Thanks, Stanley... however I did check that issue but it's for some Akka server and is focused on gzip not working. Not applicable to this scenario as not even compression level 1 is being parsed. Is there any additional config needed to be done on the client-side?

**Comment by bclinkinbeard** [comment]
I'm having the same issue, where enabling compression breaks grpc-web. I have an existing call that succeeds when compression is not enabled, and I receive the following response headers.

```
access-control-allow-origin: http://localhost:3000
access-control-expose-headers: grpc-status,grpc-message
content-type: application/grpc-web+proto
date: Wed, 15 Apr 2020 20:45:23 GMT
grpc-accept-encoding: gzip
grpc-encoding: identity
server: envoy
transfer-encoding: chunked
x-envoy-upstream-service-time: 618
```

If I enable compression in my gRPC server by calling `call.setCompression("gzip");` in a `ServerInterceptor`, I get the following response headers and the parsing throws the error reported by OP.

```
access-control-allow-origin: http://localhost:3000
access-control-expose-headers: grpc-status,grpc-message
content-type: application/grpc-web+proto
date: Wed, 15 Apr 2020 20:50:44 GMT
grpc-accept-encoding: gzip
grpc-encoding: gzip
server: envoy
transfer-encoding: chunked
x-envoy-upstream-service-time: 624
```

Based on https://github.com/grpc/grpc-web/blob/master/BROWSER-FEATURES.md#compression, I would have expected a `Content-Encoding: gzip` header in the response, but it's not there. Could that cause the `Uncaught Error: The stream is broken @0/0. Error: invalid frame byte.` error?

I'm also curious if the text wire format needs to be used when compressing, based on #87. Ultimately, I'm not sure how compression is even _supposed_ to work with grpc-web. Is there specific configuration required at the proxy level?

Thanks a bunch for any help or direction you can offer @stanley-cheung.

**Comment by stanley-cheung** [comment]
There are several issues like this - I am folding this into #561. We will look into this soon.

**Comment by anupkrish24** [comment]
@bclinkinbeard Did you end up figuring this out? I tried adding the Content-Encoding: gzip in the Envoy proxy but I'm getting a "(failed) net::ERR_CONTENT_DECODING_FAILED" in my response. Thanks!
