### ISSUE TITLE
how can I get status metadata from service client response with promise async await method

### ISSUE THREAD

**Issue by Poafs1** [grpc/grpc-web#721]
I use grpc-web and envoy proxy to develop my website. Everything works fine, I  can get a response from service client and status metadata from on status function. However, I don't want to get a response inside a callback function, so my solution is to use async-await with a service promise client, in which it responses correctly, but I don't know how to get status metadata from service promise client. Please advise me on this issue. Thank you in advance!

<img width="575" alt="Screen Shot 2563-02-01 at 19 07 08" src="https://user-images.githubusercontent.com/29890935/73592265-ec158e00-452a-11ea-9be4-a155050723a2.png">
<img width="621" alt="Screen Shot 2563-02-01 at 19 07 01" src="https://user-images.githubusercontent.com/29890935/73592269-eddf5180-452a-11ea-903c-893adbd3615c.png">
<img width="1047" alt="Screen Shot 2563-02-01 at 19 06 02" src="https://user-images.githubusercontent.com/29890935/73592270-efa91500-452a-11ea-9a59-731ed5dfbf6a.png">

**Comment by iCovarrubias** [comment]
Is `client.signIn` a unary request?

You can only attach the `on status/data/error/end` method to streams.

**Comment by stanley-cheung** [comment]
Sorry for missing this - now you can get access to the response metadata in the promise-based client, but you have to write an Interceptor for it. The `.then()`API doesn't really give room for the status and metadata.

See this blog post https://grpc.io/blog/grpc-web-interceptor/ about the new Interceptor API. For the promise-based client, you need to implement the `UnaryInterceptor` interface.

You can also check out this [unit test](https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/test/tsc-tests/client04.ts).
