### ISSUE TITLE
Streaming on data only returns all the events at once at the end of the stream

### ISSUE THREAD

**Issue by barrymichaeldoyle** [grpc/grpc-web#724]
I've added a question on StackOverflow to provide [more details here](https://stackoverflow.com/questions/60188375/grpc-streaming-in-react-not-working-as-expected).

Basically, when I setup a stream according to the docs, the streaming functionality doesn't return results as they are streamed. Instead the streamed events all get sent at once just before the stream ends.

**Comment by stanley-cheung** [comment]
It wasn't mentioned in the issue description - which grpc-web proxy are you using?

**Comment by barrymichaeldoyle** [comment]
Just the default on as far as I know.

**Comment by curio77** [comment]
Not the OP, but I'm seeing this with a custom Go application utilizing `github.com/improbable-eng/grpc-web/go/grpcweb`. FWIW, I've enabled WebSockets on the `WrapServer` there.

**Comment by stanley-cheung** [comment]
Looks like this issue is resolved - yes you need to use `mode=grpcwebtext` when using the code generator plugin. The binary wire format does not support streaming. Glad this is resolved.
