### ISSUE TITLE
Not able to get message from helloworld ex

### ISSUE THREAD

**Issue by Jonathon55** [grpc/grpc-web#726]
Using Ubuntu, Cannot Read Property getMessage of 'null'. I have reset the build multiple times and ran it. The container says its up on docker. Then I deleted all the containers and still same error. also deleted clone and re downloaded it.

**Comment by stanley-cheung** [comment]
There isn't enough information to act on this issue report. What commands did you run? What's the result? What's the error message? At what point did you see this error?

**Comment by Jonathon55** [comment]
Was an Envoy Issue. I re did installation and deleted all my docker containers. Now it works thank you for the assistance!
