### ISSUE TITLE
How to get response header information from server?

### ISSUE THREAD

**Issue by chaozgz** [grpc/grpc-web#728]
I want to realize the auth by setting a token in the metadata. When I use the dev tool in the browser, I can see the token set by the server in the response but not in the status.metadata demonstrated in the document. Am I doing it wrong? Where can I get the information in the header?

**Comment by stanley-cheung** [comment]
You most likely have to whitelist that header in your envoy config like this: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L33

**Comment by chaozgz** [comment]
> You most likely have to whitelist that header in your envoy config like this: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L33

Thank you for your prompt reply! Problem solved!
