### ISSUE TITLE
Not able to get response with PromiseClient

### ISSUE THREAD

**Issue by jnaso29** [grpc/grpc-web#729]
I'm having trouble getting the response from my server on the client side while using GreeterPromiseClient instead of PromiseClient in the hello world demo. I'm creating the client and request(on the client side) like so: 

var client = new GreeterPromiseClient(
  "http://" + window.location.hostname + ":8080", 
  null, 
  null
);

var request = new HelloRequest(["John", " Smith"]);

I then call the sayHello function on my client side: 

client.sayHello(request, {})
.then((err, response) => {
  console.log(response.getMessage());
});
This code gives me the error "Uncaught (in promise) TypeError: Cannot read property 'getMessage' of undefined"

I know the service is going through to my server because I log the data from the server side and get the correct data. This is my server function: 

function doSayHello(call, callback) {
  console.log("Server data: ", call.request);
  callback(null, {
    message: "Hello! " + call.request.name + call.request.lastName
  });
}

The console logs: "Server data:  { name: 'John', lastName: ' Smith' }" which is correct so I'm led to believe that maybe I'm not sending the callback correctly. If anyone knows a good reference in the grpc-web docs for grpc promise calls I would appreciate the help. 

Note: everything works fine with the regular GreeterClient. Heres my code for that: 

var client = new GreeterClient(
  "http://" + window.location.hostname + ":8080", 
  null, 
  null
);

var request = new HelloRequest(["Josh", " Naso"]);

client.sayHello(request, {}, (err, response) => {
  console.log(response.getMessage());
});

My server code is the same for both the promise and regular call.

**Comment by iCovarrubias** [comment]
Try looking at the contents of the first parameter (`err`, in this case) in the promise client, the promise client version gives you the response in the first parameter and then to handle errors you need a catch function:

```
client.sayHello(request, {})
  .then((response) => {
        console.log(response.getMessage());
   }.catch((err)=> {
// handle you error here
});
```

**Comment by stanley-cheung** [comment]
The PromiseClient API is actually

```
client.sayHello(request, {})
.then((response) => {
console.log(response.getMessage());
});
```
