### ISSUE TITLE
Is there a proto-loader for gRPC-web?

### ISSUE THREAD

**Issue by skinnyboixD** [grpc/grpc-web#733]
For gRPC there is a proto-loader to generate the protobuf files. But I am wondering if there is something similar for gRPC-web, (helloworld_grpc_web_pb.js, helloworld_pb.js) instead of having to download the protoc plug-in and having to generate it through the terminal. 

Please let me know if this is even possible or if there's a work around. I am building an NPM package for devs to use gRPC-web in React and I would like to automate this process for them. 

Thanks in advance!

**Comment by stanley-cheung** [comment]
Currently this particular client implementation only supports static code generation. We don't currently have plan to support dynamic code generation like proto-loader that gRPC Node supports.

**Comment by skinnyboixD** [comment]
> Currently this particular client implementation only supports static code generation. We don't currently have plan to support dynamic code generation like proto-loader that gRPC Node supports.


> Currently this particular client implementation only supports static code generation. We don't currently have plan to support dynamic code generation like proto-loader that gRPC Node supports.

Thanks for the reply Stanley! Good to know!

**Comment by Ben-Avrahami** [comment]
is it still not supported? or anything changed since
