### ISSUE TITLE
Installation of protoc-gen-grpc-web

### ISSUE THREAD

**Issue by iAmGroot1** [grpc/grpc-web#737]
Hi,

I am currently working on using grpc-web to write a simple client for my service. I have created a service.proto file which was successfully compiled using protoc. The problem arose when I tried to generate the gRPC-Web service client stub using the plugin protoc-gen-grpc-web which doesnt work despite having installed the latter.

Got the following error :
protoc -I=./ service.proto   --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./
protoc-gen-grpc-web: program not found or is not executable
--grpc-web_out: protoc-gen-grpc-web: Plugin failed with status code 1.

OS : Ubuntu 18.04 

Any suggestions on how to solve this issue? Thank you!

**Comment by nboukeffa** [comment]
Is `protoc-gen-grpc-web` in your path? If not modify your path to include the folder where the binary is. If yes try to `chmod +x protoc-gen-grpc-web`, it might be just a permission issue.

**Comment by stanley-cheung** [comment]
Yea did you make sure the `protoc-gen-grpc-web` binary is executable, and is in your `PATH`?
