### ISSUE TITLE
Looking for Hello world example that uses SSL/TLS

### ISSUE THREAD

**Issue by robcecil** [grpc/grpc-web#741]
Looking for usage example(s) demonstrating the 2nd and 3rd parameters for the ctor of the generated client:

```
let apiClient = new APIServicePromiseClient(hostAndPort, null, null);
```
defined as:
```
constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: string; });
```

I'm looking for a way to establish an ssl Credential object, but not sure if is the same API as in the gRPC docs for Nodejs.

The followup on 

https://github.com/grpc/grpc-web/issues/40 
https://github.com/grpc/grpc-web/pull/125

has not progressed.

Thanks

**Comment by Rio-dapp** [comment]
I have similar problem, but i need Insecure permission

**Comment by robcecil** [comment]
> I have similar problem, but i need Insecure permission

I thought the default behavior (with 2nd & 3rd parameters nulled) is the Insecure Channel?

**Comment by Rio-dapp** [comment]
> I thought the default behavior (with 2nd & 3rd parameters nulled) is the Insecure Channel?
In c# (ChannelCredentials.Insecure) and nodeJs (grpc.credentials.createInsecure()) this is different object (but by default Null)

**Comment by robcecil** [comment]
Yes, understood there might be some parallels with the way the objc and c# client stubs were configured for ssl. All that is required in grpc-web is simply using "https://..." in this case apparently.

**Comment by iasniv** [comment]
Did you find an example for this? I posted something similar in https://github.com/grpc/grpc-web/issues/762

**Comment by swuecho** [comment]
I use envoy to take care of the https issues. hope this helpful

**Comment by iasniv** [comment]
> I use envoy to take care of the https issues. hope this helpful

How can there be a trust established between my application in the browser and envoy in this case? In case of client certificate, shouldn't my application be adding the certificate and envoy passing it on upstream?

**Comment by GeorgeTsagk** [comment]
Any progress on this?
Looking for a simple example that makes grpc-web calls over TLS

**Comment by suprraz** [comment]
+1

**Comment by KevinSheridan** [comment]
Also seeking this

**Comment by SunnyAureliusRichard** [comment]
Any update on this?

**Comment by scchess** [comment]
Updates?
