### ISSUE TITLE
How can I set 'insecure' credential?

### ISSUE THREAD

**Issue by Rio-dapp** [grpc/grpc-web#742]
Hello developers,
How can I set 'insecure' credential?
`constructor (hostname: string,
               credentials: null | { [index: string]: string; },
               options: null | { [index: string]: string; });`

I don't find `credentials` object structure

**Comment by stanley-cheung** [comment]
There is nothing you need to do if you are not passing any credentials. There's no separate "insecure" credentials concept here in grpc-web.
