### ISSUE TITLE
Question: gRPC with server-side push

### ISSUE THREAD

**Issue by swilcox3** [grpc/grpc-web#743]
This isn't a bug or a feature request, per se, but a question.  I couldn't find a gitter/discord chat anywhere, so this seemed the best place to ask.  Feel free to move this somewhere more appropriate.

I'm making a real-time browser application with a microservices backend.  The microservices use gRPC.  I'd like it if my browser client could also use that same gRPC interface, but I also need the ability to track connections and push updates to connected clients.  It's a collaborative application, so I need to track which users are connected to what session.  If a user makes changes, those changes need to be pushed to all other clients in the session.
From what I've seen, gRPC isn't a good fit for server-side push, it's probably better to use a Websocket connection for that.  So I was hoping to mix gRPC and Websocket, where I still have my browser client making gRPC calls to the server, but receiving updates through the Websocket.  

Is this completely insane or is it possible?  Is there an alternate method that would provide the same functionality?

**Comment by wenbozhu** [comment]
You can use server-streaming with grpc to push messages to the client. The actual server-side support for something like a push service is out of the scope for grpc, e.g .knowing which node/process has the connection from a particular client session etc.  You may use websockets if you need bidi support from websockets, but you may have to use something like socket.io to deal with fallback (to HTTP) etc.
