### ISSUE TITLE
Use grpc-web without envoy

### ISSUE THREAD

**Issue by deepankarsharma** [grpc/grpc-web#750]
Is it possible to use grpc-web without envoy? Ideally would like some solution that works out of the box on debian / ubuntu. The last supported ubuntu release for envoy is bionic beaver which is getting long in the tooth.

**Comment by clehene** [comment]
You can use it with ESP https://github.com/cloudendpoints
Here's a kubernetes deploy fragment
```yaml
   spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1.46.0
        args: [
          "--ssl_port=8443",
          "--service=[YOUR SERVICE]",
          "--cors_preset=basic",
          "--cors_expose_headers=custom-header-1,grpc-status,grpc-message",
          "--cors_allow_headers=authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,x-api-key",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:8000",
          "-z", "healthz"
        ]
```

**Comment by stanley-cheung** [comment]
Envoy is just the default implementation. We are working on a Java in-process gateway. There is a Go implementation out there. But currently there is no direct way of connecting a grpc-web browser client to a grpc backend without a gateway or a proxy that understands grpc-web.

**Comment by clehene** [comment]
@stanley-cheung since grpc-web is concerned with browser libraries, would it make sense to have the java implementation as part of grpc-java (a module) rather than within grpc-web?

**Comment by deepankarsharma** [comment]
As a feature request - whatever option you develop please consider submitting it upstream as a package in debian / ubuntu repositories. As a user it is very convenient to be able to apt get the proxy. Envoy does have apt repositories but since it is not an upstream package, newer releases of envoy do not have a package.

**Comment by fr3fou** [comment]
can you use nginx as alternative?
