### ISSUE TITLE
Protobuf package, method and field level options

### ISSUE THREAD

**Issue by sharonjl** [grpc/grpc-web#765]
I can't find any documentation on this. Are there any package, method or field level options we can use to customize the output?

Specifically, looking for options for the output file names and type names.

**Comment by stanley-cheung** [comment]
Can you tell us more details about what you want to achieve?

The `protoc-gen-grpc-web` plugin has an `,out=<custom file name>` option you can pass to customize the output file name. 

I am not sure what you mean by custom type name though.

**Comment by ben-xD** [comment]
@stanley-cheung, is `,out=` documented somewhere?

I am looking/hoping for a different option, but I can't find documentation for any of these options.
