### ISSUE TITLE
protoc-gen-grpc-web not working for windows 10 even though path is set 

### ISSUE THREAD

**Issue by AKASH209BC** [grpc/grpc-web#767]
Error :- 
returns protoc-gen-grpc-web' is not recognized as an internal or external command, operable program or batch file. 

--grpc-web_out: protoc-gen-grpc-web: Plugin failed with status code 1.

I am using protoc-gen-grpc-web-1.0.7-windows-x86_64.exe and have saved it in C:\protoc-gen-grpc-web location 
My path is set as C:\protoc-gen-grpc-web in system path

![gitpro](https://user-images.githubusercontent.com/33162645/77820449-75e76f00-7108-11ea-879b-0d8d1c946e47.PNG)

**Comment by stanley-cheung** [comment]
Is it executable?

**Comment by AKASH209BC** [comment]
It was executable. 
Ya , the issue got resolved.
I did the following:-
1. Set the name of the protoc-gen-grpc-web-1.0.7-windows-x86_64.exe to protoc-gen-grpc-web.exe.
2. Path as C:\protoc-gen-grpc-web

**Comment by forconz** [comment]
```
# How to use
# Git Bash Here， .\\scripts\\gen.sh
# npm run gen:proto

BASEDIR=$(dirname "$0")
cd ${BASEDIR}/../

NODEMODULES=".\\node_modules"

PROTO_DIR="./proto"
GRPC_OUT="./src/grpc"
GRPC_TOOLS_NODE_PROTOC="${NODEMODULES}\\protoc\\protoc\\bin\\protoc.exe"

mkdir -p  #${GRPC_OUT}

rm -rf ${GRPC_OUT}/*

$GRPC_TOOLS_NODE_PROTOC -I="$PROTO_DIR" wechat.proto \
    --js_out=import_style=commonjs,binary:$GRPC_OUT \
    --grpc-web_out=import_style=typescript,mode=grpcwebtext:$GRPC_OUT    

# TypeScript compiling
#tsc
```

$ .\\scripts\\gen.sh
'protoc-gen-grpc-web' is not recognized as an internal or external command,
operable program or batch file.
--grpc-web_out: protoc-gen-grpc-web: Plugin failed with status code 1.

I did the following:-

Set the name of the protoc-gen-grpc-web-1.0.7-windows-x86_64.exe to protoc-gen-grpc-web.exe.
Path as C:\protoc-gen-grpc-web

the issue did not resolved.

**Comment by ishan2790** [comment]
I tried to run the command from cmd prompt instead of VS code terminal. It worked for from there.
