### ISSUE TITLE
Getting error: code: 2 message: "Http response at 400 or 500 level"

### ISSUE THREAD

**Issue by reselbob** [grpc/grpc-web#769]
Hi:

I am writing a [grpc-web client](https://github.com/reselbob/simple-node-grpc/tree/create-simple-web-client) that goes up against my Node.js gRPC API server running at localhost:8080 on a MAC OS version 10.15.3

Here is the branch of the project under development: [`https://github.com/reselbob/simple-node-grpc/tree/create-simple-web-client`](https://github.com/reselbob/simple-node-grpc/tree/create-simple-web-client).

I am getting the following error message at line 14 of this file: [`https://github.com/reselbob/simple-node-grpc/blob/create-simple-web-client/client/index.js`](https://github.com/reselbob/simple-node-grpc/blob/create-simple-web-client/client/index.js) from within the Chrome browser (Version 80.0.3987.149 (Official Build) (64-bit)).

```
err:
code: 2
message: "Http response at 400 or 500 level"
metadata: undefined
```
Here is the code in index.js where I call the gRPC API's ping() function:

```
module.exports = {
    ping: function(data, callback){
        const request = new PingRequest();
        request.setData(data);
        const metadata = {"content-type": "application/grpc-web"};
        client.ping(request, metadata, function(err, response) {
            callback(err, response.result)
        })
    },
    simplePing: function(data){
        return data;
    }
};
```
I am at a loss trying to understand what  I am doing wrong. I have searched the Internet but have not found any information that is helpful. Thanks in advance for any assistance you can provide.

**Comment by 86** [comment]
Are you running Envoy? If not, follow the instructions: https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld#configure-the-proxy

**Comment by reselbob** [comment]
I am not.

Thanks! 

Educate me, please. Why do I need to proxy over Envoy?

**Comment by 86** [comment]
This issue will help you. It looks like the browser API is not enough. https://github.com/grpc/grpc-web/issues/347
