### ISSUE TITLE
Http download support via grpc web proxy

### ISSUE THREAD

**Issue by jvmlet** [grpc/grpc-web#770]
Hello
Does it make sense to support http download via grpc web proxy? 
The proxied grpc call should have the predefined response proto message, like bytes, extension, content type, filename ect., everything needed to produce the valid http response for download. 
The grpc web spec  will include  response proto message definition and proxy implementation will have special treatment for service call that returns this particular message type to feed http response accordingly.
Thanks

**Comment by wenbozhu** [comment]
This is out of the scope for grpc-web, because there is no "grpc-web" client involved. 

Maybe you want to check what Envoy supports to map different HTTP message protocols to gRPC and protobuf?

**Comment by jvmlet** [comment]
I'm just asking to provide and publish specification for grpc response message (proto) that should be treated as 'download' by grpc web proxy. If this repo is not the appropriate place for such proposal, please point me to the right  repo. Thanks

**Comment by wenbozhu** [comment]
You may want to discuss your idea on https://github.com/envoyproxy/envoy

**Comment by jvmlet** [comment]
Envoy is custom implementation of grpc web specification. If  you don't think this proposal should be part of specification I give up.

**Comment by wenbozhu** [comment]
Right, this is not for grpc-web to specify or implement. Thanks for the inputs.
