### ISSUE TITLE
Hello World example failing on npm install of grpc

### ISSUE THREAD

**Issue by isabelgk** [grpc/grpc-web#781]
I am trying to run the Hello World [example](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld), and I have been having issues with installing the grpc dependency.

I hit an error with `npm install`.

A snippet of the output is:
```
13226 verbose pkgid grpc@1.24.2
13227 verbose cwd /home/ubuntu/grpc-web/net/grpc/gateway/examples/helloworld
13228 verbose Linux 4.15.0-96-generic
13229 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
13230 verbose node v13.12.0
13231 verbose npm  v6.14.4
13232 error code ELIFECYCLE
13233 error errno 6
13234 error grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
13234 error Exit status 6
13235 error Failed at the grpc@1.24.2 install script.
13235 error This is probably not a problem with npm. There is likely additional logging output above.
```

The full output is here: [error.log](https://github.com/grpc/grpc-web/files/4457954/error.log).

I found there were [others having issues](https://github.com/grpc/grpc-node/issues/1183) with grpc and node versioning, but I have not had any success using any combination of Node v.13.x, v.12.x, v.8.x and grpc@1.23.x, grpc@1.24.x. All of these have the same issue.

I am running Ubuntu 18.04 on VMWare Workstation Pro 15.

**Comment by stanley-cheung** [comment]
hm, I cannot reproduce. I can run `npm install` from the `net/grpc/gateway/examples/helloworld` directory just fine. It installed the `grpc` npm package @1.24.2. I am using `node` version 12.15.0 and `npm` version 6.13.4.

But in any case this seems like an issue to be raised with the grpc/grpc-node repo instead.

**Comment by isabelgk** [comment]
Thanks for the quick response. I tried using `node` v12.15.0 and `npm` v6.13.4 without any luck. 

I will close this and move the issue over to the grpc/grpc-node repo.
