### ISSUE TITLE
Repeated base type (int32, double, ...) issue

### ISSUE THREAD

**Issue by FaustmannChr** [grpc/grpc-web#783]
We had an issue with repeated base types, which works with the standard implementation of grpc. Only the grpc-web implementation has this issue.

example (not working):
```
message data {
   repeated int32 item = 1;
}
```

working example:
```
message data {
   repeated wrapperItem item = 1;
}

message wrapperItem {
   int32 item = 1;
}
```

**Comment by simonmau** [comment]
+1

**Comment by stanley-cheung** [comment]
@FaustmannChr can you give us more information about what's not working? Perhaps you can provide us some code snippet?
