### ISSUE TITLE
Feature Request: support client side streaming

### ISSUE THREAD

**Issue by mrmeku** [grpc/grpc-web#789]
Here's the use case I'm wanting to support with GRPC web that currently is not supported:

Imagine you want to make a web interface where you can upload a very large file (400GB as an example)

In a single request, browser's disallow you to send more than 4GB typically (its not part of the HTTP post spec, but is a limiation imposed by each respective browser)

Thus you might consider using a GRPC client stream to send the file down in chunks.

However, GRPC web currently does not generate any code hooks to do client side streaming to a GRPCWeb server.

Also, I just want to say how awesome it has been to use GRPC web in my personal and work projects. Its really wonderful! Keep up the great work.

**Comment by stanley-cheung** [comment]
See #24. It has been in our future road map.
