### ISSUE TITLE
How to reduce the size of compiled.js

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc-web#79]
Hello,

As I understand, there are 3 main parts that make the bundle:

1. grpc-web library
2. protobuf library
3. messages and service definitions from the **.proto** file.

for a simple grpc service (10 rpc methods, 20 messages definitions), the ```compiled.js``` produced by running ```closurebuilder.py``` is around **400KB**.

Is there any way to make this bundle smaller ? Any insights on which JS files weights the most into these 400KB ?

My second question is, when using **[closurebuilder.py](https://developers.google.com/closure/library/docs/closurebuilder)**, I need to specify a ```namespace="proto.packageName.serviceNameClient"``` flag. How to handle the case where I have 2 or 3 services defined in my protos files? Should I repeat the command, with a different namespace for each compiler run? I don't want to produce 3 bundles, with the same [grpc-web library](https://github.com/grpc/grpc-web/tree/master/javascript/net/grpc/web) and [protobuf JS library](https://github.com/google/protobuf/tree/a428e42072765993ff674fda72863c9f1aa2d268/js) repeated in each of these bundles...

Finally, in the [grpc-web JS libary](https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/gatewayclientbase.js), I can see many required files like this:
```js
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.Status');
goog.require('grpc.web.StatusCode');
```
May I ask where these dependencies are located ? I'm considering the option to build the compiled.js with something like webpack instead of **[closurebuilder.py](https://developers.google.com/closure/library/docs/closurebuilder)**.

Many thanks

**Comment by stanley-cheung** [comment]
Now that our [`grpc-web` NPM package](https://www.npmjs.com/package/grpc-web) is live, there should be more ways to compile, compact, uglify, minimize, etc, the compiled JS files. If this is still a concern, please re-open.
