### ISSUE TITLE
No access to stream method in generated JS

### ISSUE THREAD

**Issue by reintroducing** [grpc/grpc-web#793]
Hello,
Before I ask my question, I just want to be transparent that I'm a complete newbie when it comes to grpc/protos so if I misspeak in any way please excuse me. I'm a FE dev trying to implement some output JS from a proto file on the web and am running up against a wall. The proto in question is this:

```
service FoodLogService{
    rpc CreateFoodLog (stream CreateFoodLogRequest) returns (FoodLog);
    rpc GetFoodLogHistory (GetFoodLogHistoryRequest) returns (stream FoodLog);
    rpc GetFoodLogHistoryAsArray (GetFoodLogHistoryRequest) returns (FoodLogs);
    rpc UpdateFoodLog (UpdateFoodLogRequest) returns (FoodLog);
    rpc DeleteFoodLog (DeleteFoodLogRequest) returns (google.protobuf.Empty);
}
```

For every method on this client I've been able to call it from the output JS like so:
```js
Client.updateFoodLog();
Client.deleteFoodLog();
...etc
```

However, for the `createFoodLog` method, it's missing from the output JS. The mode on the compiler is set to `grpcwebtext`, but again, I don't understand the impact that will have on this particular issue. The only difference between the create rpc and the others that I can see is that the request param is passed as a stream, but I don't know if that is what is impacting the output JS. Unfortunately the people in charge of the compilation process don't speak JS so we're just going back and forth lobbing questions to each other in circles on this.

I'm kind of at a complete loss and standstill here, so any light that could be shed would be really appreciated.

**Comment by stanley-cheung** [comment]
Your `CreateFoodLog` method is considered client-side streaming. Together with bidi-streaming (where you put the `stream` qualifier to both request and response side), these types of RPCs were not supported currently because of browser API restrictions.

**Comment by reintroducing** [comment]
@stanley-cheung I really appreciate your quick response. What options/alternatives do we have, then, to create something the web supports to get this to work? Our mobile apps use these protos successfully but it sounds like we'll need to make some additional methods to support web, is that a fair assumption here?

**Comment by stanley-cheung** [comment]
Yea one workaround is to redesign / add other methods which does not involve streaming from the client side. See #24 for discussion around bidirectional streaming support for this library.

**Comment by reintroducing** [comment]
@stanley-cheung appreciate your help, thank you.
