### ISSUE TITLE
protoc-gen tool not separating classes from namespaces with `.`

### ISSUE THREAD

**Issue by barrymichaeldoyle** [grpc/grpc-web#805]
I've tried to explain my problem in detail over here: https://stackoverflow.com/questions/61528526/issue-with-typescript-definition-files-when-generating-proto-definitions-with-pr

**Comment by barrymichaeldoyle** [comment]
I see it's a similar issue to issue #693 

Which was closed 28 days, but I'm still experiencing the problem.

Apparently it was fixed here #780 but the tool hasn't been updated yet. When can we expect the next release?

**Comment by stanley-cheung** [comment]
Very soon, sorry about the delay.

**Comment by barrymichaeldoyle** [comment]
Thank you Stan!

**Comment by stanley-cheung** [comment]
`1.2.0` has been released.
