### ISSUE TITLE
TS Experimental status

### ISSUE THREAD

**Issue by dunkymole** [grpc/grpc-web#812]
Hi,

We are thinking about adopting grpc-web and having TS typings is a major reason to want to do so but the experimental designation is worrying. Can we have some degree of certainty that this feature will "graduate" out of "experimental"? If so any idea of the timeline?

Thanks

**Comment by stanley-cheung** [comment]
Unfortunately there is no timeline to graduate TypeScript support in this repo any time soon because there is the lack of official support from protobuf. And also we don't currently have the resources to polish this in the near term.
