### ISSUE TITLE
Limitation of 6 streams per browser per domain

### ISSUE THREAD

**Issue by OwenDelahoy** [grpc/grpc-web#814]
While working on an application that opened many long-lived server-streams in a single page, I was puzzled to find many of the connections were continuously pending. Initially I thought this might be related to envoy configuration, or the nodejs server configuration. But after much searching, reconfiguration and experimentation, it seems the limit is not server side.

Rather, it seems like Chrome and Firefox impose a limit of 6 simultaneous HTTP 1.X connections per domain as documented [here](https://developer.mozilla.org/en-US/docs/Web/API/EventSource). Apparently websockets are [exempt](https://stackoverflow.com/a/32704207/104383) from this limit.

To save other people time, it would be helpful to document this limitation.

**Comment by stanley-cheung** [comment]
Discussion in #522
