### ISSUE TITLE
ERROR: Service 'prereqs' failed to build:

### ISSUE THREAD

**Issue by yangboz** [grpc/grpc-web#817]
ERROR: Service 'prereqs' failed to build: The command '/bin/sh -c bazel build javascript/net/grpc/web/... &&   cp $(bazel info bazel-genfiles)/javascript/net/grpc/web/protoc-gen-grpc-web   /usr/local/bin/protoc-gen-grpc-web' returned a non-zero code: 1'
on
```
inux vultr.guest 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
docker
```
Docker version 19.03.6, build 369ce74a3c
```
```
docker-compose
```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```
any idea? thanks.

**Comment by stanley-cheung** [comment]
What was the original command that you ran?

**Comment by yangboz** [comment]
my bad, the root cause was less memory to build docker image ,out of memory, after increased the mormry to 2G, issue resolved, thanks.
