### ISSUE TITLE
gRPC Error (12, unknown service BookService)

### ISSUE THREAD

**Issue by sfm1977** [grpc/grpc-web#829]
Hi,

I'm  trying to use grpc-web in flutter web after a few days, i can't put thinks working with a golang server and flutter web app. 

I'm using https://github.com/improbable-eng/grpc-web. My server code:

`func main() {

	grpcServer := grpc.NewServer()
	bookpb.RegisterBookServiceServer(grpcServer, &bookService{})
	grpclog.SetLogger(log.New(os.Stdout, "exampleserver: ", log.LstdFlags))

	wrappedServer := grpcweb.WrapServer(grpcServer)
	handler := func(w http.ResponseWriter, req *http.Request) {

		w.Header().Add("Access-Control-Allow-Origin", "*")
		w.Header().Add("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
		w.Header().Add("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-User-Agent, X-Grpc-Web")
		w.Header().Add("grpc-status", "")
		w.Header().Add("grpc-message", "")

		if req.Method == "OPTIONS" {
			w.WriteHeader(http.StatusOK)
			return
		}

		wrappedServer.ServeHTTP(w, req)
	}

	httpServer := http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: http.HandlerFunc(handler),
	}

	grpclog.Printf("Starting server. http port: %d", port)

	if err := httpServer.ListenAndServe(); err != nil {
		grpclog.Fatalf("failed starting http server: %v", err)
	}
}`

In my flutter web app i have this code:

`
Future<Book> doRemoteCall() async {
  final channel = GrpcWebClientChannel.xhr(Uri.parse('http://localhost:9090'));
  final client = BookServiceClient(channel);
  

  GetBookRequest req = GetBookRequest();
  req.isbn = 1;

  return await client.getBook(req);
}`

When i run my flutter web app in chrome i got this error:

> errors.dart:165 Uncaught (in promise) Error: gRPC Error (12, unknown service BookService)
    

    at Object.createErrorWithStack (errors.dart:247)
    at Object._rethrow (async_patch.dart:200)
    at async._AsyncCallbackEntry.new.callback (zone.dart:1175)
    at Object._microtaskLoop (schedule_microtask.dart:41)
    at _startMicrotaskLoop (schedule_microtask.dart:50)
    at async_patch.dart:166

but i start the service in Go server: bookpb.RegisterBookServiceServer(grpcServer, &bookService{})

I also used envoy proxy and didn't work using dart grpc-web with a golang server. Any idea?
Thanks,

**Comment by stanley-cheung** [comment]
I am not familiar with this `GrpcWebClientChannel.xhr(Uri.parse('http://localhost:9090'));`.

This is probably too many layers up for me to help trouble-shoot. 

If possible, please start with the [Helloworld](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld) to make sure at least grpc-web is working for you end-to-end in some form. Then you can switch one component at a time (i.e. server first, then client) to isolate the problem. 

Right now you are using many different components that may or may not be relevant to grpc-web. It would be pretty hard for me to help trouble-shoot.

**Comment by sfm1977** [comment]
Thanks @stanley-cheung, i manage to work with this example:

**Comment by sfm1977** [comment]
Sorry about this confusion, my solution is from another solution, so, once again, my apologies. That being said, i managed to set it work with envoy. Thanks again to @stanley-cheung, simply doing layer by layer did the trick.
