### ISSUE TITLE
Python Basic gRPC to HTTP examples

### ISSUE THREAD

**Issue by josiahlaivins** [grpc/grpc-web#830]
We have a python based gRPC server being served from a docker container. The server right now has the following config from [official tutorial](https://grpc.io/docs/languages/python/basics/):
```python
def serve(port=50051,n_workers=10):
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=n_workers))
    gpb.add_SomeBackendServicer_to_server(SomeBackend(),server)
    server.add_insecure_port(f'[::]:{port}')
    server.start()
    return server
```
We use docker run --network host to make things simple. We have a javascript web app that needs to communicate with this gRPC framework. We found we need to somehow use envoy for this.

We use `docker run --network host  envoyproxy/envoy:v1.14.1`

Using bloom RPC we found that the request hangs. This is good in that we know that envoy must be catching the HTTP request, this is bad in that nothing gets done with it. We see no easy documentation on how we are supposed to connect envoy to a typical gRPC backend. Our backend is running on port 50051, where do we put this?

![image](https://user-images.githubusercontent.com/55600928/83268281-6382c380-a193-11ea-9cb8-0053bd0c5ed2.png)

**Comment by stanley-cheung** [comment]
Here's a section in the `envoy.yaml` file where you direct traffic to the grpc backend:

https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L38-L44

And you refer to the service by its name after route matching: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L25
