### ISSUE TITLE
How to use protoc-gen-grpc-web tool on Windows

### ISSUE THREAD

**Issue by barrymichaeldoyle** [grpc/grpc-web#835]
I'm having issues setting up the protoc gen tool on a new Windows device (worked on the previous one).

Previously, the setup (over a year ago) was such a mission to accomplish, I couldn't find documentation anywhere for it.

Whenever I run my bash file (which works fine on the setup device) on my new device I get a `protoc: command not found` error. There's all this talk about adding it to the path (not very detailed), but I've tried a bunch of stuff and I'm getting nowhere.

Could someone please just post some simple friendly way to get the protoc gen tool working with ease on Windows.

Thanks.

**Comment by barrymichaeldoyle** [comment]
Still struggling with this, any pointers?

**Comment by newusersss** [comment]
@barrymichaeldoyle 

gRPC => gRPC-Web:

Install x64 *.exe \go\bin:
https://github.com/protocolbuffers/protobuf/releases/latest

Cmd goland or atom:
go get -u github.com/golang/protobuf/protoc-gen-go

Install x64 *.exe \go\bin:
https://github.com/grpc/grpc-web/releases

**Comment by stanley-cheung** [comment]
For Windows, you need to download a `protoc.exe` from the [protobuf release page](https://github.com/protocolbuffers/protobuf/releases) (it's usually in the form of protoc-x.y.z-win64.zip), and the `protoc-gen-grpc-web.exe` plugin from our grpc-web [release page](https://github.com/grpc/grpc-web/releases). Unfortunately we don't have a lot of resources dedicated to support the Windows platform.

**Comment by FakeCode** [comment]
I used below npm package to generate js grpc and pb
https://www.npmjs.com/package/protoc-gen-grpc?activeTab=readme
