### ISSUE TITLE
Cannot use grpc-web inside web worker

### ISSUE THREAD

**Issue by edyu** [grpc/grpc-web#838]
I'm using the dart version of grpc-web and when using it under web worker, the generated code is using window global object which is not available.

The line causing the problem is:
`_stub = grpc.Client(GrpcWebClientChannel.xhr(Uri.parse('http://${server}:${port}')));`

grpc.Client is generated code.

Here is the error output
<pre>
Uncaught ReferenceError: 
window is not defined
    at Object.main (worker.dart:28)
    at js_helper.dart:3221
    at js_helper.dart:3221
    at dartProgram (js_helper.dart:3221)
    at js_helper.dart:3221
</pre>

**Comment by stanley-cheung** [comment]
There's no support for making this work in service worker yet. Folding this under #587
