### ISSUE TITLE
Windows protoc: command not found

### ISSUE THREAD

**Issue by barrymichaeldoyle** [grpc/grpc-web#845]
When I try to run the following bash script:

```
protoc -I=$PROTO_DIR/                                      \
       --js_out=import_style=commonjs:./src/gen \
       --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:./src/gen
```

I get the following error:

> protoc: command not found

I've tried a bunch of stuff and it's not working.

Using Windows.

**Comment by jvmlet** [comment]
From readme : If you don't already have protoc installed, you will have to download it first from here.

**Comment by barrymichaeldoyle** [comment]
Done that. What do I do with the download?

**Comment by stanley-cheung** [comment]
You have to place it somewhere your `$PATH` can discover it as executable.

**Comment by barrymichaeldoyle** [comment]
I've done that and I still have the same problem :(

**Comment by jvmlet** [comment]
Have you extracted the zip file?

**Comment by barrymichaeldoyle** [comment]
Ahhhh, I've done a bunch more stuff and I've finally gotten it to work. But what's the point of using https://github.com/protocolbuffers/protobuf/releases over this https://github.com/grpc/grpc-web/releases ?

**Comment by stanley-cheung** [comment]
`protoc` is the main protocol buffer code generator tool. `protoc-gen-grpc-web` is a plugin that supplies additional capabilities to generate stub classes for grpc-web services.

**Comment by rohitkumar9989** [comment]
Ive extracted the protbuf file but i am still getting the error, I have pasted the extracted file into the directory iam working with, and when i executed the command its still showing the same error please help me with this
![Screenshot (44)](https://user-images.githubusercontent.com/69589867/162112397-6a0567f1-0c28-440a-b622-a9d6af8a41fa.png)
 This is the place where i attached the file and image_loc is the file iam working with
Thanks in advance

**Comment by kurushqosimi** [comment]
Have you solved this problem?
