### ISSUE TITLE
Update ts typings for support interceptors

### ISSUE THREAD

**Issue by Fl0pZz** [grpc/grpc-web#848]
https://github.com/grpc/grpc-web/issues/766

https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/index.d.ts

**Comment by jmzwcn** [comment]
Type 'StreamInterceptor[]' is not assignable to type 'string'.ts(2322)
user_grpc_web_pb.d.ts(147, 39): The expected type comes from this index signature.

**Comment by jmzwcn** [comment]
@stanley-cheung , yes it is a serious issue.

**Comment by jvmlet** [comment]
The workaround for this serious issue is  `@ts-ignore` :
```
new MyPromiseClient((url
                        , null,
                        {
                            //todo : remove ts-ignore once  https://github.com/grpc/grpc-web/issues/848 is resolved

                            // @ts-ignore
                            'unaryInterceptors': [new MyInterceptor()]
                        });
```
