### ISSUE TITLE
CORS indicator header auto indicator

### ISSUE THREAD

**Issue by mwitkow** [grpc/grpc-web#85]
@wenbozhu we hit a little snag in our implementation. 

If a user wants to expose other HTTP methods other than gRPC, the CORS handling must not accept requests other than the ones registered on the gRPC server. However, there's no way of telling what `Content-Type` the CORS pre-flight check is.

We've worked around this by:
 a) allowing the user to automatically register all methods of the gRPC server in our gRPC-Go wrapper
 b) allowing the user to whitelist all CORS automatically that carry `x-gprc-web` header in the pre-flight requests `Access-Control-Request-Headers`

we'd like to extend the spec to make sure that all gRPC-Web requests have the `x-grpc-web`: `1` header added to them to so we can enable this auto-cors thing.

@MarcusImprobable  for context.

**Comment by n0mer** [comment]
@stanley-cheung reviewed this, so @mwitkow review is not necessary and this issue can be closed?
