### ISSUE TITLE
d.ts generation incorrect use of import

### ISSUE THREAD

**Issue by ajs117** [grpc/grpc-web#855]
import * as common_pb from './common_pb'; 

gets used like

 getVehicles(): common_pbVehicleList | undefined;

there needs to be a . between pb and V

**Comment by stanley-cheung** [comment]
Can you share your `.proto` so that I can try to reproduce? This is highly likely fixed in #837, which will come in the next release, soon.

**Comment by ajs117** [comment]
I can’t share it I’m afraid. However I can give an example:

common.proto
‘’’ message Something { int32 id = 1 } ‘’’

a.proto (imports common)
‘’’ message ThingsList { repeated Something somethings } ‘’’

https://github.com/grpc/grpc-web/issues/837 looks like it is probably the same issue.
