### ISSUE TITLE
Universal SSR use case

### ISSUE THREAD

**Issue by optiman** [grpc/grpc-web#856]
Modern frontend frameworks such as [Nuxt.js](https://nuxtjs.org) allow us to write isomorphic web applications in a way that first loaded page is generated on the server side (Node.js) while all following pages are rendered in the browser as normal SPA.
This approach has many benefits such as single code base, better SEO, faster time-to-content.
Unfortunately, `grpc-web` is using only `XMLHttpRequest` to make requests, which is not available in Node.js environment. 
This fact forces to use separate clients and generated stubs for Node.js (https://github.com/grpc/grpc-node) and browser (this library) unlike alternative solution from Improbable, which offers the abilty to use custom transport [`@improbable-eng/grpc-web-node-http-transport`](https://www.npmjs.com/package/@improbable-eng/grpc-web-node-http-transport) for SSR.
I would very much prefer to use the official solution made by the gRPC team, but it seems that this is imposible at the moment.

Are there any plans to support such usage of `grpc-web` or will it remain browser-only for the foreseeable future?

**Comment by stanley-cheung** [comment]
Yes this project will remain browser-only for the foreseeable future. #630
