### ISSUE TITLE
add FromObject or Parse method to protobuf messages

### ISSUE THREAD

**Issue by mmohaveri** [grpc/grpc-web#875]
I'm trying to find a way to populate a protobuf message from based on data from an object in a programmatic way.

currently we can do the opposite:

`
message User {
   string user = 1;
}
`

`
obj = new User().toObject()
`

I want a way to do the reverse operation like:
```
obj = {
   user: "user name"
}

protoUser = new User()
ParseFromObject(protoUser, obj)
```

We have something similar in other languages (like python) but I failed to find it in documentation or code. Am I missing something? or currently there is no way of doing what I want to do?

**Comment by cyberco** [comment]
I've been looking at this very problem for the passed week and I'm sorry to say there is no easy solution for this glaring ommission. This discussion sums the problem up pretty neatly (including a post by me wrt my specific use case):
https://github.com/protocolbuffers/protobuf/issues/1904

Structs can get you a bit along the way. See for instance:
https://medium.com/@waynelpu/how-to-pass-plain-javascript-object-with-gprc-94a91906ab1c
But if you have a proto message in your JSON you cannot simply do message.toObject() to get the JSON. I instead use this hack to get JSON that *will* be accepted by a struct:
https://github.com/grpc/grpc-web/issues/315#issuecomment-428016723

But getting back from that JSON to a message is still something I haven't figured out. See:
https://stackoverflow.com/questions/62763078/protobuf-message-from-json-in-javascript

**Comment by stanley-cheung** [comment]
This is more of a Protobuf API question, not a grpc-web question.

**Comment by NicksonYap** [comment]
It is indeed a Protobuf issue, not gRPC

Weirdly, `protobuf.js` supports converting plain objects to protobuf object but `google-protobuf` does not

A probable solution for simple protos:

This is not supported:
```js
var obj = {
   user: "username",
  full_name: "userfullname"
}

var protoUser = new User(obj)
```

This is supported: (and if this works for you, **this is preferred**)
```js
var arr = ["username, "userfullname"]

var protoUser = new User(arr)
```

We need a way convert obj to array 

**Is there a way to loop through the fields that are defined and read them from the object to form the array?**

A very  **dangerous** way would be to use `Object.values()`
 But the order of the resulting array is not guaranteed and will cause **the fields to be swapped**.

```js
var obj = {
  user: "username",
  full_name: "userfullname"
}

var arr = Object.values(obj) //gives ["username, "userfullname"]

var protoUser = new User(arr)

console.log(protoUser.toObject())
/*
{
  user: "username",
  full_name: "userfullname"
}
*/
```


```js
var obj = {
  full_name: "userfullname"
  user: "username",
}

var arr = Object.values(obj) //gives ["userfullname, "username"]

var protoUser = new User(arr)

console.log(protoUser.toObject())
/* 
WRONG!!!
{
  user: "userfullname",
  full_name: "username"
}
*/
```

**Comment by Volankey** [comment]
> I'm trying to find a way to populate a protobuf message from based on data from an object in a programmatic way.
> 
> currently we can do the opposite:
> 
> `message User { string user = 1; }`
> 
> `obj = new User().toObject()`
> 
> I want a way to do the reverse operation like:
> 
> ```
> obj = {
>    user: "user name"
> }
> 
> protoUser = new User()
> ParseFromObject(protoUser, obj)
> ```
> 
> We have something similar in other languages (like python) but I failed to find it in documentation or code. Am I missing something? or currently there is no way of doing what I want to do?

You can try this library https://github.com/Volankey/grpc-web-from-object.

**Comment by infodusha** [comment]
So I was also digging into this and i have built my own package
https://github.com/infodusha/grpc-web-from-object
That one is similar to @NicksonYap idea except is is **type-safe and may be nested**.

**Comment by jaqxues** [comment]
Any updates?

The absence of this feature makes grpc-web pretty unusable. Not being able to do
```ts
client.doSomething({id: "12345", somethingElse: 124})
```

but having to do this is ridiculous. Frankly not representative of a well-thought eco-system... (if I am not missing something huge).
```ts
const doSomethingReq = new DoSomethingRequest()
doSomethingReq.setId("12345")
doSomethingReq.setSomethingElse(124)
client.doSomething(doSomethingReq)
```
