### ISSUE TITLE
Add setter and getter functions for message properties

### ISSUE THREAD

**Issue by mmohaveri** [grpc/grpc-web#876]
I'm using grpc-web for communicating between my VueJS app and my backend.
Currently I store javascript objects in my store, and have to manually convert them to and from protobuf messages for API calls.
I prefer to directly use some of the protobuf messages to store information in the store but the problem is protobuf messages do not define setter and getter properties on them, so I won't be able to do something like `message.prop = val`.

What I'm proposing is to add setters and getter to protobuf messags so instead of `message.setProp(val)` and `val = message.getProp()` I'll be able to say `message.prop = val` and `val = message.prop`.

This way not only the final code would be much cleaner, but also I'll be able to use protobuf messages directly in Vuex stores while taking advantage of VueJS reactivity core.

**Comment by stanley-cheung** [comment]
This is a Protobuf question, not a grpc-web question.
