### ISSUE TITLE
UnaryInterceptor not called

### ISSUE THREAD

**Issue by dmaixner** [grpc/grpc-web#877]
I guess this is going something forgotten on my side, but after spending some time with this I have to ask.

### Description

Backend is in Go. Using Envoy for proxy. Svelte for frontend.

My proto file is pretty simple:
```javascript
...
message HelloResponse {
    string name = 1;
}

message IdRequest {
    int32 id = 1;
}

service Backend {
    rpc GetHello (IdRequest) returns (HelloResponse) {}
}
```

I have used updated [unary interceptor from blog post](https://grpc.io/blog/grpc-web-interceptor/#unary-interceptor-example):
```javascript
  const SimpleUnaryInterceptor = function () {};
  SimpleUnaryInterceptor.prototype.intercept = function (request, invoker) {
    console.log("test1");
    const reqMsg = request.getRequestMessage();
    reqMsg.setId("[Intercept request]" + reqMsg.getId());
    return invoker(request).then((response) => {
      console.log("test2");
      const responseMsg = response.getResponseMessage();
      responseMsg.setName("[Intercept response]" + responseMsg.getName());
      return response;
    });
  };
```

I have bound it to the client via opts:
```javascript
  let opts = { 'unaryInterceptors': [new SimpleUnaryInterceptor()] };
  let client = new protobuf.BackendClient("https://myserver:8092", null, opts);
```

I have this simple request/response code:
```javascript
  let request = new protobuf.IdRequest();
  request.setId(3);
  client.getHello(request, {}, (err, response) => {
    console.log(response.getName());
  });
```

### Problem
Request and response work fine, but interceptor doesn't seem to be run at all. In console log I can see only response data from server, but nothing from interceptor. Can someone please tell me, what am I missing here?

Thank you.

**Comment by stanley-cheung** [comment]
So I noticed that you are doing this:
```
 let opts = { 'unaryInterceptors': [new SimpleUnaryInterceptor()] };
```
but are using the callback-based API:
```
  client.getHello(request, {}, (err, response) => {
    console.log(response.getName());
  });
```
Your interceptor is meant to be used with the Promise-based client. So you can either change your `opts` to
```
let opts = { 'streamInterceptors': [new SimpleUnaryInterceptor()] };
```
or change your client to the Promise-based client
```
let client = new protobuf.BackendPromiseClient("https://myserver:8092", null, opts);
```
and then use the Promise-based API
```
client.getHello(request, {}).then((response) => {
  ...
});
```

**Comment by dmaixner** [comment]
Thank you very much for fast response @stanley-cheung. 👍 

Feels a bit strange that unary interceptors are related to promise-based client (but unary requests are not), even though I guess there is some good reasoning in that.

If I would change to 'streamInterceptors', I would need to change the interceptor implementation as well, right? To look like this: https://grpc.io/blog/grpc-web-interceptor/#stream-interceptor-example. In the blog post, there is missing info about eventType can be also `metadata`, which I find useful. Since I'm not using streaming yet, I'm going to use PromiseClient.

With this, my `SimpleUnaryInterceptor` is called and request is modified with no problems.

But still, I have problem with response. I can see message is returned, but it seems symbols are lost from `UnaryResponse` class -- it says `e.getMetaData is not a function`. I guess the problem is in closure compiler settings? File `grpc-web\packages\grpc-web\externs.js` doesn't contain any `UnaryResponse` methods. If somebody finds this too, **it seems this should be hopefully fixed with https://github.com/grpc/grpc-web/commit/550c8d2375ae549917935ca78db69991b3521ddb.**

**Comment by jvmlet** [comment]
Sorry for hijacking the thread, but I can't even typescript compile the code that uses `options` parameter :
```js
const adminClient = new MyServicePromiseClient(url,
                        null,
                        {'unaryInterceptors': [new SimpleUnaryInterceptor()]});
```
getting `error TS2322: Type 'any[]' is not assignable to type 'string'.`

The `d.ts` that gets generated :
```js
export class MyServicePromiseClient{
  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
             options?: null | { [index: string]: string; }); // string to string ????
}
```

**Comment by DevsAnon** [comment]
Version this is included in?
