### ISSUE TITLE
Does grpc-web support google.protobuf.Any type?

### ISSUE THREAD

**Issue by zhanghepeng** [grpc/grpc-web#891]
Does grpc-web support Any type? If so, is there a typescript demo?

**Comment by joe-getcouragenow** [comment]
Also need to know.

**Comment by stanley-cheung** [comment]
@zhanghepeng What do you mean by support the Any type?

**Comment by joe-getcouragenow** [comment]
It's an arbitrary type for Protocol Buffers.

https://developers.google.com/protocol-buffers/docs/proto3#any

**Comment by stanley-cheung** [comment]
What would it mean to be supporting the Any type in grpc-web? Seems like a protobuf question?

**Comment by joe-getcouragenow** [comment]
It means you can then embed other types inside 

here is an example: https://github.com/cloudstateio/cloudstate/blob/master/protocols/protocol/cloudstate/crdt.proto

**Comment by Yannic** [comment]
For `gRPC-Web`, there's nothing special about `google.protobuf.Any`. It's supported like any other message type.

That said, there's one caveat when using TypeScript: `Any` contains convenience methods like `pack` or `unpack` [1] which, AFAICT, are not part of the `any.d.ts` generated by `protoc-gen-grpc-web`.

[1] https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/js/well_known_types_embed.cc

**Comment by zhanghepeng** [comment]
> It means you can then embed other types inside
> 
> here is an example: https://github.com/cloudstateio/cloudstate/blob/master/protocols/protocol/cloudstate/crdt.proto

Thank you
