### ISSUE TITLE
[Question] Missing metadata on responses

### ISSUE THREAD

**Issue by AudriusButkevicius** [grpc/grpc-web#899]
Hi,

I have a grpc web client calling a unary call which returns a stream of responses from the service,
the service also injects a X-Custom-Header in the response. 

I can see the X-Custom-Header in Chrome developer tools on the request coming back, from the service as well as 
`Access-Control-Expose-Headers: X-Custom-Header`, yet `status.metadata` in `stream.on('status', ...)` is always empty.

Is there a special naming convention that needs to be used to get the headers back in the status object?

Thanks

**Comment by AudriusButkevicius** [comment]
It seems that `on('status', ...)` provides the trailers not headers, which I am not sure how you even set them from Java.
Also, as this goes via envoy, I am not sure where they end up.

However it seems there is an undocumented `on('metadata', ...)` which provides the headers.

**Comment by stanley-cheung** [comment]
Yes they are 2 separate grpc concepts: `on('metadata'. ...)` returns the _initial_ metadata, which in grpc-web, is the response headers. `on('status', ...)` returns the _trailing_ metadata, which are encoded in the response stream itself.

**Comment by AudriusButkevicius** [comment]
I am not exactly sure how one distinguishes between the two, because in java grpc there is just metadata, so I guess the decision of what goes where happens in envoy?

The 'metadata' event took digging in the source code to find.

I guess this ticket should be repurposed as a suggestion to improve the documentation

**Comment by stanley-cheung** [comment]
Yes, the documentation should be improved.

In Java, here's a bit in our interop test that distinguish between initial metadata vs trailing metadata: https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java#L442. There's `trailers` concept.

**Comment by AudriusButkevicius** [comment]
Thanks, learned something new today.
