### ISSUE TITLE
Envoy crashes on to start due to invalid envoy.yaml from example

### ISSUE THREAD

**Issue by daltonj** [grpc/grpc-web#902]
The current example cors configuration does not load the envoy server.

error initializing configuration '/etc/envoy/envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:
[info][main] [source/server/server.cc:512] exiting
Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].cors) allow_origin_string_match: Cannot find field.):

Full message:
[critical][main] [source/server/server.cc:86] error initializing configuration '/etc/envoy/envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].cors) allow_origin_string_match: Cannot find field.): {"static_resources":{"clusters":[{"load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":8070,"address":"localhost"}}}}]}],"cluster_name":"cluster_0"},"lb_policy":"round_robin","http2_protocol_options":{},"type":"logical_dns","name":"ad_service","connect_timeout":"0.25s"}],"listeners":[{"filter_chains":[{"filters":[{"typed_config":{"http_filters":[{"name":"envoy.filters.http.grpc_web"},{"name":"envoy.filters.http.cors"},{"name":"envoy.filters.http.router"}],"route_config":{"virtual_hosts":[{"cors":{"max_age":"1728000","allow_headers":"keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout","expose_headers":"custom-header-1,grpc-status,grpc-message","allow_origin_string_match":[{"prefix":"*"}],"allow_methods":"GET, PUT, DELETE, POST, OPTIONS"},"routes":[{"route":{"max_grpc_timeout":"0s","cluster":"echo_service"},"match":{"prefix":"/"}}],"name":"ad_service","domains":["*"]}],"name":"local_route"},"stat_prefix":"ingress_http","@type":"type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager","codec_type":"auto"},"name":"envoy.filters.network.http_connection_manager"}]}],"name":"listener_0","address":{"socket_address":{"port_value":8080,"address":"0.0.0.0"}}}]},"admin":{"address":{"socket_address":{"port_value":9901,"address":"0.0.0.0"}},"access_log_path":"/tmp/admin_access.log"}}

My envoy file is the latest from with the service name changed:
https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml

I'm using the latest version of Envoy:
FROM envoyproxy/envoy:latest

**Comment by stanley-cheung** [comment]
Does `FROM envoyproxy/envoy:latest` still exist? I thought Envoy team removed that a while ago. I searched on docker hub and can't find it either https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&name=latest. Perhaps what you had was a cached older version?

**Comment by daltonj** [comment]
This seems quite likely.  I switched to a pinned version v1.15.0 and it seems to be OK.   I think we can close this then. 

On an unrelated note my grpc service with envoy now fails with a different error:
upstream connect error or disconnect/reset before headers. reset reason: connection failure

And I see in the logs:
call failed on attempt 0 with err=rpc error: code = Unavailable desc = The service is currently unavailable., retrying.

Presumably some magic envoy / grpc configuration yaml is needed.  Also, unrelated - an example that uses SSL would very helpful.

**Comment by daltonj** [comment]
Calling this specific issue closed.
