### ISSUE TITLE
[Question]How to get response header with 'PromiseClient'?

### ISSUE THREAD

**Issue by kybetter** [grpc/grpc-web#904]
e.g:
```js
import { FooPromiseClient } from './SearchService_grpc_web_pb';

const fooService = new FooPromiseClient('http://xxx.xxx');

fooService.foo(someRequest).then(response => {
  // I can only get response body here, How can I get response header, please help me.
})

```

**Comment by stanley-cheung** [comment]
You will need to write an Interceptor to get access to the metadata. See the blog post: https://grpc.io/blog/grpc-web-interceptor/#unary-interceptor-example

**Comment by kybetter** [comment]
> You will need to write an Interceptor to get access to the metadata. See the blog post: https://grpc.io/blog/grpc-web-interceptor/#unary-interceptor-example

Thank you! But Where do I get 'UnaryInterceptor' interface? I don't know how to get it.

Should I download it from here? https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/interceptor.js
