### ISSUE TITLE
"TypeError: request.serializeBinary is not a function"

### ISSUE THREAD

**Issue by ZhangDewei** [grpc/grpc-web#906]
When I use grpc-web to request grpc-backend, panic the err: "TypeError: request.serializeBinary is not a function", I use proto way is :protoc -I. --js_out=import_style=commonjs:./fe/src/api/ --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./fe/src/api/ xxx.proto

**Comment by stanley-cheung** [comment]
@ZhangDewei This has come up several times in the past: #566, #377, but it was never really clear what went wrong, so we need a lot more information about your particular situation to proceed.

Can you give us more information on how to reproduce this? Can you give us
- a simplified version of your .proto
- the ` protoc` command
- your `package.json` file
- your main `client.js`, which imports these generated files
- when exactly did this error happen? does this happen during compile time? Or does this happen at runtime, in the browser?
- If this happens at runtime in the browser, how did you compile your javascript files? 

Please be as detail as possible. Thanks.

**Comment by ZhangDewei** [comment]
> @ZhangDewei This has come up several times in the past: #566, #377, but it was never really clear what went wrong, so we need a lot more information about your particular situation to proceed.
> 
> Can you give us more information on how to reproduce this? Can you give us
> 
> * a simplified version of your .proto
> * the ` protoc` command
> * your `package.json` file
> * your main `client.js`, which imports these generated files
> * when exactly did this error happen? does this happen during compile time? Or does this happen at runtime, in the browser?
> * If this happens at runtime in the browser, how did you compile your javascript files?
> 
> Please be as detail as possible. Thanks.

Thank you. The problem is solved

**Comment by Enrikerf** [comment]
How do you solved @ZhangDewei ? I am getting the same error

**Comment by wilywork** [comment]
i have same problem.

driver's:
*protoc-3.20.1-win64 (version 3.21.12 not work, reason: protoc-gen-js not found)
*protoc-gen-grpc-web-1.4.2-windows-x86_64

command:
```
protoc -I=src/assets/proto helloworld.proto --js_out=import_style=commonjs:./src/assets/dist_proto --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:./src/assets/dist_proto
```

helloworld.proto :

```syntax = "proto3";

package private;
option go_package = "proto";

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```
code:
```
import {GreeterPromiseClient} from "../assets/dist_proto/helloworld_grpc_web_pb";

const client = new GreeterPromiseClient(
  "http://localhost:8080",
  null,
  null
);
```

dependencies:
```
    "dependencies": {
        "@grpc/proto-loader": "0.7.4",
        "google-protobuf": "^3.21.2",
        "grpc-web": "^1.4.2"
    }
```

**Comment by harmeetsingh17** [comment]
> > @ZhangDewei This has come up several times in the past: #566, #377, but it was never really clear what went wrong, so we need a lot more information about your particular situation to proceed.
> > Can you give us more information on how to reproduce this? Can you give us
> > 
> > * a simplified version of your .proto
> > * the ` protoc` command
> > * your `package.json` file
> > * your main `client.js`, which imports these generated files
> > * when exactly did this error happen? does this happen during compile time? Or does this happen at runtime, in the browser?
> > * If this happens at runtime in the browser, how did you compile your javascript files?
> > 
> > Please be as detail as possible. Thanks.
> 
> Thank you. The problem is solved

@ZhangDewei how was the problem solved?

**Comment by harmeetsingh17** [comment]
> i have same problem.
> 
> driver's: *protoc-3.20.1-win64 (version 3.21.12 not work, reason: protoc-gen-js not found) *protoc-gen-grpc-web-1.4.2-windows-x86_64
> 
> command:
> 
> ```
> protoc -I=src/assets/proto helloworld.proto --js_out=import_style=commonjs:./src/assets/dist_proto --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:./src/assets/dist_proto
> ```
> 
> helloworld.proto :
> 
> ```yaml
> package private;
> option go_package = "proto";
> 
> // The greeting service definition.
> service Greeter {
>   // Sends a greeting
>   rpc SayHello (HelloRequest) returns (HelloReply) {}
> }
> 
> // The request message containing the user's name.
> message HelloRequest {
>   string name = 1;
> }
> 
> // The response message containing the greetings
> message HelloReply {
>   string message = 1;
> }
> ```
> 
> code:
> 
> ```
> import {GreeterPromiseClient} from "../assets/dist_proto/helloworld_grpc_web_pb";
> 
> const client = new GreeterPromiseClient(
>   "http://localhost:8080",
>   null,
>   null
> );
> ```
> 
> dependencies:
> 
> ```
>     "dependencies": {
>         "@grpc/proto-loader": "0.7.4",
>         "google-protobuf": "^3.21.2",
>         "grpc-web": "^1.4.2"
>     }
> ```

@wilywork were you able to fix the issue?

**Comment by wilywork** [comment]
@harmeetsingh17 , yes, the problem in the code.
example final:
```
export default {
  client: null,
  connect() {
    console.log("[connect]....");
    this.client = new GreeterClient("http://localhost:8080");
  },

  send(messsage: string) {
    const user = new HelloRequest();
    user.setName(messsage);

    this.client.sayHello(user, null, function (err: any, response: any) {
      if (err) console.log(err);
      console.log("Greeting:", response);
    });
  },
};
```

**Comment by acdcjunior** [comment]
Folks, for anyone reading this in the future, I got the same error and the problem was the arguments I was passing to the grpc function.

So for a proto with a method like:

```proto
service MyService {
  rpc MyMethod (MyRequest) returns (MyReply) {}
}
message MyRequest {
  string myField = 1;
}
```

So I was doing:


```js
client.myMethod({ myField: 'foobar' }, {}, function (err: any, response: any) {
```

But this is what I should've been doing:

```js
const myReq = new MyRequest();
myReq.setMyField('foobar');

client.myMethod(myReq, {}, function (err: any, response: any) {
```

which made the issue go away.

**Comment by Mauville** [comment]
I had to tap into a blackbox that was using grpc-web, and what worked for me was compiling with `binary` support on the platform I was targeting.

````
protoc -I. --js_out=import_style=commonjs,binary:./fe/src/api/ /
--grpc-web_out=import_style=commonjs,mode=grpcwebtext:./fe/src/api/ xxx.proto
````
