### ISSUE TITLE
grpc-web request grpc-server err: "upstream connect error or disconnect/reset before headers. reset reason: connection failure"

### ISSUE THREAD

**Issue by ZhangDewei** [grpc/grpc-web#907]
I use grpc-web request envoy proxy to use grpc-python server. But found err: "upstream connect error or disconnect/reset before headers. reset reason: connection failure" My code is as follows:
first envoy：
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9902 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8000 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: grpc_json
                use_remote_address: true
                add_user_agent: true
                upgrade_configs:
                   upgrade_type: websocket
                   enabled: true
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: user
                            max_grpc_timeout: 0s
                      cors:
                        allow_credentials: true
                        allow_origin:
                          - "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,cookie,token,remote_ip,x-forwarded-for,apiSource
                        max_age: "1972800000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                        enabled: true
                http_filters:
                  - name: envoy.grpc_json_transcoder
                    config:
                      proto_descriptor: "/tmp/envoy/proto.pb"
                      services: ["chatman.Chat"]
                      print_options:
                        add_whitespace: true
                        always_print_primitive_fields: true
                        always_print_enums_as_ints: false
                        preserve_proto_field_names: false
                  - name: envoy.grpc_web
                  - name: envoy.cors
                  - name: envoy.router
  clusters:
    - name: user
      connect_timeout: 0.25s
      type: static
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
       cluster_name: user
       endpoints:
       - lb_endpoints:
         - endpoint:
             address:
               socket_address:
                 address: 127.0.0.1
                 port_value: 5000
     #  hosts: [{ socket_address: { address: 10.130.21.100, port_value: 5001 } }]

then js:
var client = new ChatClient('http://127.0.0.1:8000');
    var request = new ChatRequest();
    request.setMessages = 'dewei-grpc-web';
    client.chat(request, {}, function(err, response){
        if(err) {
          console.log('err', err)
        } else {
          console.log('result', response);
        }
    });

I use grpc-python-client to request grpc-python-server ok; help please.

**Comment by stanley-cheung** [comment]
This is a general error that Envoy cannot connect to your backend service. There can be a variety of issues in your particular environment. Is your service running? Is it listening on port :5000 as indicated? Can you connect to your service via another client? Are you running either your Envoy instance or your grpc backend instance from docker? If so, did you use the `--network=host` to make sure the host can access that port in your container?

Or, taking a step back, are you able to run the helloworld example? https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld.
