### ISSUE TITLE
Inter-op test for the Go middleware (from Improbable)

### ISSUE THREAD

**Issue by wenbozhu** [grpc/grpc-web#91]
See https://github.com/grpc/grpc-web/issues/60

@mwitkow

**Comment by johanbrandhorst** [comment]
Bump. We need clarity on how this client interops with the Improbable backend proxy.

**Comment by johanbrandhorst** [comment]
I desperately think this needs to be completed before GA (if you're still aiming for October).

**Comment by stanley-cheung** [comment]
Added a demo to show interoperability with the Improbable gRPC Web Go Proxy
```
docker-compose up echo-server grpcwebproxy binary-client
```
