### ISSUE TITLE
relative URLs (with subpath) not supported anymore in 1.2.0

### ISSUE THREAD

**Issue by mathijs81** [grpc/grpc-web#911]
We use grpc-web and have set up our server to forward /grpc/* to the grpc-web-proxy.

We could then in the webapp instantiate our service with
```
const endpoint = '/grpc';
const client = new OurProductWebServiceClient(endpoint, null, null);
```
and everything would work.

The commit https://github.com/grpc/grpc-web/commit/9d96b7a4b833b95413819ae50e34ad97e591fecb changed the URL handling and now setting the endpoint to '/grpc' gives a `Failed to construct 'URL': Invalid base URL` error.

It seems endpoint has to be a hostname now for the new setup to work, and this makes it impossible to serve the grpc traffic under a subdirectory (because `new URL('/something', 'http://localhost:8080/grpc/')` just strips out the `grpc` part and returns `http://localhost:8080/something`).

Is it possible to change the client so that a subdirectory is allowed?
(Looking at the source, just dropping the leading `/` from `/$package_dot$$service_name$/$method_name$` would allow us to specify `window.location.origin + '/grpc/'` as the endpoint and then the paths would be correct again)

**Comment by stanley-cheung** [comment]
This is subsequently reverted in #866. I should be cutting a `1.2.1` release soon which will contain that revert.
