### ISSUE TITLE
FEATURE_PROTO3_OPTIONAL' is not a member of 'google::protobuf::compiler::CodeGenerator'

### ISSUE THREAD

**Issue by miljkovicivan** [grpc/grpc-web#912]
We're building grpc-web as plugin. After successful build of https://github.com/protocolbuffers/protobuf/releases/download/v3.10.1/protobuf-all-3.10.1.tar.gz
`./configure --prefix=/usr && make -j$(nproc) && make check && make install && ldconfig` we build grpc-web with `make install-plugin` and get following error

```
[root@93fe1e1908f8 grpc-web]# make install-plugin
cd "/grpc-web"/javascript/net/grpc/web && make install
make[1]: Entering directory `/grpc-web/javascript/net/grpc/web'
g++ -std=c++11 -I/usr/local/include -pthread  -c -o grpc_generator.o grpc_generator.cc
grpc_generator.cc:1601:12: error: 'uint64_t grpc::web::{anonymous}::GrpcCodeGenerator::GetSupportedFeatures() const' marked override, but does not override
   uint64_t GetSupportedFeatures() const override {
            ^
grpc_generator.cc: In member function 'uint64_t grpc::web::{anonymous}::GrpcCodeGenerator::GetSupportedFeatures() const':
grpc_generator.cc:1603:12: error: 'FEATURE_PROTO3_OPTIONAL' is not a member of 'google::protobuf::compiler::CodeGenerator'
     return CodeGenerator::FEATURE_PROTO3_OPTIONAL;
            ^
make[1]: *** [grpc_generator.o] Error 1
make[1]: Leaving directory `/grpc-web/javascript/net/grpc/web'
make: *** [install-plugin] Error 2
```

We tried using older versions of this repo but without success.

Last time this course of commands were working is 19.07.2020

**Comment by stanley-cheung** [comment]
The minimal protobuf version has been updated to 3.12. So please try starting with something like version 3.12.2 or 3.12.3.

The way to check is to look at our `third_party` submodule links: https://github.com/grpc/grpc-web/tree/master/third_party. the `grpc/grpc` link has been updated to `v1.30.0`, which in turns has a `third_party/protobuf` link which points to version `3.12.2`.

**Comment by janiskemper** [comment]
I got the same error with protobuf version 3.13.0. Do you have any other suggestions of where the error might come from?
