### ISSUE TITLE
Error while running docker-compose pull

### ISSUE THREAD

**Issue by stupidly-logical** [grpc/grpc-web#928]
```
docker-compose pull
Pulling java-interop-server (grpcweb/java-interop-server:latest)...
ERROR: pull access denied for grpcweb/java-interop-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

**Comment by stanley-cheung** [comment]
This is not going to work. We haven't uploaded all the images specified in the base `docker-compose.yml` to Docker Hub. You will have to do `docker-compose build` if you want to build these images. 

In fact, we are probably not going to maintain these docker images in the future. It adds quite a lot of overhead to each release process for not that much benefit. After we have deprecated those Docker Hub images, we will remove all documentations involving any `docker-compose pull` commands.
