### ISSUE TITLE
Documentation for PromiseClient

### ISSUE THREAD

**Issue by semin-park** [grpc/grpc-web#932]
I'd like to know if there are any documentation on the promise based client.

grpc-web is my first encounter with grpc and I'm a little bit confused where all the documentation are. Am I expected to know grpc in order to understand grpc-web?

**Comment by emil14** [comment]
It's hard to figure out stuff without good docs :) Please add docs for Promise based clients

**Comment by danieleades** [comment]
While we're at it, what's the state of the promise client with respect to the typescript output? Last I checked in only the js output contained the promise client. Is this still the case?

**Comment by colemars** [comment]
Any word on this? I keep seeing `PromiseClient` mentioned and used around the web but can't find anything on how to use it / if it's stable.

**Comment by SimulShift** [comment]
> While we're at it, what's the state of the promise client with respect to the typescript output? Last I checked in only the js output contained the promise client. Is this still the case?

I am still interested in this. Yeah, looks like only the js output has the promise client. Let's get the typescript promise client going.

**Comment by sampajano** [comment]
Hi thanks for the request (and patience 😃)!

Actually i think Typescript client (i.e. `import_style=typescript`) generates Promise methods too (on the same client).

```
  echo(
    request: echo_pb.EchoRequest,
    metadata: grpcWeb.Metadata | null): Promise<echo_pb.EchoResponse>;
```

I'll work on a PR to document this :)

Thanks!
