### ISSUE TITLE
Intercept Request

### ISSUE THREAD

**Issue by novi** [grpc/grpc-web#945]
I would like to append some metadata(may be auth token) into the requests on every unary call.
`StreamInterceptor` would be good to do this in client(web browser) side.
But there is no `setMetadata()` method on `Request` class.
Here is my workaround.
So, Are interceptors and request classes not intended for dealing these situation? 

```ts
class WrappedRequest implements Request<any, any> {
  req: Request<any, any>
  constructor(req: Request<any, any>) {
    // wrap original request
    this.req = req
  }

  getCallOptions(): CallOptions {
    return this.req.getCallOptions();
  }

  getMetadata(): Metadata {
    return {
      'Authorization': // set JWT or something auth token here
    }
  }

  getMethodDescriptor(): MethodDescriptor<any, any> {
    return this.req.getMethodDescriptor();
  }

  getRequestMessage(): any {
    return this.req.getRequestMessage()
  }
}

class AuthInterceptor implements StreamInterceptor<any, any> {
  intercept(request: Request<any, any>, invoker: (request: Request<any, any>) => ClientReadableStream<any>): ClientReadableStream<any> {
    return invoker(new WrappedRequest(request));
  }
}
```

**Comment by uwemaurer** [comment]
the Metadata is mutable, you can do it without this wrapper class and just modify the request like this:

` request.getMetadata().Authorization = authToken;`

**Comment by novi** [comment]
Thanks. It works and I eliminated this wrapper class.
