### ISSUE TITLE
Missing TypeScript return type for serverStreaming

### ISSUE THREAD

**Issue by dnasir** [grpc/grpc-web#950]
Toolset versions
* protoc 3.13.0
* protoc-gen-grpc-web 1.2.1
* grpc-web 1.2.1
* typescript 4.0.2

I recently updated to the latest version of the libraries described above, and I started getting the following TypeScript error for all of my serverside streaming methods.

```
Type 'ClientReadableStream<unknown>' is not assignable to type 'ClientReadableStream<SubscribeMarkersResponse>'.
  Type 'unknown' is not assignable to type 'SubscribeMarkersResponse'.ts(2322)
```

I've included the relevant code below.

Proto file - simplified for brevity.
```proto
syntax = "proto3";

option csharp_namespace = "RTMap.GrpcService";

package rtmap;

service RTMap {
    rpc SubscribeMarkers (SubscribeMarkersRequest) returns (stream SubscribeMarkersResponse);
}

message SubscribeMarkersRequest {
}

message SubscribeMarkersResponse {
    repeated Marker data = 1;
}

message Marker {
    string id = 1;
    string transport_mode = 2;
    double lat = 3;
    double lng = 4;
}
```

Generated TS client - simplified for brevity.
```typescript
  subscribeMarkers(
    request: SubscribeMarkersRequest,
    metadata?: grpcWeb.Metadata) {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/rtmap.RTMap/SubscribeMarkers',
      request,
      metadata || {},
      this.methodInfoSubscribeMarkers);
  }
```

The signature for `_serverStreaming` is as follows;

```
(method) AbstractClientBase.serverStreaming<rtmap_pb.SubscribeMarkersRequest, unknown>(method: string, request: rtmap_pb.SubscribeMarkersRequest, metadata: grpcWeb.Metadata, methodDescriptor: grpcWeb.MethodDescriptor<rtmap_pb.SubscribeMarkersRequest, unknown>): grpcWeb.ClientReadableStream<...>
```

So it's clear that `_serverStreaming` is not returning the correct return type.

This is not the case for regular unary calls.

**Comment by nadilas** [comment]
Can confirm, just ran into this.
Any updates?

**Comment by zefir01** [comment]
yes, there is such a problem. it is in grpc-web version 1.2.1. in grpc-web 1.2.0 everything is fine.

**Comment by lukasmoellerch** [comment]
The way I see it the core of this problem is that the `MethodDescriptor` has unknown generic Type Arguments. If the constructor would be able to infer the `REQ` / `RESP` types from its parameters no code generation changes would be required. I can quickly create a PR which outlines that idea.
