### ISSUE TITLE
share a simplest nginx proxy config for grpc-web

### ISSUE THREAD

**Issue by jmzwcn** [grpc/grpc-web#958]
server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /zbay {
        grpc_set_header Content-Type application/grpc;
        grpc_pass grpc://zbay:50051;
    }
}

just an attention: "mode=grpcweb" is needed, but server stream still be supported.

**Comment by stanley-cheung** [comment]
Sorry the grpc-web custom module for nginx is no longer being supported [soon](#870).

**Comment by jmzwcn** [comment]
No, don't need custom module, just nginx official release~~

**Comment by sirudog** [comment]
@jmzwcn Maybe I am missing something here, but the nginx official release still does not support proxying grpc-web requests, only grpc. That is why we need the custom module mentioned by @stanley-cheung, and build a custom nginx based on an old google fork of nginx.

**Comment by jmzwcn** [comment]
Haha, that is just surprised. Try and come on.
