### ISSUE TITLE
unable to pull grpcweb/prereqs from docker

### ISSUE THREAD

**Issue by byteshiva** [grpc/grpc-web#959]
I'm just trying simple echo example using grpcweb, the source as available at [https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo)
As part of executing I was following the docker steps, it failed at `Serve static JS/HTML contents
`,

unable to pull grpcweb/prereqs from docker, it throws says error after successful docker login.
```
grpc-web$ docker build -t grpcweb/commonjs-client -f net/grpc/gateway/docker/commonjs_client/Dockerfile .
Sending build context to Docker daemon  2.449MB
Step 1/8 : FROM grpcweb/prereqs
pull access denied for grpcweb/prereqs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

**Comment by ssnorrizaurous** [comment]
You have to build the base container first, see [Build pre-requisites section](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo#build-pre-requisites).

**Comment by byteshiva** [comment]
> You have to build the prereq container first. The [Build pre-requisites section](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo?rgh-link-date=2020-09-22T12%3A28%3A23Z#build-pre-requisites) could be updated to include the following to assist users. Also, considering how long this container takes to build consider making it not a dependency for examples.
> 
> ` docker build -t grpcweb/prereqs \ -f net/grpc/gateway/docker/prereqs/Dockerfile .`

Thanks @ssnorrizaurous,

It worked, after building prereqs ie., `docker build -t grpcweb/prereqs \ -f net/grpc/gateway/docker/prereqs/Dockerfile .`

`

sample screen.
![image](https://user-images.githubusercontent.com/10637299/94027633-adde1f00-fdd8-11ea-8299-d1e9cabf2a09.png)

**Comment by chanced** [comment]
Sounds like you can close the issue.
