### ISSUE TITLE
Usage of modify map unclear

### ISSUE THREAD

**Issue by wdfinch** [grpc/grpc-web#960]
When a map is compiled, the methods `getChildUnitsMap()` and `clearChildUnitsMap()` are generated. However, there are no generated methods to modify a map.

After digging quite a bit, I realized that in order to modify a map, you must use `getChildUnitsMap()` followed by the modify method (`set()`, `remove()`, etc.)

I think this is unclear as `getChildUnitsMap()` implies I am receiving a read-only version of the map. Therefore, would it be possible to add generated methods for modifying a map or at least make this more clear in the docs?

**Comment by stanley-cheung** [comment]
This is a protobuf issue, not grpc-web's.
