### ISSUE TITLE
How to enable keepalives to keep streams alive with envoy

### ISSUE THREAD

**Issue by mastergberry** [grpc/grpc-web#961]
Hey.

Our team has been using gRPC for a few years now and we have had a lot of success with it. We are using a gRPC setup in AWS with Elastic Load Balancer (ELB) in front of it by using a Network Load Balancer (NLB). We have our own custom solution in place that we wrote before gRPC became popular (we are pretty early adopters, and grpc-web was not a thing at the time), and we want to try and migrate away from these. They are buggy and not the most stable thing. In our testing of grpc-web we have noticed that there is no keep alive spec available...which is critical for us to be able to make this transition. AWS will automatically terminate any connections on ELB that do not receive any data over the connection in 1 minute. To circumvent this on the other gRPC libraries we are using the keep alive spec...which does not seem to be available here.

Is there some way to do these keep alives? Is there something in envoy that we can use to make it so that keep alives are being used to keep the socket connection active for AWS ELB?

Also going to tag @stanley-cheung specifically since I saw a comment recently talking about some legacy nginx code being removed soon which looks like it supported some form of keepalive.

Thanks.

**Comment by stanley-cheung** [comment]
Tracked in #132
