### ISSUE TITLE
Bug with trailers and headers.

### ISSUE THREAD

**Issue by visortelle** [grpc/grpc-web#962]
```
// Versions:

docker envoy: envoyproxy/envoy:v1.15.0

npm: "grpc-web": "1.2.1"
npm: "google-protobuf": "3.13.0"

go mod:	google.golang.org/grpc v1.32.0
go mod:	google.golang.org/protobuf v1.25.0
```

I can't receive trailers metadata when using `grpc.SetTrailer()`.

If I add a `grpc.SetHeader()` call with any value, the behavior is as I expect.

The issue doesn't reproduce in grcpcurl/grcpcui.

Hi! Can please someone explain this behavior? Is it a grpc-web or envoy bug or am I doing something wrong?

## Variant 1. Unexpected behavior.

**go server**

```
...
grpc.SetTrailer(ctx, metadata.Pairs("t1", "t1-value"))
grpc.SetTrailer(ctx, metadata.Pairs("t2", "t2-value"))
return nil, status.Error(codes.Unauthenticated, "You are unaunthenticated")
```

**grpcui** directly to server without envoy proxy.

Everything as expected.

![Screen Shot 2020-09-22 at 11 01 03 PM](https://user-images.githubusercontent.com/9302460/93931469-7f543b80-fd27-11ea-9bd1-62064cde675a.png)

**chrome network tab**

Why `t1` and `t2` are HTTP headers?

![Screen Shot 2020-09-22 at 10 59 31 PM](https://user-images.githubusercontent.com/9302460/93931288-47e58f00-fd27-11ea-8794-926d85a1add8.png)

**chrome console tab**

Why `t1` and `t2` is missing in error metadata?

![Screen Shot 2020-09-22 at 11 00 08 PM](https://user-images.githubusercontent.com/9302460/93931363-5df34f80-fd27-11ea-9917-4b12add7465a.png)

## Variant 2. Expected behavior.

**go server**

With added `grpc.SetHeader` call.

```
...
grpc.SetHeader(ctx, metadata.Pairs("h1", "b"))
grpc.SetTrailer(ctx, metadata.Pairs("t1", "t1-value"))
grpc.SetTrailer(ctx, metadata.Pairs("t2", "t2-value"))
return nil, status.Error(codes.Unauthenticated, "You are unaunthenticated")
```

**grpcui** directly to server without envoy proxy.

Everything ok as expected.

![Screen Shot 2020-09-22 at 11 05 57 PM](https://user-images.githubusercontent.com/9302460/93931986-2e911280-fd28-11ea-92de-ef9eeee926be.png)

**chrome network tab**

The `h1` is here, but `t1` and `t2` are missing.

![Screen Shot 2020-09-22 at 11 07 10 PM](https://user-images.githubusercontent.com/9302460/93932105-5b452a00-fd28-11ea-85cb-cc32375135ae.png)

**chrome console tab**

`t1` and `t2` are in error metadata as expected.

![Screen Shot 2020-09-22 at 11 08 17 PM](https://user-images.githubusercontent.com/9302460/93932215-82036080-fd28-11ea-9363-690c91fc77eb.png)

**Comment by stanley-cheung** [comment]
Have you added your custom header to your `envoy.yaml` file like this? https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L34  (and L32).

**Comment by visortelle** [comment]
@stanley-cheung yes, I tried. The problem isn't that I can't send a header. There is some inconsistent behavior.

If you'll take a look at the first case, `t1` and `t2` are in headers. And there is no `t1` and `t2` in error response metadata.

In the second case, the only thing I did is `setHeader("randomHeaderName")`. Then `t1` and `t2` are being missed from HTTP headers and being added to errors metadata. And the header with the name `randomHeaderName`  is in received HTTP headers.

There is no difference in `envoy.yaml` file between these two cases.

If you want, I can reproduce it and prepare a project with docker-compose for you.

**Comment by yzha5** [comment]
i have this question also

interceptor.go:
```go
func testInterceptor() grpc.UnaryServerInterceptor {
	return func(
		c context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler,
	) (resp interface{}, err error) {
		
		_ = grpc.SetTrailer(c, metadata.Pairs("trailer-key", "trailer value"))
		
		//_ = grpc.SetHeader(c, metadata.Pairs("header-key", "header value"))
		
		return handler(c, req)
	}
}
```
server.go:
```go
func (s *MyTestServer) TestInterceptor(ctx context.Context, req *pb.Req) (*pb.Res, error) {
	if len(req.V) > 5 {
		return &pb.Res{Val: req.V}, errors.New("the length of the string should be less than 5")
	}
	return &pb.Res{Val: req.V}, nil
}
```
grpc-web.request.ts:
```ts
function req() {
	const client = new DemoClient(hostName)
	const request = new Req()
	request.setV('123')
	client.testInterceptor(request, null, (err, res) => {
	        console.log('error', err)
	        console.log('response', res)
	    })
	    .on('status', (status) => {
	        console.log('status', status)
	    })
}
```
---
**example 1**
When `grpc-web.request` sends a request and the server does not return an error，`console.log('status', status)`printed:
```
{
    "code": 0,
    "details": "",
    "metadata": {
        "trailer-key": "trailer value"
    }
}
```
When `grpc-web.request` sends a request and the server returns an error,`console.log('status', status)`printed:
```
{
    "code": 2,
    "details": "the length of the string should be less than 5",
    "metadata": {
        "content-length": "0",
        "content-type": "application/grpc-web+proto",
        "grpc-message": "the length of the string should be less than 5",
        "grpc-status": "2"
    }
}
```
---
**example 2**
If add `grpc.SetHeader(c, metadata.Pairs("header-key", "header value"))` to the interceptor,

When `grpc-web.request` sends a request, whether or not the server returns an error, `console.log('status', status)`printed:
```
{
    "code": 0,
    "details": "",
    "metadata": {
        "trailer-key": "trailer value"
    }
}
```

**Comment by jhump** [comment]
> **chrome network tab**
>
> Why t1 and t2 are HTTP headers?

@visortelle, this is actually part of the gRPC spec. If an operation returns an immediate error (so no response messages), it may send what's called a "trailers only" response. (Search for "trailers-only" in [this section of the protocol spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses).) In this mode, all trailers (including the "grpc-status" and "grpc-message" trailers) are sent as HTTP headers, and the stream concludes with that (no response data).

A trailers only response is also allowed with gRPC-Web, where the trailers are actually sent as HTTP headers and then there is no response body.

Because you didn't use any custom header values in the first case, a trailers only response was used. In turn, since "t1" and "t2" ended up being sent as HTTP headers, they were likely stripped from the response that is accessible to your JS code due to CORS. When configuring which headers that are allowed/exposed, your CORS/envoy config needs to also list trailers that should be allowed/exposed, so they can also end up in HTTP headers.
