### ISSUE TITLE
Builds protoc from source

### ISSUE THREAD

**Issue by alexeagle** [grpc/grpc-web#967]
I updated to latest rules_proto to pick up this brilliant work
https://github.com/bazelbuild/rules_proto/pull/36 
which means I can build `proto_library` targets without needing a working C++ compile toolchain on the machine (some devs at my company have incompatible protobuf header files on the LD_PATH for example)

However even with v1.2.1 of grpc_web, it is building `@com_github_protocolbuffers_protobuf//:protoc_lib` from source. 
I think that's because the grpc bits are built into the cc_binary
https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/BUILD.bazel#L11

Is there a way to do this without building protoc from source? Can this be formulated as a plugin to the pre-built protoc instead?
/cc @Yannic hi! looks like you've been working in this area

**Comment by Yannic** [comment]
The good news is that, as of https://github.com/grpc/grpc-web/pull/872, using a custom (pre-build) plugin is feasible. The bad news is that I won't have time to work on it anytime soon.

If you (or anyone else interested in it) want to contribute this, I'm happy to provide some guidance and help with the review! Let me know what you think.

**Comment by sampajano** [comment]
Thanks for the discussions :) I'm closing this now since i believe this is legacy now :)
