### ISSUE TITLE
[Problem]It is difficult to implement grpc-web client without NodeJS and WebPack.

### ISSUE THREAD

**Issue by diuming** [grpc/grpc-web#974]
I don't want to use NodeJS as a server in production environment.(performance issue)
So difficult to use(sorry).

```
grpc-web -> npm i grpc-web (install to local and copy to appropriate location)
const grpc = {};
grpc.web = require('grpc-web');
```

Error: Module name "HelloWorld_pb.js" has not been loaded yet for context: _. Use require([])
Error: Module name "HelloWorld_grpc_web_pb.js" has not been loaded yet for context: _. Use require([])
[Error] TypeError: undefined is not a constructor (evaluating 'new GreeterClient('http://localhost:9090')')
	Global Code (commonjs:13)
[Error] TypeError: goog.exportSymbol is not a function. (In 'goog.exportSymbol('proto.helloworld.HelloReply', null, global)', 'goog.exportSymbol' is undefined)
Global Code (HelloWorld_pb.js:15)
[Error] TypeError: undefined is not an object (evaluating 'grpc.web.MethodType.UNARY')
Global Code (HelloWorld_grpc_web_pb.js:81)
[Error] ReferenceError: Can't find variable: exports
Global Code (google-protobuf.js:522:227)
[Error] ReferenceError: Can't find variable: module
[Error] Error: Script error for "/JavaScripts/grpc-web"
https://requirejs.org/docs/errors.html#scripterror
[Error] ReferenceError: Can't find variable: exports
Global Code (google-protobuf.js:522:227)

**Comment by diuming** [comment]
leave grpc-web

**Comment by raghava2706** [comment]
Hi @diuming, how did you solve this issue, I am having the same issues.
Module name "google-protobuf" has not been loaded yet for context: _. Use require([])
Uncaught TypeError: Cannot read properties of undefined (reading 'exportSymbol') while executing `goog.exportSymbol('proto.google.protobuf.ListValue', null, global);`
