### ISSUE TITLE
Argument of type 'MethodInfo<Request, Response>' is not assignable to parameter of type 'MethodDescriptor<Request, Response>'

### ISSUE THREAD

**Issue by eric-heihei** [grpc/grpc-web#981]
Error:Argument of type 'MethodInfo<Request, Response>' is not assignable to parameter of type 'MethodDescriptor<Request, Response>'

grpc-web version is 1.2.1
google-protoc version is 3.13.0

proto file is:
syntax = "proto3";

package user;
option go_package = "server/user";

service AuthService {
    // user login
    rpc Login (Auth.Login.Request) returns (Auth.Login.Response);
}

message Auth {
    message Login {
        message Request{
            string loginname = 1;
            string password = 2;
        }
        message Response {
            bytes token = 1;
        }
    }
}

Generate typescript file is :

/**
 * @fileoverview gRPC-Web generated client stub for user
 * @enhanceable
 * @public
 */

// GENERATED CODE -- DO NOT EDIT!

import * as grpcWeb from 'grpc-web';

import {
  Auth} from './auth_pb';

export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: string; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: string; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname;
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodInfoLogin = new grpcWeb.AbstractClientBase.MethodInfo(
    Auth.Login.Response,
    (request: Auth.Login.Request) => {
      return request.serializeBinary();
    },
    Auth.Login.Response.deserializeBinary
  );

  login(
    request: Auth.Login.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.Error,
               response: Auth.Login.Response) => void) {
    return this.client_.rpcCall(
      this.hostname_ +
        '/user.AuthService/Login',
      request,
      metadata || {},
      this.methodInfoLogin,
      callback);
  }

}

How to solve this question? Thanks

**Comment by stanley-cheung** [comment]
Have you re-compiled (or downloaded) the latest `protoc-gen-grpc-web` plugin? Also perhaps double check if your PATH is using this latest version? Coz it looks like your generated code is not using the latest version of the plugin - each generated RPC should have a corresponding MethodDescriptor object instantiated in the generated code.

**Comment by eric-heihei** [comment]
@stanley-cheung

**Comment by uwemaurer** [comment]
what version of the typescript compiler are you using?

It sound like the problem I reported here: https://github.com/grpc/grpc-web/issues/944

There generated typescript code currently only compiles with type checking disabled.  The type checking is disabled on newer typescript compilers (>=3.7) with the `//@ts-nocheck`  comment, however it fails on older version of the compiler.
