### ISSUE TITLE
TypeScript client constructor has incorrect type for ClientOptions: `{ [index: string]: string; }`.

### ISSUE THREAD

**Issue by mfickett** [grpc/grpc-web#982]
## Expected

Able to compile in TypeScript:

```ts
class AuthInterceptor {
  intercept(request: any, invoker: any) {        
    return Vue.prototype.$auth.getAccessToken().then((token: string) => {
      const metadata = request.getMetadata();
      metadata.Authorization = `Bearer ${token}`;
      return invoker(request);
    });
  }
}
const authInterceptor = new AuthInterceptor();
const standardOptionsWithAuth = {
  unaryInterceptors: [authInterceptor],  
  streamInterceptors: [authInterceptor]  
};

const client = new MyServiceClient(
    PROXY_ADDRESS,
    null /* no creds */,
    standardOptionsWithAuth
  );
```

## Observed

I get an error that:

```
Argument of type '{ unaryInterceptors: AuthInterceptor[]; streamInterceptors: AuthInterceptor[]; }' is not assignable to parameter of type '{ [index: string]: string; }'.
  Property 'unaryInterceptors' is incompatible with index signature.
    Type 'AuthInterceptor[]' is not assignable to type 'string'.
```

I see in the generated code:

```ts
export class MyServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: string; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: string; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname;
    this.credentials_ = credentials;
    this.options_ = options;
  }
...
```

However, in the [`GrpcWebClientBase`](https://github.com/grpc/grpc-web/blob/cce2f19faac594590bb9b8ba96192ee0b2e3b9c8/javascript/net/grpc/web/grpcwebclientbase.js#L56) it uses [ClientOptions](https://github.com/grpc/grpc-web/blob/cce2f19faac594590bb9b8ba96192ee0b2e3b9c8/javascript/net/grpc/web/clientoptions.js#L11):

```js
class GrpcWebClientBase {
  /**
   * @param {!ClientOptions=} options
   */
  constructor(options = {}) {
...
```

## Requested Change

Please update the type declaration for the `options` constructor argument. It would also be great to have an example of declaring and using an interceptor in TypeScript if that's possible (and doesn't already exist)!

## Versions

```
    "google-protobuf": "^3.13.0",
    "grpc-web": "^1.2.1",
    "@types/google-protobuf": "^3.7.3",
```

I'm generating the proto files following the [grpc-web docs for TypeScript support](https://github.com/grpc/grpc-web#typescript-support):

```bash
    protoc \
        -I ../../interface \
        --js_out=import_style=commonjs,binary:${OUT} \
        --grpc-web_out=import_style=typescript,mode=grpcwebtext:${OUT} ${infile}
```

**Comment by stanley-cheung** [comment]
Hm, I am a bit confused. The `ClientOptions` class is new. It hasn't been released. Are you somehow using a mismatched version of the library (like using the `master` HEAD somehow)?

And you are not supposed to specify both of these
```
const standardOptionsWithAuth = {
  unaryInterceptors: [authInterceptor],  
  streamInterceptors: [authInterceptor]  
};
```

This is a full example of using `streamInterceptors` when you are using the normal callback-based client (i.e. xxxxxClient): https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/test/tsc-tests/client03.ts

This is a full example of using `unaryInterceptors` when you are using the promise-base client (i.e. xxxPromiseClient): https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/test/tsc-tests/client04.ts

**Comment by mfickett** [comment]
Thanks for the example links, that's very helpful for getting all the imports/types in the interceptor declaration.

I only saw `ClientOptions` in GitHub, so maybe it's irrelevant. I'm getting the `grpc-web` libraries from NPM (versions in the first comment), and `protoc` matches: `protoc --version` says `libprotoc 3.13.0`.

But still, generated TypeScript code types `options` as `{ [index: string]: string; }` (as in the constructor copied in the 1st comment) and even using the new interceptor declaration with correct types, when I try to pass in my `{streamInterceptors: [new MyAuthInterceptor()]}` I get that same error from the first comment. It'll run and seems to work, but the compiler says it's wrong.

Having imported my client with `import { MyServiceClient } from "../../gen-proto/My_serviceServiceClientPb";` I get:

```
ERROR in /path/to.../client/web/src/services/GrpcService.ts(57,7):
57:7 Type 'AuthInterceptor[]' is not assignable to type 'string'.
    54 | const client = new MyServiceClient(
    55 |     PROXY_ADDRESS,
    56 |     null /* no creds */,
  > 57 |     { streamInterceptors: [new AuthInterceptor()] }
       |       ^
    58 |   );
```

**Comment by uwemaurer** [comment]
In this change https://github.com/grpc/grpc-web/commit/9b73daa52193f9bbc90d5b2cd01c3199ba917858#diff-0520f789a9bbf4b945615569ffb5725475612d5a87c0022fe58d2cbad6b7ff05

the options were changed like this:
 
```
-        "             options?: null | { [index: string]: string; }) {\n");
+        "             options?: null | { [index: string]: any; }) {\n");
```

so it really looks like you are generating with an older version of the grpc-web plugin. Maybe look at your PATH to see if an older version is used. Would be helpful if the generator would write its own version number in a comment into the generated files.

**Comment by mfickett** [comment]
Thanks! I had `1.2.0_1` and upgrading to `1.2.1` and confirm that now I get the `any` type for the options values, and the code snippet I had above compiles without type errors.

I had used `brew` to install the plugin, which is easy but doesn't guarantee that other devs get the same version. I see [a few packages on NPM](https://www.npmjs.com/search?q=protoc-gen-grpc-web) but none of them has `1.2.1` yet; it would be convenient if I could get the plugin via NPM and then specify the version requirement in my `package.json`. But it looks like [the releases here](https://github.com/grpc/grpc-web/releases) are up to date and `brew` did have the new version, so it was easy to upgrade.

I agree adding a tool version line to the generated files would be great.
