### ISSUE TITLE
Mentioning third-party projects that support gRPC-Web?

### ISSUE THREAD

**Issue by trustin** [grpc/grpc-web#989]
Hi,

`README.md` currently only mentions the future plan for supporting gRPC-Web natively in language-specific web frameworks:

> In the future, we expect gRPC-Web to be supported in language-specific web frameworks for languages such as Python, Java, and Node. For details, see the roadmap.

Actually, there is already a framework that supports gRPC-Web out of the box - [Armeria](https://armeria.dev/docs/server-grpc/#grpc-web). Would it make sense to mention it (and other implementations as well if any) in `README.md` or somewhere else?

**Comment by trustin** [comment]
Gentle ping, gRPC team.

**Comment by trustin** [comment]
Geeentle ping, gRPC team.

**Comment by anuraaga** [comment]
@sampajano I randomly noticed https://github.com/grpc/grpc.io/issues/932 and when thinking of possibly opening something similar for Armeria, found @trustin had already done so a long time ago. Any thoughts on listing up more third party projects with grpc-web support like Armeria?

**Comment by trustin** [comment]
Yes, pretty please! 😄

**Comment by sampajano** [comment]
Thanks for the requests! Done in the above PR! 😃
