### ISSUE TITLE
solution for grpc-web and uint64 max values

### ISSUE THREAD

**Issue by bennyscetbun** [grpc/grpc-web#992]
Hi all,
We have an issue with grpc-web and uint64.
We know that javascript is using a 64bit floating number for all the numbers.
Therefor most of the uint64 values are approximated and false and we can't use them for user ids in javascript...

What solution would you got to use the whole uint64?
What about BigInt?

Thanks for the help

**Comment by stanley-cheung** [comment]
This is an issue for the [protobuf](https://github.com/protocolbuffers/protobuf/) repo.

**Comment by bennyscetbun** [comment]
Thanks i am going there right away
